//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.DB
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///科室信息
    /// </summary>
    public partial class T_DB_DB_SECTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_DB_DB_SECTION()
        {
            this.T_DB_DB_TEAM = new HashSet<T_DB_DB_TEAM>();
        }
    
        
    /// <summary>
    ///科室ID
    /// </summary>
    public string SECTION_ID { get; set; }
        
    /// <summary>
    ///科室编码
    /// </summary>
    public string SECTION_CODE { get; set; }
        
    /// <summary>
    ///科室名称
    /// </summary>
    public string SECTION_NAME { get; set; }
        
    /// <summary>
    ///科室职责
    /// </summary>
    public string SECTION_RESP { get; set; }
        
    /// <summary>
    ///科室状态
    /// </summary>
    public string SECTION_STATUS { get; set; }
        
    /// <summary>
    ///科室成立时间
    /// </summary>
    public System.DateTime SECTION_ESTABLISH_DATE { get; set; }
        
    /// <summary>
    ///科室地址
    /// </summary>
    public string SECTION_ADDR { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    
        public virtual T_DB_DB_DEPT T_DB_DB_DEPT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_DB_DB_TEAM> T_DB_DB_TEAM { get; set; }
    }
}
