//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.DB
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///零件认证ID与零件号关系
    /// </summary>
    public partial class T_DB_DB_SPEC_ID_PART
    {
        
    /// <summary>
    ///零件认证ID与零件号关系ID
    /// </summary>
    public string SPEC_ID_PART_ID { get; set; }
        
    /// <summary>
    ///车型系列号
    /// </summary>
    public string CAR_TYPE_SERIAL { get; set; }
        
    /// <summary>
    ///零件编码
    /// </summary>
    public string PART_NO { get; set; }
        
    /// <summary>
    ///型号规格认证ID
    /// </summary>
    public string MODEL_SPEC_ID { get; set; }
        
    /// <summary>
    ///CCC证书号认证ID
    /// </summary>
    public string CCC_CERT_ID { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///CCC证书号
    /// </summary>
    public string CCC_CERT_CODE { get; set; }
        
    /// <summary>
    ///规格型号
    /// </summary>
    public string SPECIF_MODEL { get; set; }
        
    /// <summary>
    ///供应商ID
    /// </summary>
    public string SUPPLIER_ID { get; set; }
        
    /// <summary>
    ///供应商名称
    /// </summary>
    public string SUPPLIER_NAME { get; set; }
    }
}
