//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.DB
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///员工信息
    /// </summary>
    public partial class T_DB_DB_EMP
    {
        
    /// <summary>
    ///员工ID
    /// </summary>
    public string EMP_ID { get; set; }
        
    /// <summary>
    ///员工编码
    /// </summary>
    public string EMP_CODE { get; set; }
        
    /// <summary>
    ///员工名称
    /// </summary>
    public string EMP_NAME { get; set; }
        
    /// <summary>
    ///员工等级
    /// </summary>
    public string EMP_LEVEL { get; set; }
        
    /// <summary>
    ///部门编码
    /// </summary>
    public string DEPT_CODE { get; set; }
        
    /// <summary>
    ///科室编码
    /// </summary>
    public string SECTION_CODE { get; set; }
        
    /// <summary>
    ///班组编码
    /// </summary>
    public string TEAM_CODE { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    
        public virtual T_DB_DB_POST T_DB_DB_POST { get; set; }
    }
}
