//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.DB
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///通知对象从表
    /// </summary>
    public partial class T_DB_DB_NOTICE_OBJ_D
    {
        
    /// <summary>
    ///通知对象从表ID
    /// </summary>
    public string NOTICE_OBJ_D_ID { get; set; }
        
    /// <summary>
    ///通知对象名
    /// </summary>
    public string NOTICE_OBJ_NAME { get; set; }
        
    /// <summary>
    ///确认状态:0-未确认;1-已确认;
    /// </summary>
    public string CONFIRM_STATUS { get; set; }
        
    /// <summary>
    ///确认时间
    /// </summary>
    public System.DateTime CONFIRM_DATE { get; set; }
        
    /// <summary>
    ///回复内容
    /// </summary>
    public string RETURN_REASON { get; set; }
        
    /// <summary>
    ///排序号
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    
        public virtual T_DB_DB_NOTICE_M T_DB_DB_NOTICE_M { get; set; }
    }
}
