//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.DB
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///成本中心信息表
    /// </summary>
    public partial class T_DB_DB_COST_CENTER
    {
        
    /// <summary>
    ///成本中心ID
    /// </summary>
    public string COST_CENTER_ID { get; set; }
        
    /// <summary>
    ///成本中心编码
    /// </summary>
    public string COST_CENTER_CODE { get; set; }
        
    /// <summary>
    ///有效期自
    /// </summary>
    public System.DateTime AVAI_DATE_END { get; set; }
        
    /// <summary>
    ///有效期至
    /// </summary>
    public System.DateTime AVAI_DATE_BEGIN { get; set; }
        
    /// <summary>
    ///公司编码
    /// </summary>
    public string COMP_CODE { get; set; }
        
    /// <summary>
    ///CCtC
    /// </summary>
    public string CCTC_DESC { get; set; }
        
    /// <summary>
    ///负责人
    /// </summary>
    public string PRINCIPAL_MAN { get; set; }
        
    /// <summary>
    ///部门ID
    /// </summary>
    public string DEPT_ID { get; set; }
        
    /// <summary>
    ///成本中心名称
    /// </summary>
    public string COST_CENTER_NAME { get; set; }
        
    /// <summary>
    ///成本中心描述
    /// </summary>
    public string COST_CENTER_DESC { get; set; }
        
    /// <summary>
    ///Ind
    /// </summary>
    public string IND_DESC { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
