//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.DB
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///邮件发送从表
    /// </summary>
    public partial class T_DB_DB_EMAIL_D
    {
        
    /// <summary>
    ///邮件发送从表ID:邮件发送从表ID
    /// </summary>
    public string EMAIL_D_ID { get; set; }
        
    /// <summary>
    ///邮件标题:邮件标题
    /// </summary>
    public string EMAIL_SUBJECT { get; set; }
        
    /// <summary>
    ///邮件内容:邮件内容
    /// </summary>
    public string EMAIL_BODY { get; set; }
        
    /// <summary>
    ///收件人邮箱:收件人邮箱
    /// </summary>
    public string REC_EMAIL { get; set; }
        
    /// <summary>
    ///附件路径:附件路径 有多个附件时，用”;“隔开
    /// </summary>
    public string ATT_PATH { get; set; }
        
    /// <summary>
    ///优先级:优先级 0：低，1：正常，2：高
    /// </summary>
    public decimal PRIORITY_NUM { get; set; }
        
    /// <summary>
    ///邮件发送状态:邮件发送状态 0：待发送，1：已发送，2：发送失败
    /// </summary>
    public string EMAIL_SEND_STATUS { get; set; }
        
    /// <summary>
    ///备注:备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    
        public virtual T_DB_DB_EMAIL_M T_DB_DB_EMAIL_M { get; set; }
    }
}
