//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.DB
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///零件型号信息导入表
    /// </summary>
    public partial class T_DB_BU_PART_MODEL_IMP
    {
        
    /// <summary>
    ///零件型号信息导入ID
    /// </summary>
    public string PART_MODEL_IMP_ID { get; set; }
        
    /// <summary>
    ///车型系列号
    /// </summary>
    public string CAR_TYPE_SERIAL { get; set; }
        
    /// <summary>
    ///认证ID
    /// </summary>
    public string AUTHEN_ID { get; set; }
        
    /// <summary>
    ///导入值
    /// </summary>
    public string IMP_VAL { get; set; }
        
    /// <summary>
    ///导入类型 1 型号规格 2 CCC证书号
    /// </summary>
    public string IMP_TYPE { get; set; }
        
    /// <summary>
    ///用户ID
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
