//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.DB
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///物流公司表
    /// </summary>
    public partial class T_DB_DB_LOG_COMP
    {
        
    /// <summary>
    ///物流公司ID
    /// </summary>
    public string LOG_COMP_ID { get; set; }
        
    /// <summary>
    ///物流公司SAP编码
    /// </summary>
    public string SAP_LOG_COMP_CODE { get; set; }
        
    /// <summary>
    ///物流公司SCM编码
    /// </summary>
    public string SCM_LOG_COMP_CODE { get; set; }
        
    /// <summary>
    ///物流公司名称
    /// </summary>
    public string LOG_COMP_NAME { get; set; }
        
    /// <summary>
    ///物流公司类型;1-为厂外物流;2-为厂内物流;默认值:1
    /// </summary>
    public string LOG_COMP_TYPE { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
