//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.DB
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///工厂信息表
    /// </summary>
    public partial class T_DB_DB_FACTORY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_DB_DB_FACTORY()
        {
            this.T_DB_DB_FAC_LINK_MAN_INFO = new HashSet<T_DB_DB_FAC_LINK_MAN_INFO>();
            this.T_DB_DB_FAC_SEC = new HashSet<T_DB_DB_FAC_SEC>();
        }
    
        
    /// <summary>
    ///工厂ID
    /// </summary>
    public string FACTORY_ID { get; set; }
        
    /// <summary>
    ///系统工厂代码
    /// </summary>
    public string SYSTEM_FAC_CODE { get; set; }
        
    /// <summary>
    ///SAP工厂编码
    /// </summary>
    public string SAP_FACTORY_CODE { get; set; }
        
    /// <summary>
    ///物流工厂编码
    /// </summary>
    public string LOG_FAC_CODE { get; set; }
        
    /// <summary>
    ///工厂简称
    /// </summary>
    public string FACTORY_S_NAME { get; set; }
        
    /// <summary>
    ///工厂全称
    /// </summary>
    public string FACTORY_FULL_NAME { get; set; }
        
    /// <summary>
    ///纳税人识别号
    /// </summary>
    public string TAXPAYER_ID { get; set; }
        
    /// <summary>
    ///开户行
    /// </summary>
    public string ACCOUNT_BANK { get; set; }
        
    /// <summary>
    ///银行账号
    /// </summary>
    public string BANK_ACC { get; set; }
        
    /// <summary>
    ///财务电话
    /// </summary>
    public string FINAN_TEL { get; set; }
        
    /// <summary>
    ///发票备注
    /// </summary>
    public string INVOICE_REMARK { get; set; }
        
    /// <summary>
    ///成本中心编码
    /// </summary>
    public string COST_CENTER_CODE { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///工厂英文简称
    /// </summary>
    public string FACTORY_S_NAME_EN { get; set; }
        
    /// <summary>
    ///工厂类别
    /// </summary>
    public string FACTORY_CATE { get; set; }
        
    /// <summary>
    ///COP工厂编码
    /// </summary>
    public string COP_FAC_CODE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_DB_DB_FAC_LINK_MAN_INFO> T_DB_DB_FAC_LINK_MAN_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_DB_DB_FAC_SEC> T_DB_DB_FAC_SEC { get; set; }
    }
}
