//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///不合格品判定申请处理流程表
    /// </summary>
    public partial class T_BU_PQ_REJ_JG_APP_PRO
    {
        
    /// <summary>
    ///不合格品判定申请处理流程表ID
    /// </summary>
    public string REJ_JG_APP_PRO_ID { get; set; }
        
    /// <summary>
    ///不合格品单号
    /// </summary>
    public string REJ_BILL_CODE { get; set; }
        
    /// <summary>
    ///主凶件号
    /// </summary>
    public string PFP_CODE { get; set; }
        
    /// <summary>
    ///主凶件名称
    /// </summary>
    public string PFP_NAME { get; set; }
        
    /// <summary>
    ///供应商编码
    /// </summary>
    public string SUPPLIER_CODE { get; set; }
        
    /// <summary>
    ///是否索赔
    /// </summary>
    public string IS_INDEM { get; set; }
        
    /// <summary>
    ///是否有牵连件
    /// </summary>
    public string IS_U_PART { get; set; }
        
    /// <summary>
    ///数量(故障件数)
    /// </summary>
    public decimal FAULT_QTY { get; set; }
        
    /// <summary>
    ///制造车系代码
    /// </summary>
    public string MFGSERIES_CODE { get; set; }
        
    /// <summary>
    ///发生位置
    /// </summary>
    public string HAP_POS { get; set; }
        
    /// <summary>
    ///存放位置
    /// </summary>
    public string SAVE_POS { get; set; }
        
    /// <summary>
    ///补货位置
    /// </summary>
    public string RESTOCK_POS { get; set; }
        
    /// <summary>
    ///不良描述
    /// </summary>
    public string BAD_CAUSE { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string BAD_DESC { get; set; }
        
    /// <summary>
    ///捆包号
    /// </summary>
    public string BALE_CODE { get; set; }
        
    /// <summary>
    ///合同号
    /// </summary>
    public string CONTRACT_CODE { get; set; }
        
    /// <summary>
    ///完整包装数量
    /// </summary>
    public decimal FULL_PACK_QTY { get; set; }
        
    /// <summary>
    ///折合材料数量(半成品)
    /// </summary>
    public decimal MATE_QTY_SEMI { get; set; }
        
    /// <summary>
    ///半成品号
    /// </summary>
    public string SEMI_CODE { get; set; }
        
    /// <summary>
    ///半成品数
    /// </summary>
    public decimal SEMI_QTY { get; set; }
        
    /// <summary>
    ///折合材料数量(废成品)
    /// </summary>
    public decimal MATE_QTY_SCRAP { get; set; }
        
    /// <summary>
    ///废成品报废公斤
    /// </summary>
    public decimal SCRAP_KG { get; set; }
        
    /// <summary>
    ///物料单位
    /// </summary>
    public string MATERIAL_UNIT { get; set; }
        
    /// <summary>
    ///报废类型（0工废，1料废）
    /// </summary>
    public string SCRAP_TYPE { get; set; }
        
    /// <summary>
    ///不良类别代码
    /// </summary>
    public string BAD_TYPE_CODE { get; set; }
        
    /// <summary>
    ///零部件ng数量
    /// </summary>
    public decimal PART_NG_QTY { get; set; }
        
    /// <summary>
    ///是否批量
    /// </summary>
    public string IS_BATCH { get; set; }
        
    /// <summary>
    ///是否再发
    /// </summary>
    public string IS_RE_SEND { get; set; }
        
    /// <summary>
    ///是否停线
    /// </summary>
    public string IS_STOP_LINE { get; set; }
        
    /// <summary>
    ///是否PPM
    /// </summary>
    public string IS_PPM { get; set; }
        
    /// <summary>
    ///是否标识与实物不符
    /// </summary>
    public string IS_LOGO_NOT_MATCH { get; set; }
        
    /// <summary>
    ///系数
    /// </summary>
    public decimal COEF { get; set; }
        
    /// <summary>
    ///RanNO
    /// </summary>
    public string RAN_NO { get; set; }
        
    /// <summary>
    ///完整包装数量_ng数量
    /// </summary>
    public decimal COMP_PACK_QYT_NG { get; set; }
        
    /// <summary>
    ///折合材料数量(半成品)_ng数量
    /// </summary>
    public decimal MATE_QTY_SEMI_NG { get; set; }
        
    /// <summary>
    ///折合材料数量(废成品)_ng数量
    /// </summary>
    public decimal MATE_QTY_SCRAP_NG { get; set; }
        
    /// <summary>
    ///驳回原因
    /// </summary>
    public string REJ_REASON { get; set; }
        
    /// <summary>
    ///当前主流程环节（1已保存待申请；2已申请待判定；3已判定待回收；4已回收待确认；5回收已确认或者说已处理完成；7已拆单）
    /// </summary>
    public string CUR_MAIN_PRO { get; set; }
        
    /// <summary>
    ///当前补货环节（-1无需补货；1待补货；2已补货确认）
    /// </summary>
    public string CUR_RESTOCK_PRO { get; set; }
        
    /// <summary>
    ///当前状态（1正常；2被驳回；3驳回重新提交）
    /// </summary>
    public string CUR_STATUS { get; set; }
        
    /// <summary>
    ///申请类型（1零部件；2原材料）
    /// </summary>
    public string APP_TYPE { get; set; }
        
    /// <summary>
    ///申请日期
    /// </summary>
    public System.DateTime APP_DATE { get; set; }
        
    /// <summary>
    ///申请人（操作用户）
    /// </summary>
    public string APP_MAN { get; set; }
        
    /// <summary>
    ///判定日期
    /// </summary>
    public System.DateTime JUDGE_DATE { get; set; }
        
    /// <summary>
    ///判定人（操作用户）
    /// </summary>
    public string JUDGE_MAN { get; set; }
        
    /// <summary>
    ///补货人
    /// </summary>
    public string RESTOCK_MAN { get; set; }
        
    /// <summary>
    ///补货确认时间
    /// </summary>
    public System.DateTime RESTOCK_CONF_DATE { get; set; }
        
    /// <summary>
    ///补货确认人（操作用户）
    /// </summary>
    public string RESTOCK_CONF_MAN { get; set; }
        
    /// <summary>
    ///回收人（操作用户）
    /// </summary>
    public string RECY_MAN { get; set; }
        
    /// <summary>
    ///回收日期
    /// </summary>
    public System.DateTime RECY_DATE { get; set; }
        
    /// <summary>
    ///回收确认人（操作用户）
    /// </summary>
    public string RECY_CONF_MAN { get; set; }
        
    /// <summary>
    ///回收确认日期
    /// </summary>
    public System.DateTime RECY_CONF_DATE { get; set; }
        
    /// <summary>
    ///驳回人（操作用户）
    /// </summary>
    public string REJ_MAN { get; set; }
        
    /// <summary>
    ///申请单处理流水日志
    /// </summary>
    public string APP_DEAL_LOG { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///最后操作时间（用于历史表对应上）
    /// </summary>
    public System.DateTime LAST_OPT_TIME { get; set; }
        
    /// <summary>
    ///缺陷ID，多个ID以英文逗号,隔开（冗余字段）
    /// </summary>
    public string DEFECT_ID { get; set; }
        
    /// <summary>
    ///缺陷显示值（冗余字段）
    /// </summary>
    public string DEFECT_DIS_VAL { get; set; }
        
    /// <summary>
    ///缺陷责任单位，多个ID以英文逗号,隔开（冗余字段）PFP_SID值
    /// </summary>
    public string DEFECT_DUTY_UNIT { get; set; }
        
    /// <summary>
    ///回收备注信息
    /// </summary>
    public string REC_REMARK_INFO { get; set; }
        
    /// <summary>
    ///同步状态，0无需同步，1等待录入，2等待提交，3录入成功等待提交，4录入成功，5提交成功，-1录入失败，-2录入异常，-3提
    ///交失败，-4提交异常
    /// </summary>
    public string IS_HAVE_SAME { get; set; }
        
    /// <summary>
    ///最后一次驳回的时间
    /// </summary>
    public System.DateTime REJ_DATE { get; set; }
        
    /// <summary>
    ///所属工厂CODE
    /// </summary>
    public string BEL_FACT_CODE { get; set; }
        
    /// <summary>
    ///记录驳回的环节
    /// </summary>
    public string REJ_SEG { get; set; }
        
    /// <summary>
    ///记录原申请单号（来源于物流申请的单号）
    /// </summary>
    public string P_BILL_CODE { get; set; }
        
    /// <summary>
    ///1-仓库库位,包含同个QA区库位之间 2-新车试装 3-KIT线边 4-KIT二次物流 5-生产线 6-整车返修 7-费用申请
    /// </summary>
    public string TYPE_VAL { get; set; }
        
    /// <summary>
    ///ok品回流确认人
    /// </summary>
    public string OK_BACK_CONF_MAN { get; set; }
        
    /// <summary>
    ///ok品回流确认时间
    /// </summary>
    public System.DateTime OK_BACK_CONF_TIME { get; set; }
        
    /// <summary>
    ///ok品确认状态（-1无需确认ok数为0的情况，0未确认，1已确认）
    /// </summary>
    public string OK_CONF_STATUS { get; set; }
        
    /// <summary>
    ///ok品回流位置
    /// </summary>
    public string OK_BACK_POS { get; set; }
        
    /// <summary>
    ///直接父单号 分单，记录对应的父单号（直属父单号）
    /// </summary>
    public string DIRECTLY_P_BILL_CODE { get; set; }
        
    /// <summary>
    ///物流QA库位
    /// </summary>
    public string LOG_QA_POS { get; set; }
        
    /// <summary>
    ///物流班次
    /// </summary>
    public string LOG_CLASS_TIMES { get; set; }
    }
}
