//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///历史邮箱信息表
    /// </summary>
    public partial class T_BU_PQ_MAIL_INFO
    {
        
    /// <summary>
    ///MAIL_ID
    /// </summary>
    public string MAIL_ID { get; set; }
        
    /// <summary>
    ///用户ID
    /// </summary>
    public string EMP_ID { get; set; }
        
    /// <summary>
    ///用户名称
    /// </summary>
    public string USER_NAME { get; set; }
        
    /// <summary>
    ///用户邮箱
    /// </summary>
    public string USER_MAIL { get; set; }
    }
}
