//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///重保件信息临时查询表
    /// </summary>
    public partial class T_DB_DB_IP_INFO_CSR
    {
        
    /// <summary>
    ///表ID
    /// </summary>
    public string CSR_ID { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///零件号
    /// </summary>
    public string PRAT_NO { get; set; }
        
    /// <summary>
    ///零件名称
    /// </summary>
    public string PRAT_NAME { get; set; }
        
    /// <summary>
    ///重保件标识码
    /// </summary>
    public string IP_CODE { get; set; }
        
    /// <summary>
    ///供应商名称
    /// </summary>
    public string SUPPLIER_NAME { get; set; }
        
    /// <summary>
    ///下线日期
    /// </summary>
    public System.DateTime OFFLINE_DATE { get; set; }
        
    /// <summary>
    ///发动机号
    /// </summary>
    public string ENGINE_NO { get; set; }
        
    /// <summary>
    ///车型系列号
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///车型状态
    /// </summary>
    public string CAR_STATUS { get; set; }
        
    /// <summary>
    ///所有人
    /// </summary>
    public string ALL_NAME { get; set; }
        
    /// <summary>
    ///仓库名称
    /// </summary>
    public string CAR_HOUSE_NAME { get; set; }
        
    /// <summary>
    ///导入批次号
    /// </summary>
    public string BATCHNO { get; set; }
        
    /// <summary>
    ///错误信息
    /// </summary>
    public string COLUMN68 { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///序号
    /// </summary>
    public string XH_CODE { get; set; }
    }
}
