//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_DB_DB_EQUIP_TEMP
    /// </summary>
    public partial class T_DB_DB_EQUIP_TEMP
    {
        
    /// <summary>
    ///EQUIP_ID
    /// </summary>
    public string EQUIP_ID { get; set; }
        
    /// <summary>
    ///PRO_LINE_D_ID
    /// </summary>
    public string PRO_LINE_D_ID { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///PROCESS_CODE
    /// </summary>
    public string PROCESS_CODE { get; set; }
        
    /// <summary>
    ///EQUIP_CODE
    /// </summary>
    public string EQUIP_CODE { get; set; }
        
    /// <summary>
    ///SYS_MODULE
    /// </summary>
    public string SYS_MODULE { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP_ORG_ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///FACTORY_CODE
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///FACTORY_NAME
    /// </summary>
    public string FACTORY_NAME { get; set; }
    }
}
