//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_DB_DB_LOOKUP_VALUE_TEMP
    /// </summary>
    public partial class T_DB_DB_LOOKUP_VALUE_TEMP
    {
        
    /// <summary>
    ///LOOKUP_VALUE_ID
    /// </summary>
    public string LOOKUP_VALUE_ID { get; set; }
        
    /// <summary>
    ///LOOKUP_TYPE_ID
    /// </summary>
    public string LOOKUP_TYPE_ID { get; set; }
        
    /// <summary>
    ///LOOKUP_TYPE_CODE
    /// </summary>
    public string LOOKUP_TYPE_CODE { get; set; }
        
    /// <summary>
    ///LOOKUP_VALUE_CODE
    /// </summary>
    public string LOOKUP_VALUE_CODE { get; set; }
        
    /// <summary>
    ///LOOKUP_VALUE_NAME
    /// </summary>
    public string LOOKUP_VALUE_NAME { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///ATTRIBUTE1
    /// </summary>
    public string ATTRIBUTE1 { get; set; }
        
    /// <summary>
    ///ATTRIBUTE2
    /// </summary>
    public string ATTRIBUTE2 { get; set; }
        
    /// <summary>
    ///ATTRIBUTE3
    /// </summary>
    public string ATTRIBUTE3 { get; set; }
        
    /// <summary>
    ///ATTRIBUTE4
    /// </summary>
    public string ATTRIBUTE4 { get; set; }
        
    /// <summary>
    ///ATTRIBUTE5
    /// </summary>
    public string ATTRIBUTE5 { get; set; }
        
    /// <summary>
    ///REMARK
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///IS_SYSTEM
    /// </summary>
    public string IS_SYSTEM { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP_ORG_ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
