//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///工序与参数关系表
    /// </summary>
    public partial class T_PQ_DB_PROCESS_PARAM
    {
        
    /// <summary>
    ///工序与参数关系ID
    /// </summary>
    public string PROCESS_PARAM_ID { get; set; }
        
    /// <summary>
    ///工程
    /// </summary>
    public string ENGINEERING_TYPE { get; set; }
        
    /// <summary>
    ///部品类别
    /// </summary>
    public string PART_SORT { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///逻辑工序
    /// </summary>
    public string LOGIC_PROCESS { get; set; }
        
    /// <summary>
    ///测量字段名
    /// </summary>
    public string MEASURE_NAME { get; set; }
        
    /// <summary>
    ///对应表名
    /// </summary>
    public string TABLE_NAME { get; set; }
        
    /// <summary>
    ///是否装配 0.否 1.是
    /// </summary>
    public string IS_ASSEMBLY { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///测量字段编码
    /// </summary>
    public string MEASURE_CODE { get; set; }
        
    /// <summary>
    ///分组编码
    /// </summary>
    public string GROUP_CODE { get; set; }
    }
}
