//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///不合格品单零件信息表
    /// </summary>
    public partial class T_PQ_BU_REJ_BILL_PART
    {
        
    /// <summary>
    ///不合格品单零件信息表ID
    /// </summary>
    public string REJ_BILL_PART_ID { get; set; }
        
    /// <summary>
    ///零件编码
    /// </summary>
    public string PART_NO { get; set; }
        
    /// <summary>
    ///零件名称
    /// </summary>
    public string PART_NAME { get; set; }
        
    /// <summary>
    ///零件数量
    /// </summary>
    public decimal PART_QTY { get; set; }
        
    /// <summary>
    ///零件价格
    /// </summary>
    public decimal PART_PRICE { get; set; }
        
    /// <summary>
    ///物流单价
    /// </summary>
    public decimal LOG_UNIT_PRICE { get; set; }
        
    /// <summary>
    ///零件金额合计
    /// </summary>
    public decimal PART_AMT_TOT { get; set; }
        
    /// <summary>
    ///是否主凶件
    /// </summary>
    public string IS_PFP { get; set; }
        
    /// <summary>
    ///是否索赔主凶件
    /// </summary>
    public string IS_INDEM_PFP { get; set; }
        
    /// <summary>
    ///供应商编码
    /// </summary>
    public string SUPPLIER_CODE { get; set; }
        
    /// <summary>
    ///发票号
    /// </summary>
    public string INVOICE_CODE { get; set; }
        
    /// <summary>
    ///RANNO
    /// </summary>
    public string RAN_NO { get; set; }
        
    /// <summary>
    ///关税金额
    /// </summary>
    public decimal TARIFF_AMT { get; set; }
        
    /// <summary>
    ///物流费
    /// </summary>
    public decimal LOG_FEE { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///物流零件单价
    /// </summary>
    public decimal LOG_PART_PRICE { get; set; }
        
    /// <summary>
    ///PIR单号
    /// </summary>
    public string PIR_ORDER_CODE { get; set; }
    
        public virtual T_PQ_BU_REJ_BILL T_PQ_BU_REJ_BILL { get; set; }
    }
}
