//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///门关闭力测定数据表
    /// </summary>
    public partial class T_PQ_BU_DOOR_CLOSE_MEAS
    {
        
    /// <summary>
    ///门关闭力测定数据ID
    /// </summary>
    public string DOOR_CLOSE_MEAS_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///CCR编号
    /// </summary>
    public string CCR_CODE { get; set; }
        
    /// <summary>
    ///测量日期
    /// </summary>
    public System.DateTime MEASURE_DATE { get; set; }
        
    /// <summary>
    ///测量人
    /// </summary>
    public string MEASURE_MAN { get; set; }
        
    /// <summary>
    ///测量设备型号
    /// </summary>
    public string MEASURE_EQUIP_CODE { get; set; }
        
    /// <summary>
    ///FR--LH全开能量
    /// </summary>
    public decimal FR_LH_FULL_ENERGY { get; set; }
        
    /// <summary>
    ///FR--LH全开速度
    /// </summary>
    public decimal FR_LH_FULL_SPEED { get; set; }
        
    /// <summary>
    ///FR--LH半开能量
    /// </summary>
    public decimal FR_LH_HALF_ENERGY { get; set; }
        
    /// <summary>
    ///FR--LH半开速度
    /// </summary>
    public decimal FR_LH_HALF_SPEED { get; set; }
        
    /// <summary>
    ///FR--RH全开能量
    /// </summary>
    public decimal FR_RH_FULL_ENERGY { get; set; }
        
    /// <summary>
    ///FR--RH全开速度
    /// </summary>
    public decimal FR_RH_FULL_SPEED { get; set; }
        
    /// <summary>
    ///FR--RH半开能量
    /// </summary>
    public decimal FR_RH_HALF_ENERGY { get; set; }
        
    /// <summary>
    ///FR--RH半开速度
    /// </summary>
    public decimal FR_RH_HALF_SPEED { get; set; }
        
    /// <summary>
    ///RR--LH全开能量
    /// </summary>
    public decimal RR_LH_FULL_ENERGY { get; set; }
        
    /// <summary>
    ///RR--LH全开速度
    /// </summary>
    public decimal RR_LH_FULL_SPEED { get; set; }
        
    /// <summary>
    ///RR--LH半开能量
    /// </summary>
    public decimal RR_LH_HALF_ENERGY { get; set; }
        
    /// <summary>
    ///RR--LH半开速度
    /// </summary>
    public decimal RR_LH_HALF_SPEED { get; set; }
        
    /// <summary>
    ///RR--RH全开能量
    /// </summary>
    public decimal RR_RH_FULL_ENERGY { get; set; }
        
    /// <summary>
    ///RR--RH全开速度
    /// </summary>
    public decimal RR_RH_FULL_SPEED { get; set; }
        
    /// <summary>
    ///RR--RH半开能量
    /// </summary>
    public decimal RR_RH_HALF_ENERGY { get; set; }
        
    /// <summary>
    ///RR--RH半开速度
    /// </summary>
    public decimal RR_RH_HALF_SPEED { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
