//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///RFID点位过车信息
    /// </summary>
    public partial class T_PQ_BU_FX_RFID_CAR_PAS
    {
        
    /// <summary>
    ///RFID点位过车实绩ID
    /// </summary>
    public string RFID_CAR_PAS_ID { get; set; }
        
    /// <summary>
    ///数据状态：0:未解析1:解析中2:解析成功3:解析失败
    /// </summary>
    public string DATA_STATE { get; set; }
        
    /// <summary>
    ///解析失败原因
    /// </summary>
    public string DATA_RESULT { get; set; }
        
    /// <summary>
    ///VIN
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///过车点位
    /// </summary>
    public string PROCESS_ID { get; set; }
        
    /// <summary>
    ///过车时间
    /// </summary>
    public string PASS_DATE { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string PLANT_CODE { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///默认为系统时间；
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///默认为系统时间；
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///反馈结果状态：0-为反馈，1-已反馈，默认值为0
    /// </summary>
    public string RE_STATUS { get; set; }
    }
}
