//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///不合格品责任变更信息表
    /// </summary>
    public partial class T_PQ_BU_REJ_DUTY_CHAN
    {
        
    /// <summary>
    ///不合格品责任变更信息表ID
    /// </summary>
    public string REJ_DUTY_CHAN_ID { get; set; }
        
    /// <summary>
    ///不合格品责任变更单号
    /// </summary>
    public string REJ_DUTY_CHAN_CODE { get; set; }
        
    /// <summary>
    ///申诉日期
    /// </summary>
    public System.DateTime APPEAL_DATE { get; set; }
        
    /// <summary>
    ///申诉单位
    /// </summary>
    public string APPEAL_UNIT { get; set; }
        
    /// <summary>
    ///申诉责任人
    /// </summary>
    public string APPEAL_DUTY_MAN { get; set; }
        
    /// <summary>
    ///申诉单位科长
    /// </summary>
    public string APPEAL_DUTY_UNIT_SC { get; set; }
        
    /// <summary>
    ///申诉单位科长审核日期
    /// </summary>
    public System.DateTime APPEAL_DUTY_UNIT_SC_DATE { get; set; }
        
    /// <summary>
    ///申诉单位变更原因说明
    /// </summary>
    public string CHAN_CAUSE_DESC { get; set; }
        
    /// <summary>
    ///审核单位主担工程师确认人
    /// </summary>
    public string MAIN_ENGI_CONF_MAN { get; set; }
        
    /// <summary>
    ///审核单位主担工程师确认日期
    /// </summary>
    public System.DateTime MAIN_ENGI_CONF_DATE { get; set; }
        
    /// <summary>
    ///审核单位主担工程师驳回原因
    /// </summary>
    public string MAIN_ENGI_REJ_CAUSE { get; set; }
        
    /// <summary>
    ///审核单位确认意见
    /// </summary>
    public string AUD_UNIT_CONF_OPI { get; set; }
        
    /// <summary>
    ///审核单位科长
    /// </summary>
    public string AUD_UNIT_SC { get; set; }
        
    /// <summary>
    ///审核单位科长审核日期
    /// </summary>
    public System.DateTime AUD_UNIT_SC_DATE { get; set; }
        
    /// <summary>
    ///审核单位科长驳回原因
    /// </summary>
    public string AUD_UNIT_SC_REJ_CAUSE { get; set; }
        
    /// <summary>
    ///审核单位部长
    /// </summary>
    public string AUD_UNIT_MINI { get; set; }
        
    /// <summary>
    ///审核单位部长批准日期
    /// </summary>
    public System.DateTime AUD_UNIT_MINI_DATE { get; set; }
        
    /// <summary>
    ///审核单位部长批准意见
    /// </summary>
    public string AUD_UNIT_MINI_OPI { get; set; }
        
    /// <summary>
    ///审核单位部长驳回原因
    /// </summary>
    public string AUD_UNIT_MINI_REJ_CAUSE { get; set; }
        
    /// <summary>
    ///责任变更申诉状态,值列表DUTY_CHAN_PRO_TYPE
    /// </summary>
    public string STATUS { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///建议变更单位
    /// </summary>
    public string SUG_CHAN_UNIT { get; set; }
        
    /// <summary>
    ///确认变更单位
    /// </summary>
    public string CONF_CHAN_UNIT { get; set; }
        
    /// <summary>
    ///文件名
    /// </summary>
    public string FILE_NAME { get; set; }
        
    /// <summary>
    ///文件路径
    /// </summary>
    public string FILE_PATH { get; set; }
        
    /// <summary>
    ///申请建议科室确认人
    /// </summary>
    public string MAIN_ENGI_SUG_MAN { get; set; }
        
    /// <summary>
    ///申请建议科室确认日期
    /// </summary>
    public System.DateTime MAIN_ENGI_SUG_DATE { get; set; }
    }
}
