//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///生产Q班问题数据表
    /// </summary>
    public partial class T_PQ_BU_PROD_Q_QUES
    {
        
    /// <summary>
    ///生产Q班问题数据表ID
    /// </summary>
    public string PROD_Q_QUES_ID { get; set; }
        
    /// <summary>
    ///发生日期
    /// </summary>
    public System.DateTime HAP_DATE { get; set; }
        
    /// <summary>
    ///品情来源（lookup_value_code）
    /// </summary>
    public string SOURCE_DEPT { get; set; }
        
    /// <summary>
    ///车型（lookup_value_code）
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///车号
    /// </summary>
    public string CAR_NO { get; set; }
        
    /// <summary>
    ///不良区分 （lookup_value_code）
    /// </summary>
    public string BAD_DIST { get; set; }
        
    /// <summary>
    ///不良件数
    /// </summary>
    public decimal BAD_QTY { get; set; }
        
    /// <summary>
    ///问题点
    /// </summary>
    public string QUES_POINT { get; set; }
        
    /// <summary>
    ///录入人（user_name）
    /// </summary>
    public string ENTERING_MAN { get; set; }
        
    /// <summary>
    ///录入时间
    /// </summary>
    public System.DateTime OPER_DATE { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///工厂编码（FACTORY_CODE）
    /// </summary>
    public string FACTORY_CODE { get; set; }
    }
}
