//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///预警处理单
    /// </summary>
    public partial class T_PQ_BU_WARNING_DEAL
    {
        
    /// <summary>
    ///预警处理单ID
    /// </summary>
    public string WARNING_DEAL_ID { get; set; }
        
    /// <summary>
    ///预警类型
    /// </summary>
    public string WARNING_TYPE { get; set; }
        
    /// <summary>
    ///通知单编号
    /// </summary>
    public string NOTICE_CODE { get; set; }
        
    /// <summary>
    ///预警项目编码
    /// </summary>
    public string WARNING_ITEM_CODE { get; set; }
        
    /// <summary>
    ///发生数量
    /// </summary>
    public int HAPPEN_QTY { get; set; }
        
    /// <summary>
    ///发起人
    /// </summary>
    public string SPONSOR_MAN { get; set; }
        
    /// <summary>
    ///发起时间
    /// </summary>
    public System.DateTime SPONSOR_DATE { get; set; }
        
    /// <summary>
    ///处理人
    /// </summary>
    public string DEAL_PERSON { get; set; }
        
    /// <summary>
    ///处理内容
    /// </summary>
    public string DEAL_FUNC { get; set; }
        
    /// <summary>
    ///处理时间
    /// </summary>
    public System.DateTime HANDLED_TIME { get; set; }
        
    /// <summary>
    ///确认人
    /// </summary>
    public string CONFIRM_MAN { get; set; }
        
    /// <summary>
    ///确认时间
    /// </summary>
    public System.DateTime CONFIRM_DATE { get; set; }
        
    /// <summary>
    ///确认意见
    /// </summary>
    public string CONFIRM_OPINION { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
