//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///发动机不良履历表
    /// </summary>
    public partial class T_PQ_BU_ENGINE_BAD_CV
    {
        
    /// <summary>
    ///发动机不良履历ID
    /// </summary>
    public string ENGINE_BAD_CV_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///发动机号
    /// </summary>
    public string ENGINE_NO { get; set; }
        
    /// <summary>
    ///发动机状态
    /// </summary>
    public string ENGINE_STATUS { get; set; }
        
    /// <summary>
    ///变更时间
    /// </summary>
    public System.DateTime CHANGE_DATE { get; set; }
        
    /// <summary>
    ///责任部门
    /// </summary>
    public string DUTY_DEPT { get; set; }
        
    /// <summary>
    ///不良大类
    /// </summary>
    public string BAD_BIG_TYPE { get; set; }
        
    /// <summary>
    ///不良类型
    /// </summary>
    public string BAD_TYPE { get; set; }
        
    /// <summary>
    ///变更人
    /// </summary>
    public string CHANGE_MAN { get; set; }
        
    /// <summary>
    ///变更备注
    /// </summary>
    public string CHANGE_REMARK { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///工厂名称
    /// </summary>
    public string FACTORY_NAME { get; set; }
    }
}
