//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///申诉单信息表
    /// </summary>
    public partial class T_PQ_BU_APPEAL_ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PQ_BU_APPEAL_ORDER()
        {
            this.T_PQ_BU_APPEAL_TYPE = new HashSet<T_PQ_BU_APPEAL_TYPE>();
            this.T_PQ_BU_ARBITRATION_TYPE = new HashSet<T_PQ_BU_ARBITRATION_TYPE>();
        }
    
        
    /// <summary>
    ///申诉单ID
    /// </summary>
    public string APPEAL_ORDER_ID { get; set; }
        
    /// <summary>
    ///申诉单号
    /// </summary>
    public string APPEAL_ORDER_CODE { get; set; }
        
    /// <summary>
    ///索赔月
    /// </summary>
    public string CLAIM_MON { get; set; }
        
    /// <summary>
    ///申诉单位编号
    /// </summary>
    public string APPEAL_COMP_CODE { get; set; }
        
    /// <summary>
    ///申诉单据数
    /// </summary>
    public int APPEAL_BILL_NUM { get; set; }
        
    /// <summary>
    ///申诉日期
    /// </summary>
    public System.DateTime APPEAL_DATE { get; set; }
        
    /// <summary>
    ///申诉人ID
    /// </summary>
    public string APPEAL_MAN_ID { get; set; }
        
    /// <summary>
    ///申诉单状态
    /// </summary>
    public string APPEAL_BILL_STATUS { get; set; }
        
    /// <summary>
    ///格式审核日期
    /// </summary>
    public System.DateTime FORMAT_AUDIT_DATE { get; set; }
        
    /// <summary>
    ///仲裁日期
    /// </summary>
    public System.DateTime ARBITRATION_DATE { get; set; }
        
    /// <summary>
    ///设定比例日期
    /// </summary>
    public System.DateTime SET_RATE_DATE { get; set; }
        
    /// <summary>
    ///审核日期
    /// </summary>
    public System.DateTime AUDIT_DATE { get; set; }
        
    /// <summary>
    ///批准日期
    /// </summary>
    public System.DateTime APPROVE_DATE { get; set; }
        
    /// <summary>
    ///驳回意见
    /// </summary>
    public string REJ_OPINION { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///SAP工厂编码
    /// </summary>
    public string SAP_FACTORY_CODE { get; set; }
        
    /// <summary>
    ///仲裁驳回意见
    /// </summary>
    public string ARBITRATION_REJ_OPINION { get; set; }
        
    /// <summary>
    ///设定比例驳回意见
    /// </summary>
    public string SET_RATE_REJ_OPINION { get; set; }
        
    /// <summary>
    ///审核驳回意见
    /// </summary>
    public string AUDIT_REJ_OPINION { get; set; }
        
    /// <summary>
    ///批准驳回意见
    /// </summary>
    public string APPROVE_REJ_OPINION { get; set; }
        
    /// <summary>
    ///格式审核人
    /// </summary>
    public string FORMAT_AUDITOR { get; set; }
        
    /// <summary>
    ///仲裁人
    /// </summary>
    public string ARBITRATER { get; set; }
        
    /// <summary>
    ///设定比例人
    /// </summary>
    public string SET_RATER { get; set; }
        
    /// <summary>
    ///审核人
    /// </summary>
    public string AUDITOR { get; set; }
        
    /// <summary>
    ///批准人
    /// </summary>
    public string APPROVER { get; set; }
        
    /// <summary>
    ///是否为物流申诉单
    /// </summary>
    public string IS_LOG_APPEAL_ORDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_APPEAL_TYPE> T_PQ_BU_APPEAL_TYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_ARBITRATION_TYPE> T_PQ_BU_ARBITRATION_TYPE { get; set; }
    }
}
