//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///基础数据_色差规格表
    /// </summary>
    public partial class T_PQ_DB_BA_COLOR_DIFF_SPEC
    {
        
    /// <summary>
    ///色差规格ID
    /// </summary>
    public string BA_COLOR_DIFF_SPEC_ID { get; set; }
        
    /// <summary>
    ///颜色
    /// </summary>
    public string CAR_COLOR { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///评价类型 枚举:1;仪器;2目视
    /// </summary>
    public string EVAL_TYPE { get; set; }
        
    /// <summary>
    ///项目大类 枚举:1:明度:2:黄相；3:红相
    /// </summary>
    public string PROJ_BIG_TYPE { get; set; }
        
    /// <summary>
    ///项目小类 枚举:1:正面；2:反面
    /// </summary>
    public string PROJ_SMALL_TYPE { get; set; }
        
    /// <summary>
    ///上限值
    /// </summary>
    public decimal MAX_VALUE { get; set; }
        
    /// <summary>
    ///下限值
    /// </summary>
    public decimal L_BOUND_VAL { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
