//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///曲轴工序测量表
    /// </summary>
    public partial class T_PQ_BU_CS_P_MEAS
    {
        
    /// <summary>
    ///曲轴工序测量ID
    /// </summary>
    public string CS_P_MEAS_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///部品类别
    /// </summary>
    public string PART_SORT { get; set; }
        
    /// <summary>
    ///部品二维码
    /// </summary>
    public string PART_2D_CODE { get; set; }
        
    /// <summary>
    ///搬入时间
    /// </summary>
    public System.DateTime MOVE_IN_TIME { get; set; }
        
    /// <summary>
    ///搬出时间
    /// </summary>
    public System.DateTime MOVE_OUT_TIME { get; set; }
        
    /// <summary>
    ///连杆颈加热开始时间
    /// </summary>
    public System.DateTime CONN_ROD_HEAT_TIME { get; set; }
        
    /// <summary>
    ///法兰轴颈加热开始时间
    /// </summary>
    public System.DateTime FLANGE_HEAT_TIME { get; set; }
        
    /// <summary>
    ///主轴颈加热开始时间
    /// </summary>
    public System.DateTime SPINDLE_HEAT_TIME { get; set; }
        
    /// <summary>
    ///Diameter M1_Pos1
    /// </summary>
    public decimal DIAMETER_M1_POS1 { get; set; }
        
    /// <summary>
    ///Diameter M1_Pos2
    /// </summary>
    public decimal DIAMETER_M1_POS2 { get; set; }
        
    /// <summary>
    ///Diameter M1_Pos3
    /// </summary>
    public decimal DIAMETER_M1_POS3 { get; set; }
        
    /// <summary>
    ///Roundness  M1_Pos1
    /// </summary>
    public decimal ROUNDNESS_M1_POS1 { get; set; }
        
    /// <summary>
    ///Roundness  M1_Pos2
    /// </summary>
    public decimal ROUNDNESS_M1_POS2 { get; set; }
        
    /// <summary>
    ///Roundness  M1_Pos3
    /// </summary>
    public decimal ROUNDNESS_M1_POS3 { get; set; }
        
    /// <summary>
    ///Straightness  M1
    /// </summary>
    public decimal STRAIGHTNESS_M1 { get; set; }
        
    /// <summary>
    ///Taper M1
    /// </summary>
    public decimal TAPER_M1 { get; set; }
        
    /// <summary>
    ///Diameter M2_Pos1
    /// </summary>
    public decimal DIAMETER_M2_POS1 { get; set; }
        
    /// <summary>
    ///Diameter M2_Pos2
    /// </summary>
    public decimal DIAMETER_M2_POS2 { get; set; }
        
    /// <summary>
    ///Diameter M2_Pos3
    /// </summary>
    public decimal DIAMETER_M2_POS3 { get; set; }
        
    /// <summary>
    ///Roundness  M2_Pos1
    /// </summary>
    public decimal ROUNDNESS_M2_POS1 { get; set; }
        
    /// <summary>
    ///Roundness  M2_Pos2
    /// </summary>
    public decimal ROUNDNESS_M2_POS2 { get; set; }
        
    /// <summary>
    ///Roundness  M2_Pos3
    /// </summary>
    public decimal ROUNDNESS_M2_POS3 { get; set; }
        
    /// <summary>
    ///Straightness  M2
    /// </summary>
    public decimal STRAIGHTNESS_M2 { get; set; }
        
    /// <summary>
    ///Taper M2
    /// </summary>
    public decimal TAPER_M2 { get; set; }
        
    /// <summary>
    ///Diameter M3_Pos1
    /// </summary>
    public decimal DIAMETER_M3_POS1 { get; set; }
        
    /// <summary>
    ///Diameter M3_Pos2
    /// </summary>
    public decimal DIAMETER_M3_POS2 { get; set; }
        
    /// <summary>
    ///Diameter M3_Pos3
    /// </summary>
    public decimal DIAMETER_M3_POS3 { get; set; }
        
    /// <summary>
    ///Roundness  M3_Pos1
    /// </summary>
    public decimal ROUNDNESS_M3_POS1 { get; set; }
        
    /// <summary>
    ///Roundness  M3_Pos2
    /// </summary>
    public decimal ROUNDNESS_M3_POS2 { get; set; }
        
    /// <summary>
    ///Roundness  M3_Pos3
    /// </summary>
    public decimal ROUNDNESS_M3_POS3 { get; set; }
        
    /// <summary>
    ///Straightness  M3
    /// </summary>
    public decimal STRAIGHTNESS_M3 { get; set; }
        
    /// <summary>
    ///Taper M3
    /// </summary>
    public decimal TAPER_M3 { get; set; }
        
    /// <summary>
    ///Runout M3
    /// </summary>
    public decimal RUNOUT_M3 { get; set; }
        
    /// <summary>
    ///Diameter M4_Pos1
    /// </summary>
    public decimal DIAMETER_M4_POS1 { get; set; }
        
    /// <summary>
    ///Diameter M4_Pos2
    /// </summary>
    public decimal DIAMETER_M4_POS2 { get; set; }
        
    /// <summary>
    ///Diameter M4_Pos3
    /// </summary>
    public decimal DIAMETER_M4_POS3 { get; set; }
        
    /// <summary>
    ///Roundness  M4_Pos1
    /// </summary>
    public decimal ROUNDNESS_M4_POS1 { get; set; }
        
    /// <summary>
    ///Roundness  M4_Pos2
    /// </summary>
    public decimal ROUNDNESS_M4_POS2 { get; set; }
        
    /// <summary>
    ///Roundness  M4_Pos3
    /// </summary>
    public decimal ROUNDNESS_M4_POS3 { get; set; }
        
    /// <summary>
    ///Straightness  M4
    /// </summary>
    public decimal STRAIGHTNESS_M4 { get; set; }
        
    /// <summary>
    ///Taper M4
    /// </summary>
    public decimal TAPER_M4 { get; set; }
        
    /// <summary>
    ///Diameter M5_Pos1
    /// </summary>
    public decimal DIAMETER_M5_POS1 { get; set; }
        
    /// <summary>
    ///Diameter M5_Pos2
    /// </summary>
    public decimal DIAMETER_M5_POS2 { get; set; }
        
    /// <summary>
    ///Diameter M5_Pos3
    /// </summary>
    public decimal DIAMETER_M5_POS3 { get; set; }
        
    /// <summary>
    ///Roundness  M5_Pos1
    /// </summary>
    public decimal ROUNDNESS_M5_POS1 { get; set; }
        
    /// <summary>
    ///Roundness  M5_Pos2
    /// </summary>
    public decimal ROUNDNESS_M5_POS2 { get; set; }
        
    /// <summary>
    ///Roundness  M5_Pos3
    /// </summary>
    public decimal ROUNDNESS_M5_POS3 { get; set; }
        
    /// <summary>
    ///Straightness  M5
    /// </summary>
    public decimal STRAIGHTNESS_M5 { get; set; }
        
    /// <summary>
    ///Taper M5
    /// </summary>
    public decimal TAPER_M5 { get; set; }
        
    /// <summary>
    ///Diameter P1_Pos1
    /// </summary>
    public decimal DIAMETER_P1_POS1 { get; set; }
        
    /// <summary>
    ///Diameter P1_Pos2
    /// </summary>
    public decimal DIAMETER_P1_POS2 { get; set; }
        
    /// <summary>
    ///Diameter P1_Pos3
    /// </summary>
    public decimal DIAMETER_P1_POS3 { get; set; }
        
    /// <summary>
    ///Roundness  P1_Pos1
    /// </summary>
    public decimal ROUNDNESS_P1_POS1 { get; set; }
        
    /// <summary>
    ///Roundness  P1_Pos2
    /// </summary>
    public decimal ROUNDNESS_P1_POS2 { get; set; }
        
    /// <summary>
    ///Roundness  P1_Pos3
    /// </summary>
    public decimal ROUNDNESS_P1_POS3 { get; set; }
        
    /// <summary>
    ///Straightness  P1
    /// </summary>
    public decimal STRAIGHTNESS_P1 { get; set; }
        
    /// <summary>
    ///Taper P1
    /// </summary>
    public decimal TAPER_P1 { get; set; }
        
    /// <summary>
    ///Paral. P1 to M1_M5
    /// </summary>
    public decimal PARAL_P1_TO_M1_M5 { get; set; }
        
    /// <summary>
    ///Diameter P2_Pos1
    /// </summary>
    public decimal DIAMETER_P2_POS1 { get; set; }
        
    /// <summary>
    ///Diameter P2_Pos2
    /// </summary>
    public decimal DIAMETER_P2_POS2 { get; set; }
        
    /// <summary>
    ///Diameter P2_Pos3
    /// </summary>
    public decimal DIAMETER_P2_POS3 { get; set; }
        
    /// <summary>
    ///Roundness  P2_Pos1
    /// </summary>
    public decimal ROUNDNESS_P2_POS1 { get; set; }
        
    /// <summary>
    ///Roundness  P2_Pos2
    /// </summary>
    public decimal ROUNDNESS_P2_POS2 { get; set; }
        
    /// <summary>
    ///Roundness  P2_Pos3
    /// </summary>
    public decimal ROUNDNESS_P2_POS3 { get; set; }
        
    /// <summary>
    ///Straightness  P2
    /// </summary>
    public decimal STRAIGHTNESS_P2 { get; set; }
        
    /// <summary>
    ///Taper P2
    /// </summary>
    public decimal TAPER_P2 { get; set; }
        
    /// <summary>
    ///Paral. P2 to M1_M5
    /// </summary>
    public decimal PARAL_P2_TO_M1_M5 { get; set; }
        
    /// <summary>
    ///Diameter P3_Pos1
    /// </summary>
    public decimal DIAMETER_P3_POS1 { get; set; }
        
    /// <summary>
    ///Diameter P3_Pos2
    /// </summary>
    public decimal DIAMETER_P3_POS2 { get; set; }
        
    /// <summary>
    ///Diameter P3_Pos3
    /// </summary>
    public decimal DIAMETER_P3_POS3 { get; set; }
        
    /// <summary>
    ///Roundness  P3_Pos1
    /// </summary>
    public decimal ROUNDNESS_P3_POS1 { get; set; }
        
    /// <summary>
    ///Roundness  P3_Pos2
    /// </summary>
    public decimal ROUNDNESS_P3_POS2 { get; set; }
        
    /// <summary>
    ///Roundness  P3_Pos3
    /// </summary>
    public decimal ROUNDNESS_P3_POS3 { get; set; }
        
    /// <summary>
    ///Straightness  P3
    /// </summary>
    public decimal STRAIGHTNESS_P3 { get; set; }
        
    /// <summary>
    ///Taper P3
    /// </summary>
    public decimal TAPER_P3 { get; set; }
        
    /// <summary>
    ///Paral. P3 to M1_M5
    /// </summary>
    public decimal PARAL_P3_TO_M1_M5 { get; set; }
        
    /// <summary>
    ///Diameter P4_Pos1
    /// </summary>
    public decimal DIAMETER_P4_POS1 { get; set; }
        
    /// <summary>
    ///Diameter P4_Pos2
    /// </summary>
    public decimal DIAMETER_P4_POS2 { get; set; }
        
    /// <summary>
    ///Diameter P4_Pos3
    /// </summary>
    public decimal DIAMETER_P4_POS3 { get; set; }
        
    /// <summary>
    ///Roundness  P4_Pos1
    /// </summary>
    public decimal ROUNDNESS_P4_POS1 { get; set; }
        
    /// <summary>
    ///Roundness  P4_Pos2
    /// </summary>
    public decimal ROUNDNESS_P4_POS2 { get; set; }
        
    /// <summary>
    ///Roundness  P4_Pos3
    /// </summary>
    public decimal ROUNDNESS_P4_POS3 { get; set; }
        
    /// <summary>
    ///Straightness  P4
    /// </summary>
    public decimal STRAIGHTNESS_P4 { get; set; }
        
    /// <summary>
    ///Taper P4
    /// </summary>
    public decimal TAPER_P4 { get; set; }
        
    /// <summary>
    ///Paral. P4 to M1_M5
    /// </summary>
    public decimal PARAL_P4_TO_M1_M5 { get; set; }
        
    /// <summary>
    ///Diameter Flange
    /// </summary>
    public decimal DIAMETER_FLANGE { get; set; }
        
    /// <summary>
    ///M1 Dia. Class
    /// </summary>
    public decimal M1_DIA_CLASS { get; set; }
        
    /// <summary>
    ///M2 Dia. Class
    /// </summary>
    public decimal M2_DIA_CLASS { get; set; }
        
    /// <summary>
    ///M3 Dia. Class
    /// </summary>
    public decimal M3_DIA_CLASS { get; set; }
        
    /// <summary>
    ///M4 Dia. Class
    /// </summary>
    public decimal M4_DIA_CLASS { get; set; }
        
    /// <summary>
    ///M5 Dia. Class
    /// </summary>
    public decimal M5_DIA_CLASS { get; set; }
        
    /// <summary>
    ///P1 Dia. Class
    /// </summary>
    public decimal P1_DIA_CLASS { get; set; }
        
    /// <summary>
    ///P2 Dia. Class
    /// </summary>
    public decimal P2_DIA_CLASS { get; set; }
        
    /// <summary>
    ///P3 Dia. Class
    /// </summary>
    public decimal P3_DIA_CLASS { get; set; }
        
    /// <summary>
    ///P4 Dia. Class
    /// </summary>
    public decimal P4_DIA_CLASS { get; set; }
        
    /// <summary>
    ///Runout M2
    /// </summary>
    public decimal RUNOUT_M2 { get; set; }
        
    /// <summary>
    ///Runout M4
    /// </summary>
    public decimal RUNOUT_M4 { get; set; }
        
    /// <summary>
    ///Runout M1
    /// </summary>
    public decimal RUNOUT_M1 { get; set; }
        
    /// <summary>
    ///Runout M5
    /// </summary>
    public decimal RUNOUT_M5 { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///机种
    /// </summary>
    public string MAC_TYPE { get; set; }
        
    /// <summary>
    ///工厂名称
    /// </summary>
    public string FACTORY_NAME { get; set; }
        
    /// <summary>
    ///工序编码
    /// </summary>
    public string PROCESS_CODE { get; set; }
        
    /// <summary>
    ///逻辑工序
    /// </summary>
    public string LOGIC_PROCESS { get; set; }
        
    /// <summary>
    ///Dia. of Journal A1直径
    /// </summary>
    public decimal DIA_OF_JOURNAL_A1 { get; set; }
        
    /// <summary>
    ///Dia. of Journal A2直径
    /// </summary>
    public decimal DIA_OF_JOURNAL_A2 { get; set; }
        
    /// <summary>
    ///Width of Keyway宽度
    /// </summary>
    public decimal WIDTH_OF_KEYWAY { get; set; }
        
    /// <summary>
    ///装箱lot条形码
    /// </summary>
    public string PACK_LOT_BAR_CODE { get; set; }
        
    /// <summary>
    ///连杆颈加热结束时间
    /// </summary>
    public System.DateTime CONN_ROD_HEAT_TIME_E { get; set; }
        
    /// <summary>
    ///法兰轴颈加热结束时间
    /// </summary>
    public System.DateTime FLANGE_HEAT_TIME_E { get; set; }
        
    /// <summary>
    ///主轴颈加热结束时间
    /// </summary>
    public System.DateTime SPINDLE_HEAT_TIME_E { get; set; }
    
        public virtual T_PQ_BU_PART_PROCESS T_PQ_BU_PART_PROCESS { get; set; }
    }
}
