//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///车辆跑偏测量数据表
    /// </summary>
    public partial class T_PQ_BU_V_RUN_DEVI_MEAS
    {
        
    /// <summary>
    ///车辆跑偏测量数据ID
    /// </summary>
    public string V_RUN_DEVI_MEAS_ID { get; set; }
        
    /// <summary>
    ///测量时间
    /// </summary>
    public System.DateTime MEASURE_DATE { get; set; }
        
    /// <summary>
    ///测量人
    /// </summary>
    public string MEASURE_MAN { get; set; }
        
    /// <summary>
    ///设备编码
    /// </summary>
    public string EQUIP_CODE { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///车间编码
    /// </summary>
    public string WORKSHOP_CODE { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///CCR编号
    /// </summary>
    public string CCR_CODE { get; set; }
        
    /// <summary>
    ///GPS时间
    /// </summary>
    public string GPS_TIME { get; set; }
        
    /// <summary>
    ///GPS日期
    /// </summary>
    public string GPS_DATE { get; set; }
        
    /// <summary>
    ///VDMS
    /// </summary>
    public string VDMS { get; set; }
        
    /// <summary>
    ///操作者
    /// </summary>
    public string OPERATOR_MAN { get; set; }
        
    /// <summary>
    ///胎压 (结果串)
    /// </summary>
    public string TIRE_STRING { get; set; }
        
    /// <summary>
    ///胎压 (右前)
    /// </summary>
    public string TIRE_RF { get; set; }
        
    /// <summary>
    ///胎压 (左前)
    /// </summary>
    public string TIRE_LF { get; set; }
        
    /// <summary>
    ///胎压 (右后)
    /// </summary>
    public string TIRE_RB { get; set; }
        
    /// <summary>
    ///胎压 (左后)
    /// </summary>
    public string TIRE_LB { get; set; }
        
    /// <summary>
    ///开阔视野 (结果串)
    /// </summary>
    public string VISION_STRING { get; set; }
        
    /// <summary>
    ///开阔视野 (平均角度)
    /// </summary>
    public string VISION_AVG_ANGLE { get; set; }
        
    /// <summary>
    ///中心线 (结果串)
    /// </summary>
    public string CENTER_LINE_STRING { get; set; }
        
    /// <summary>
    ///中心线2 (结果串)
    /// </summary>
    public string CENTER_LINE_TWO_STRING { get; set; }
        
    /// <summary>
    ///中心线 (左向跑偏限值)
    /// </summary>
    public string CENTER_LINE_L_RUN_DEVI_VAL { get; set; }
        
    /// <summary>
    ///中心线 (右向跑偏限值)
    /// </summary>
    public string CENTER_LINE_R_RUN_DEVI_VAL { get; set; }
        
    /// <summary>
    ///中心线 (左边横向速度限值)
    /// </summary>
    public string CENTER_LINE_L_LAT_SPEED_VAL { get; set; }
        
    /// <summary>
    ///中心线 (右边横向速度限值)
    /// </summary>
    public string CENTER_LINE_R_LAT_SPEED_VAL { get; set; }
        
    /// <summary>
    ///中心线 (最大卫星数)
    /// </summary>
    public string CENTER_LINE_SATE_MAX { get; set; }
        
    /// <summary>
    ///中心线 (最小卫星数)
    /// </summary>
    public string CENTER_LINE_SATE_MIN { get; set; }
        
    /// <summary>
    ///中心线 (跑偏值)
    /// </summary>
    public string CENTER_LINE_RUN_DEVI_VAL { get; set; }
        
    /// <summary>
    ///设置 (胎压设置)
    /// </summary>
    public string SET_TIRE { get; set; }
        
    /// <summary>
    ///设置 (开阔视野设置)
    /// </summary>
    public string SET_VISION { get; set; }
        
    /// <summary>
    ///设置 (中心线设置)
    /// </summary>
    public string SET_CENTER_LINE { get; set; }
        
    /// <summary>
    ///设置 (速度表试验设置)
    /// </summary>
    public string SET_SPEED_TEST { get; set; }
        
    /// <summary>
    ///设置 (制动试验设置)
    /// </summary>
    public string SET_BRAKE_TEST { get; set; }
        
    /// <summary>
    ///速度表测试 (结果串)
    /// </summary>
    public string SPEED_TEST_STRING { get; set; }
        
    /// <summary>
    ///速度表测试 (测量速度)
    /// </summary>
    public string SPEED_TEST_MEAS_SPEED { get; set; }
        
    /// <summary>
    ///制动试验 (结果串)
    /// </summary>
    public string BRAKE_TEST_STRING { get; set; }
        
    /// <summary>
    ///制动试验 (测量距离)
    /// </summary>
    public string BRAKE_TEST_MEAS_DISTANCE { get; set; }
        
    /// <summary>
    ///制动试验 (制动速度)
    /// </summary>
    public string BRAKE_TEST_SPEED { get; set; }
        
    /// <summary>
    ///电源后门 (结果串)
    /// </summary>
    public string POWER_BACK_DOOR { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///测量风速
    /// </summary>
    public decimal MEAS_WIND_SPEED { get; set; }
        
    /// <summary>
    ///测量路面
    /// </summary>
    public string MEAS_ROAD { get; set; }
        
    /// <summary>
    ///测量一次
    /// </summary>
    public decimal MEAS_ONE_TIMES { get; set; }
        
    /// <summary>
    ///测量二次
    /// </summary>
    public decimal MEAS_TWO_TIMES { get; set; }
        
    /// <summary>
    ///测量三次
    /// </summary>
    public decimal MEAS_THR_TIMES { get; set; }
        
    /// <summary>
    ///数据来源 默认为0 0为接口数据 1为数据维护
    /// </summary>
    public string DATA_SOURCE { get; set; }
    }
}
