//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///OP230最终测量机ZZ信息表
    /// </summary>
    public partial class T_PQ_BU_CS_OP230ZZ_MEAS_MAC
    {
        
    /// <summary>
    ///OP230最终测量机ID
    /// </summary>
    public string MEAS_MAC_OP230_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///工程
    /// </summary>
    public string ENGINEERING_TYPE { get; set; }
        
    /// <summary>
    ///设备编码
    /// </summary>
    public string EQUIP_CODE { get; set; }
        
    /// <summary>
    ///扫描时间
    /// </summary>
    public System.DateTime SWEEP_TIME_VAL { get; set; }
        
    /// <summary>
    ///二维码
    /// </summary>
    public string QR_CODE { get; set; }
        
    /// <summary>
    ///测量2D码刻印信息
    /// </summary>
    public string MEASURE_2D_CODE { get; set; }
        
    /// <summary>
    ///测量结果
    /// </summary>
    public string MEASURE_RESULT { get; set; }
        
    /// <summary>
    ///搬入时间
    /// </summary>
    public System.DateTime MOVE_IN_TIME { get; set; }
        
    /// <summary>
    ///搬出时间
    /// </summary>
    public System.DateTime MOVE_OUT_TIME { get; set; }
        
    /// <summary>
    ///Dia.Main1 Sect 1
    /// </summary>
    public decimal DIA_MAIN1_SECT1 { get; set; }
        
    /// <summary>
    ///Dia.Main1 Sect 2
    /// </summary>
    public decimal DIA_MAIN1_SECT2 { get; set; }
        
    /// <summary>
    ///Dia.Main1 Sect 3
    /// </summary>
    public decimal DIA_MAIN1_SECT3 { get; set; }
        
    /// <summary>
    ///Round.Main1 Sect 1
    /// </summary>
    public decimal ROUND_MAIN1_SECT1 { get; set; }
        
    /// <summary>
    ///Round.Main1 Sect 2
    /// </summary>
    public decimal ROUND_MAIN1_SECT2 { get; set; }
        
    /// <summary>
    ///Round.Main1 Sect 3
    /// </summary>
    public decimal ROUND_MAIN1_SECT3 { get; set; }
        
    /// <summary>
    ///Straigt.Main1
    /// </summary>
    public decimal STRAIGT_MAIN1 { get; set; }
        
    /// <summary>
    ///Parallelism Main1
    /// </summary>
    public decimal PARALLELISM_MAIN1 { get; set; }
        
    /// <summary>
    ///Dia.Main2 Sect 1
    /// </summary>
    public decimal DIA_MAIN2_SECT1 { get; set; }
        
    /// <summary>
    ///Dia.Main2 Sect 2
    /// </summary>
    public decimal DIA_MAIN2_SECT2 { get; set; }
        
    /// <summary>
    ///Dia.Main2 Sect 3
    /// </summary>
    public decimal DIA_MAIN2_SECT3 { get; set; }
        
    /// <summary>
    ///Round.Main2 Sect 1
    /// </summary>
    public decimal ROUND_MAIN2_SECT1 { get; set; }
        
    /// <summary>
    ///Round.Main2 Sect 2
    /// </summary>
    public decimal ROUND_MAIN2_SECT2 { get; set; }
        
    /// <summary>
    ///Round.Main2 Sect 3
    /// </summary>
    public decimal ROUND_MAIN2_SECT3 { get; set; }
        
    /// <summary>
    ///Straigt.Main2
    /// </summary>
    public decimal STRAIGT_MAIN2 { get; set; }
        
    /// <summary>
    ///Parallelism Main2
    /// </summary>
    public decimal PARALLELISM_MAIN2 { get; set; }
        
    /// <summary>
    ///Runout Main2
    /// </summary>
    public decimal RUNOUT_MAIN2 { get; set; }
        
    /// <summary>
    ///Dia.Main3 Sect 1
    /// </summary>
    public decimal DIA_MAIN3_SECT1 { get; set; }
        
    /// <summary>
    ///Dia.Main3 Sect 2
    /// </summary>
    public decimal DIA_MAIN3_SECT2 { get; set; }
        
    /// <summary>
    ///Dia.Main3 Sect 3
    /// </summary>
    public decimal DIA_MAIN3_SECT3 { get; set; }
        
    /// <summary>
    ///Round.Main3 Sect 1
    /// </summary>
    public decimal ROUND_MAIN3_SECT1 { get; set; }
        
    /// <summary>
    ///Round.Main3 Sect 2
    /// </summary>
    public decimal ROUND_MAIN3_SECT2 { get; set; }
        
    /// <summary>
    ///Round.Main3 Sect 3
    /// </summary>
    public decimal ROUND_MAIN3_SECT3 { get; set; }
        
    /// <summary>
    ///Straigt.Main3
    /// </summary>
    public decimal STRAIGT_MAIN3 { get; set; }
        
    /// <summary>
    ///Parallelism Main3
    /// </summary>
    public decimal PARALLELISM_MAIN3 { get; set; }
        
    /// <summary>
    ///Dia.Main4 Sect 1
    /// </summary>
    public decimal DIA_MAIN4_SECT1 { get; set; }
        
    /// <summary>
    ///Dia.Main4 Sect 2
    /// </summary>
    public decimal DIA_MAIN4_SECT2 { get; set; }
        
    /// <summary>
    ///Dia.Main4 Sect 3
    /// </summary>
    public decimal DIA_MAIN4_SECT3 { get; set; }
        
    /// <summary>
    ///Round.Main4 Sect 1
    /// </summary>
    public decimal ROUND_MAIN4_SECT1 { get; set; }
        
    /// <summary>
    ///Round.Main4 Sect 2
    /// </summary>
    public decimal ROUND_MAIN4_SECT2 { get; set; }
        
    /// <summary>
    ///Round.Main4 Sect 3
    /// </summary>
    public decimal ROUND_MAIN4_SECT3 { get; set; }
        
    /// <summary>
    ///Straigt.Main4
    /// </summary>
    public decimal STRAIGT_MAIN4 { get; set; }
        
    /// <summary>
    ///Parallelism Main4
    /// </summary>
    public decimal PARALLELISM_MAIN4 { get; set; }
        
    /// <summary>
    ///Runout Main4
    /// </summary>
    public decimal RUNOUT_MAIN4 { get; set; }
        
    /// <summary>
    ///Dia.Main5 Sect 1
    /// </summary>
    public decimal DIA_MAIN5_SECT1 { get; set; }
        
    /// <summary>
    ///Dia.Main5 Sect 2
    /// </summary>
    public decimal DIA_MAIN5_SECT2 { get; set; }
        
    /// <summary>
    ///Dia.Main5 Sect 3
    /// </summary>
    public decimal DIA_MAIN5_SECT3 { get; set; }
        
    /// <summary>
    ///Round.Main5 Sect 1
    /// </summary>
    public decimal ROUND_MAIN5_SECT1 { get; set; }
        
    /// <summary>
    ///Round.Main5 Sect 2
    /// </summary>
    public decimal ROUND_MAIN5_SECT2 { get; set; }
        
    /// <summary>
    ///Round.Main5 Sect 3
    /// </summary>
    public decimal ROUND_MAIN5_SECT3 { get; set; }
        
    /// <summary>
    ///Straigt.Main5
    /// </summary>
    public decimal STRAIGT_MAIN5 { get; set; }
        
    /// <summary>
    ///Parallelism Main5
    /// </summary>
    public decimal PARALLELISM_MAIN5 { get; set; }
        
    /// <summary>
    ///Dia.Pin1 Sect 1
    /// </summary>
    public decimal DIA_PIN1_SECT1 { get; set; }
        
    /// <summary>
    ///Dia.Pin1 Sect 2
    /// </summary>
    public decimal DIA_PIN1_SECT2 { get; set; }
        
    /// <summary>
    ///Dia.Pin1 Sect 3
    /// </summary>
    public decimal DIA_PIN1_SECT3 { get; set; }
        
    /// <summary>
    ///Round.Pin1 Sect 1
    /// </summary>
    public decimal ROUND_PIN1_SECT1 { get; set; }
        
    /// <summary>
    ///Round.Pin1 Sect 2
    /// </summary>
    public decimal ROUND_PIN1_SECT2 { get; set; }
        
    /// <summary>
    ///Round.Pin1 Sect 3
    /// </summary>
    public decimal ROUND_PIN1_SECT3 { get; set; }
        
    /// <summary>
    ///Straigt.Pin1
    /// </summary>
    public decimal STRAIGT_PIN1 { get; set; }
        
    /// <summary>
    ///Parallelism Pin1
    /// </summary>
    public decimal PARALLELISM_PIN1 { get; set; }
        
    /// <summary>
    ///Dia.Pin2 Sect 1
    /// </summary>
    public decimal DIA_PIN2_SECT1 { get; set; }
        
    /// <summary>
    ///Dia.Pin2 Sect 2
    /// </summary>
    public decimal DIA_PIN2_SECT2 { get; set; }
        
    /// <summary>
    ///Dia.Pin2 Sect 3
    /// </summary>
    public decimal DIA_PIN2_SECT3 { get; set; }
        
    /// <summary>
    ///Round.Pin2 Sect 1
    /// </summary>
    public decimal ROUND_PIN2_SECT1 { get; set; }
        
    /// <summary>
    ///Round.Pin2 Sect 2
    /// </summary>
    public decimal ROUND_PIN2_SECT2 { get; set; }
        
    /// <summary>
    ///Round.Pin2 Sect 3
    /// </summary>
    public decimal ROUND_PIN2_SECT3 { get; set; }
        
    /// <summary>
    ///Straigt.Pin2
    /// </summary>
    public decimal STRAIGT_PIN2 { get; set; }
        
    /// <summary>
    ///Parallelism Pin2
    /// </summary>
    public decimal PARALLELISM_PIN2 { get; set; }
        
    /// <summary>
    ///Dia.Pin3 Sect 1
    /// </summary>
    public decimal DIA_PIN3_SECT1 { get; set; }
        
    /// <summary>
    ///Dia.Pin3 Sect 2
    /// </summary>
    public decimal DIA_PIN3_SECT2 { get; set; }
        
    /// <summary>
    ///Dia.Pin3 Sect 3
    /// </summary>
    public decimal DIA_PIN3_SECT3 { get; set; }
        
    /// <summary>
    ///Round.Pin3 Sect 1
    /// </summary>
    public decimal ROUND_PIN3_SECT1 { get; set; }
        
    /// <summary>
    ///Round.Pin3 Sect 2
    /// </summary>
    public decimal ROUND_PIN3_SECT2 { get; set; }
        
    /// <summary>
    ///Round.Pin3 Sect 3
    /// </summary>
    public decimal ROUND_PIN3_SECT3 { get; set; }
        
    /// <summary>
    ///Straigt.Pin3
    /// </summary>
    public decimal STRAIGT_PIN3 { get; set; }
        
    /// <summary>
    ///Parallelism Pin3
    /// </summary>
    public decimal PARALLELISM_PIN3 { get; set; }
        
    /// <summary>
    ///Dia.Pin4 Sect 1
    /// </summary>
    public decimal DIA_PIN4_SECT1 { get; set; }
        
    /// <summary>
    ///Dia.Pin4 Sect 2
    /// </summary>
    public decimal DIA_PIN4_SECT2 { get; set; }
        
    /// <summary>
    ///Dia.Pin4 Sect 3
    /// </summary>
    public decimal DIA_PIN4_SECT3 { get; set; }
        
    /// <summary>
    ///Round.Pin4 Sect 1
    /// </summary>
    public decimal ROUND_PIN4_SECT1 { get; set; }
        
    /// <summary>
    ///Round.Pin4 Sect 2
    /// </summary>
    public decimal ROUND_PIN4_SECT2 { get; set; }
        
    /// <summary>
    ///Round.Pin4 Sect 3
    /// </summary>
    public decimal ROUND_PIN4_SECT3 { get; set; }
        
    /// <summary>
    ///Straigt.Pin4
    /// </summary>
    public decimal STRAIGT_PIN4 { get; set; }
        
    /// <summary>
    ///Parallelism Pin4
    /// </summary>
    public decimal PARALLELISM_PIN4 { get; set; }
        
    /// <summary>
    ///Dia.Flange
    /// </summary>
    public decimal DIA_FLANGE { get; set; }
        
    /// <summary>
    ///Class Dia.Main1
    /// </summary>
    public decimal CLASS_DIA_MAIN1 { get; set; }
        
    /// <summary>
    ///Class Dia.Main2
    /// </summary>
    public decimal CLASS_DIA_MAIN2 { get; set; }
        
    /// <summary>
    ///Class Dia.Main3
    /// </summary>
    public decimal CLASS_DIA_MAIN3 { get; set; }
        
    /// <summary>
    ///Class Dia.Main4
    /// </summary>
    public decimal CLASS_DIA_MAIN4 { get; set; }
        
    /// <summary>
    ///Class Dia.Main5
    /// </summary>
    public decimal CLASS_DIA_MAIN5 { get; set; }
        
    /// <summary>
    ///Class Dia.Pin1
    /// </summary>
    public decimal CLASS_DIA_PIN1 { get; set; }
        
    /// <summary>
    ///Class Dia.Pin2
    /// </summary>
    public decimal CLASS_DIA_PIN2 { get; set; }
        
    /// <summary>
    ///Class Dia.Pin3
    /// </summary>
    public decimal CLASS_DIA_PIN3 { get; set; }
        
    /// <summary>
    ///Class Dia.Pin4
    /// </summary>
    public decimal CLASS_DIA_PIN4 { get; set; }
        
    /// <summary>
    ///Runout Main3
    /// </summary>
    public decimal RUNOUT_MAIN3 { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///部品工序信息ID
    /// </summary>
    public string PART_PROCESS_ID { get; set; }
        
    /// <summary>
    ///逻辑工序
    /// </summary>
    public string LOGIC_PROCESS { get; set; }
    }
}
