//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_PQ_TD_COLDATA
    /// </summary>
    public partial class T_PQ_TD_COLDATA
    {
        
    /// <summary>
    ///COLDATA_ID
    /// </summary>
    public string COLDATA_ID { get; set; }
        
    /// <summary>
    ///BA_POINT_MEAS_ID
    /// </summary>
    public string BA_POINT_MEAS_ID { get; set; }
        
    /// <summary>
    ///PART_POS
    /// </summary>
    public string PART_POS { get; set; }
        
    /// <summary>
    ///POS_ID
    /// </summary>
    public string POS_ID { get; set; }
        
    /// <summary>
    ///POS_NAME
    /// </summary>
    public string POS_NAME { get; set; }
        
    /// <summary>
    ///RL_VAL
    /// </summary>
    public string RL_VAL { get; set; }
        
    /// <summary>
    ///DIRECTION
    /// </summary>
    public string DIRECTION { get; set; }
        
    /// <summary>
    ///ATTRIBUTE_VAL
    /// </summary>
    public string ATTRIBUTE_VAL { get; set; }
        
    /// <summary>
    ///CURVAL
    /// </summary>
    public string CURVAL { get; set; }
        
    /// <summary>
    ///CHECK_SPEC_ADD
    /// </summary>
    public string CHECK_SPEC_ADD { get; set; }
        
    /// <summary>
    ///CHECK_SPEC_SUBTRA
    /// </summary>
    public string CHECK_SPEC_SUBTRA { get; set; }
        
    /// <summary>
    ///CHECK_JUDGE
    /// </summary>
    public string CHECK_JUDGE { get; set; }
        
    /// <summary>
    ///INNER_SPEC_ADD
    /// </summary>
    public string INNER_SPEC_ADD { get; set; }
        
    /// <summary>
    ///INNER_SPEC_SUBTRA
    /// </summary>
    public string INNER_SPEC_SUBTRA { get; set; }
        
    /// <summary>
    ///INNER_JUDGE
    /// </summary>
    public string INNER_JUDGE { get; set; }
        
    /// <summary>
    ///TEST_TYPE
    /// </summary>
    public string TEST_TYPE { get; set; }
        
    /// <summary>
    ///COLLECTOR
    /// </summary>
    public string COLLECTOR { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP_ORG_ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///P1_POS_ID
    /// </summary>
    public string P1_POS_ID { get; set; }
        
    /// <summary>
    ///P1_POS_NAME
    /// </summary>
    public string P1_POS_NAME { get; set; }
        
    /// <summary>
    ///P2_POS_ID
    /// </summary>
    public string P2_POS_ID { get; set; }
        
    /// <summary>
    ///P2_POS_NAME
    /// </summary>
    public string P2_POS_NAME { get; set; }
        
    /// <summary>
    ///P3_POS_ID
    /// </summary>
    public string P3_POS_ID { get; set; }
        
    /// <summary>
    ///P3_POS_NAME
    /// </summary>
    public string P3_POS_NAME { get; set; }
        
    /// <summary>
    ///P4_POS_ID
    /// </summary>
    public string P4_POS_ID { get; set; }
        
    /// <summary>
    ///P4_POS_NAME
    /// </summary>
    public string P4_POS_NAME { get; set; }
        
    /// <summary>
    ///CALC_ID
    /// </summary>
    public string CALC_ID { get; set; }
    }
}
