//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///柱图配置表
    /// </summary>
    public partial class T_PQ_DB_BARCHART_CONFIGURE
    {
        
    /// <summary>
    ///柱图配置表ID
    /// </summary>
    public string CONFIGURE { get; set; }
        
    /// <summary>
    ///图表类型(1:小时推移图2:日推移图)
    /// </summary>
    public string CHARTTYPE { get; set; }
        
    /// <summary>
    ///所选车型数量(对应图表类型)
    /// </summary>
    public decimal CAR_COUNT { get; set; }
        
    /// <summary>
    ///默认往前推移组数
    /// </summary>
    public decimal DEFAULT_PRE_GROUPS { get; set; }
        
    /// <summary>
    ///默认往前推移组数最小值
    /// </summary>
    public decimal DEFAULT_PRE_GROUPS_MIN { get; set; }
        
    /// <summary>
    ///默认往前推移组数最大值
    /// </summary>
    public decimal DEFAULT_PRE_GROUPS_MAX { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
