//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_PQ_BU_E_ASSE_BAT_TEMP
    /// </summary>
    public partial class T_PQ_BU_E_ASSE_BAT_TEMP
    {
        
    /// <summary>
    ///E_ASSE_BAT_ID
    /// </summary>
    public string E_ASSE_BAT_ID { get; set; }
        
    /// <summary>
    ///FACTORY_CODE
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///PRO_LINE_CODE
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///MAC_TYPE
    /// </summary>
    public string MAC_TYPE { get; set; }
        
    /// <summary>
    ///ENGINE_NO
    /// </summary>
    public string ENGINE_NO { get; set; }
        
    /// <summary>
    ///ENGINE_STATUS
    /// </summary>
    public string ENGINE_STATUS { get; set; }
        
    /// <summary>
    ///ENGINE_CODE
    /// </summary>
    public string ENGINE_CODE { get; set; }
        
    /// <summary>
    ///STATUS_UPD_QTY
    /// </summary>
    public decimal STATUS_UPD_QTY { get; set; }
        
    /// <summary>
    ///STATUS_CHANGE_SOURCE
    /// </summary>
    public string STATUS_CHANGE_SOURCE { get; set; }
        
    /// <summary>
    ///MAIN_SHAFT_TILE_GRADE
    /// </summary>
    public string MAIN_SHAFT_TILE_GRADE { get; set; }
        
    /// <summary>
    ///CONNECTING_ROD_GRADE
    /// </summary>
    public string CONNECTING_ROD_GRADE { get; set; }
        
    /// <summary>
    ///PISTON_GRADE
    /// </summary>
    public string PISTON_GRADE { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP_ORG_ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///FACTORY_NAME
    /// </summary>
    public string FACTORY_NAME { get; set; }
        
    /// <summary>
    ///LOGIC_STATUS
    /// </summary>
    public short LOGIC_STATUS { get; set; }
        
    /// <summary>
    ///BAD_DATA_ID
    /// </summary>
    public string BAD_DATA_ID { get; set; }
        
    /// <summary>
    ///STATUS_CHANGE_MAN
    /// </summary>
    public string STATUS_CHANGE_MAN { get; set; }
        
    /// <summary>
    ///CHANGE_TIME
    /// </summary>
    public System.DateTime CHANGE_TIME { get; set; }
        
    /// <summary>
    ///DUTY_DEPT
    /// </summary>
    public string DUTY_DEPT { get; set; }
        
    /// <summary>
    ///CHANGE_BAT
    /// </summary>
    public string CHANGE_BAT { get; set; }
        
    /// <summary>
    ///CHANGE_REMARK
    /// </summary>
    public string CHANGE_REMARK { get; set; }
        
    /// <summary>
    ///BAD_BIG_TYPE
    /// </summary>
    public string BAD_BIG_TYPE { get; set; }
        
    /// <summary>
    ///BAD_TYPE
    /// </summary>
    public string BAD_TYPE { get; set; }
        
    /// <summary>
    ///ONLINE_TIME
    /// </summary>
    public System.DateTime ONLINE_TIME { get; set; }
        
    /// <summary>
    ///OFFLINE_TIME
    /// </summary>
    public System.DateTime OFFLINE_TIME { get; set; }
        
    /// <summary>
    ///CYLINDER_JR_GRADE
    /// </summary>
    public string CYLINDER_JR_GRADE { get; set; }
        
    /// <summary>
    ///CRANKSHAFT_JRPIN_GRADE
    /// </summary>
    public string CRANKSHAFT_JRPIN_GRADE { get; set; }
        
    /// <summary>
    ///RECEIVE_TIME
    /// </summary>
    public System.DateTime RECEIVE_TIME { get; set; }
    }
}
