//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///不合格品单主信息表
    /// </summary>
    public partial class T_PQ_BU_REJ_BILL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PQ_BU_REJ_BILL()
        {
            this.T_PQ_BU_REJ_BILL_DUTY_COMP = new HashSet<T_PQ_BU_REJ_BILL_DUTY_COMP>();
            this.T_PQ_BU_REJ_BILL_OTHER_FEE = new HashSet<T_PQ_BU_REJ_BILL_OTHER_FEE>();
            this.T_PQ_BU_REJ_BILL_PART = new HashSet<T_PQ_BU_REJ_BILL_PART>();
            this.T_PQ_BU_REJ_BILL_RAW_MAT = new HashSet<T_PQ_BU_REJ_BILL_RAW_MAT>();
        }
    
        
    /// <summary>
    ///不合格品单ID
    /// </summary>
    public string REJ_BILL_ID { get; set; }
        
    /// <summary>
    ///系统单号
    /// </summary>
    public string SYSTEM_BILL_CODE { get; set; }
        
    /// <summary>
    ///不合格品单号
    /// </summary>
    public string REJ_BILL_CODE { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///报废类别
    /// </summary>
    public string SCRAP_TYPE { get; set; }
        
    /// <summary>
    ///不良日期
    /// </summary>
    public System.DateTime BAD_DATE { get; set; }
        
    /// <summary>
    ///录单日期
    /// </summary>
    public System.DateTime REC_BILL_DATE { get; set; }
        
    /// <summary>
    ///提交日期
    /// </summary>
    public System.DateTime COMM_DATE { get; set; }
        
    /// <summary>
    ///制造车系
    /// </summary>
    public string MADE_CAR_SERIES { get; set; }
        
    /// <summary>
    ///全球车系
    /// </summary>
    public string GLOBAL_CAR_SERIES { get; set; }
        
    /// <summary>
    ///解析员
    /// </summary>
    public string RESOLVE_MAN { get; set; }
        
    /// <summary>
    ///发生地
    /// </summary>
    public string HAP_ADD { get; set; }
        
    /// <summary>
    ///不良原因编码
    /// </summary>
    public string BAD_REASON_CODE { get; set; }
        
    /// <summary>
    ///不良原因描述
    /// </summary>
    public string BAD_REASON_DESC { get; set; }
        
    /// <summary>
    ///判定类别
    /// </summary>
    public string JUDGE_TYPE { get; set; }
        
    /// <summary>
    ///当前状态
    /// </summary>
    public string CUR_STATUS { get; set; }
        
    /// <summary>
    ///发送状态
    /// </summary>
    public string SEND_STATUS { get; set; }
        
    /// <summary>
    ///驳回原因
    /// </summary>
    public string REJ_REASON { get; set; }
        
    /// <summary>
    ///是否记入PPM
    /// </summary>
    public string IS_REC_PPM { get; set; }
        
    /// <summary>
    ///存放区域
    /// </summary>
    public string STORE_AREA { get; set; }
        
    /// <summary>
    ///总金额
    /// </summary>
    public decimal TOT_AMT { get; set; }
        
    /// <summary>
    ///零件金额合计
    /// </summary>
    public decimal PART_AMT_TOT { get; set; }
        
    /// <summary>
    ///工时费用合计
    /// </summary>
    public decimal WI_AMOUNT_TOT { get; set; }
        
    /// <summary>
    ///其它费用合计
    /// </summary>
    public decimal OTHER_FEE_TOT { get; set; }
        
    /// <summary>
    ///发布日期
    /// </summary>
    public System.DateTime RELEASE_DATE { get; set; }
        
    /// <summary>
    ///物料类型
    /// </summary>
    public string MATERIAL_TYPE { get; set; }
        
    /// <summary>
    ///赔偿金额
    /// </summary>
    public decimal INDEM_AMT { get; set; }
        
    /// <summary>
    ///物流分类确认状态
    /// </summary>
    public string LOG_TYPE_COMF_STATUS { get; set; }
        
    /// <summary>
    ///承担比例变更人
    /// </summary>
    public string BEAR_RATE_CHAN_MAN { get; set; }
        
    /// <summary>
    ///承担比例变更备注
    /// </summary>
    public string BEAR_RATE_CHAN_REMARK { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///K系数
    /// </summary>
    public decimal K_COEF { get; set; }
        
    /// <summary>
    ///成本中心编码
    /// </summary>
    public string COST_CENTER_CODE { get; set; }
        
    /// <summary>
    ///KD残值
    /// </summary>
    public decimal KD_RESI_VAL { get; set; }
        
    /// <summary>
    ///KD备注
    /// </summary>
    public string KD_REMARK { get; set; }
        
    /// <summary>
    ///申诉关联标记
    /// </summary>
    public string FLAG_APPEAL_RLT { get; set; }
        
    /// <summary>
    ///纳入数量
    /// </summary>
    public decimal INCLU_QTY { get; set; }
        
    /// <summary>
    ///是否再发
    /// </summary>
    public string IS_RESEND { get; set; }
        
    /// <summary>
    ///是否批量
    /// </summary>
    public string IS_BATCH { get; set; }
        
    /// <summary>
    ///检查速报ID
    /// </summary>
    public string INSPECT_RPT_ID { get; set; }
        
    /// <summary>
    ///PPM状态
    /// </summary>
    public string PPM_STATUS { get; set; }
        
    /// <summary>
    ///公司编码，值列表COMPANY
    /// </summary>
    public string COMP_CODE { get; set; }
        
    /// <summary>
    ///品牌编码,值列表CAR_BRAND_CODE
    /// </summary>
    public string BRAND_CODE { get; set; }
        
    /// <summary>
    ///PPM提交人
    /// </summary>
    public string PPM_PROPOSER { get; set; }
        
    /// <summary>
    ///PPM提交时间
    /// </summary>
    public System.DateTime PPM_PRO_TIME { get; set; }
        
    /// <summary>
    ///PPM确认人
    /// </summary>
    public string PPM_CONFIRMER { get; set; }
        
    /// <summary>
    ///PPM确认时间
    /// </summary>
    public System.DateTime PPM_CON_TIME { get; set; }
        
    /// <summary>
    ///PPM审批人
    /// </summary>
    public string PPM_APPROVER { get; set; }
        
    /// <summary>
    ///PPM审批时间
    /// </summary>
    public System.DateTime PPM_APP_TIME { get; set; }
        
    /// <summary>
    ///是否纳入制程不具合扣分
    /// </summary>
    public string IS_MAJOR_DEFECT { get; set; }
        
    /// <summary>
    ///记入PPM原因
    /// </summary>
    public string RECODE_PPM_REASON { get; set; }
        
    /// <summary>
    ///财务是否过账
    /// </summary>
    public string IS_FINAN_POST { get; set; }
        
    /// <summary>
    ///PPM供应商
    /// </summary>
    public string PPM_SUPPLIER { get; set; }
        
    /// <summary>
    ///实际审批月
    /// </summary>
    public System.DateTime REAL_APPROVE_TIME { get; set; }
        
    /// <summary>
    ///担当工程师
    /// </summary>
    public string PPM_MAN { get; set; }
        
    /// <summary>
    ///是否到货少货单
    /// </summary>
    public string IS_ARRI_LESS_BILL { get; set; }
        
    /// <summary>
    ///当工顺
    /// </summary>
    public string WORK_ORDER { get; set; }
        
    /// <summary>
    ///申请类型，1-仓库，2-新车，3-KIT线边，4-KIT二次物流，5-生产线，6-整车返修，7-费用，大连的才有值。
    /// </summary>
    public string APPL_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_REJ_BILL_DUTY_COMP> T_PQ_BU_REJ_BILL_DUTY_COMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_REJ_BILL_OTHER_FEE> T_PQ_BU_REJ_BILL_OTHER_FEE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_REJ_BILL_PART> T_PQ_BU_REJ_BILL_PART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_REJ_BILL_RAW_MAT> T_PQ_BU_REJ_BILL_RAW_MAT { get; set; }
    }
}
