//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///工厂品质目标/实际值维护表
    /// </summary>
    public partial class T_PQ_BU_TATGET_ACTUAL
    {
        
    /// <summary>
    ///表ID
    /// </summary>
    public string TATGET_ACTUAL_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///工程车间编码
    /// </summary>
    public string WORKSHOP_CODE { get; set; }
        
    /// <summary>
    ///类别编码
    /// </summary>
    public string PROJECT_TYPE_CODE { get; set; }
        
    /// <summary>
    ///管理项目表ID
    /// </summary>
    public string MANAGE_PROJECT_ID { get; set; }
        
    /// <summary>
    ///车型
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///年
    /// </summary>
    public string YEAR_VAL { get; set; }
        
    /// <summary>
    ///必达—1月目标值
    /// </summary>
    public decimal PILDASH_JAN { get; set; }
        
    /// <summary>
    ///必达—2月目标值
    /// </summary>
    public decimal PILDASH_FEB { get; set; }
        
    /// <summary>
    ///必达—3月目标值
    /// </summary>
    public decimal PILDASH_MAR { get; set; }
        
    /// <summary>
    ///必达—4月目标值
    /// </summary>
    public decimal PILDASH_APR { get; set; }
        
    /// <summary>
    ///必达—5月目标值
    /// </summary>
    public decimal PILDASH_MAY { get; set; }
        
    /// <summary>
    ///必达—6月目标值
    /// </summary>
    public decimal PILDASH_JUN { get; set; }
        
    /// <summary>
    ///必达—7月目标值
    /// </summary>
    public decimal PILDASH_JUL { get; set; }
        
    /// <summary>
    ///必达—8月目标值
    /// </summary>
    public decimal PILDASH_AUG { get; set; }
        
    /// <summary>
    ///必达—9月目标值
    /// </summary>
    public decimal PILDASH_SEP { get; set; }
        
    /// <summary>
    ///必达—10月目标值
    /// </summary>
    public decimal PILDASH_OCT { get; set; }
        
    /// <summary>
    ///必达—11月目标值
    /// </summary>
    public decimal PILDASH_NOV { get; set; }
        
    /// <summary>
    ///必达—12月目标值
    /// </summary>
    public decimal PILDASH_DEC { get; set; }
        
    /// <summary>
    ///挑战1-1月目标值
    /// </summary>
    public decimal CHALLENGE_ONE_JAN { get; set; }
        
    /// <summary>
    ///挑战1-2月目标值
    /// </summary>
    public decimal CHALLENGE_ONE_FEB { get; set; }
        
    /// <summary>
    ///挑战1-3月目标值
    /// </summary>
    public decimal CHALLENGE_ONE_MAR { get; set; }
        
    /// <summary>
    ///挑战1-4月目标值
    /// </summary>
    public decimal CHALLENGE_ONE_APR { get; set; }
        
    /// <summary>
    ///挑战1-5月目标值
    /// </summary>
    public decimal CHALLENGE_ONE_MAY { get; set; }
        
    /// <summary>
    ///挑战1-6月目标值
    /// </summary>
    public decimal CHALLENGE_ONE_JUN { get; set; }
        
    /// <summary>
    ///挑战1-7月目标值
    /// </summary>
    public decimal CHALLENGE_ONE_JUL { get; set; }
        
    /// <summary>
    ///挑战1-8月目标值
    /// </summary>
    public decimal CHALLENGE_ONE_AUG { get; set; }
        
    /// <summary>
    ///挑战1-9月目标值
    /// </summary>
    public decimal CHALLENGE_ONE_SEP { get; set; }
        
    /// <summary>
    ///挑战1-10月目标值
    /// </summary>
    public decimal CHALLENGE_ONE_OCT { get; set; }
        
    /// <summary>
    ///挑战1-11月目标值
    /// </summary>
    public decimal CHALLENGE_ONE_NOV { get; set; }
        
    /// <summary>
    ///挑战1-12月目标值
    /// </summary>
    public decimal CHALLENGE_ONE_DEC { get; set; }
        
    /// <summary>
    ///挑战2-1月目标值
    /// </summary>
    public decimal CHALLENGE_TWO_JAN { get; set; }
        
    /// <summary>
    ///挑战2-2月目标值
    /// </summary>
    public decimal CHALLENGE_TWO_FEB { get; set; }
        
    /// <summary>
    ///挑战2-3月目标值
    /// </summary>
    public decimal CHALLENGE_TWO_MAR { get; set; }
        
    /// <summary>
    ///挑战2-4月目标值
    /// </summary>
    public decimal CHALLENGE_TWO_APR { get; set; }
        
    /// <summary>
    ///挑战2-5月目标值
    /// </summary>
    public decimal CHALLENGE_TWO_MAY { get; set; }
        
    /// <summary>
    ///挑战2-6月目标值
    /// </summary>
    public decimal CHALLENGE_TWO_JUN { get; set; }
        
    /// <summary>
    ///挑战2-7月目标值
    /// </summary>
    public decimal CHALLENGE_TWO_JUL { get; set; }
        
    /// <summary>
    ///挑战2-8月目标值
    /// </summary>
    public decimal CHALLENGE_TWO_AUG { get; set; }
        
    /// <summary>
    ///挑战2-9月目标值
    /// </summary>
    public decimal CHALLENGE_TWO_SEP { get; set; }
        
    /// <summary>
    ///挑战2-10月目标值
    /// </summary>
    public decimal CHALLENGE_TWO_OCT { get; set; }
        
    /// <summary>
    ///挑战2-11月目标值
    /// </summary>
    public decimal CHALLENGE_TWO_NOV { get; set; }
        
    /// <summary>
    ///挑战2-12月目标值
    /// </summary>
    public decimal CHALLENGE_TWO_DEC { get; set; }
        
    /// <summary>
    ///实际值-1月
    /// </summary>
    public decimal ACTUAL_JAN { get; set; }
        
    /// <summary>
    ///实际值-2月
    /// </summary>
    public decimal ACTUAL_FEB { get; set; }
        
    /// <summary>
    ///实际值-3月
    /// </summary>
    public decimal ACTUAL_MAR { get; set; }
        
    /// <summary>
    ///实际值-4月
    /// </summary>
    public decimal ACTUAL_APR { get; set; }
        
    /// <summary>
    ///实际值-5月
    /// </summary>
    public decimal ACTUAL_MAY { get; set; }
        
    /// <summary>
    ///实际值-6月
    /// </summary>
    public decimal ACTUAL_JUN { get; set; }
        
    /// <summary>
    ///实际值-7月
    /// </summary>
    public decimal ACTUAL_JUL { get; set; }
        
    /// <summary>
    ///实际值-8月
    /// </summary>
    public decimal ACTUAL_AUG { get; set; }
        
    /// <summary>
    ///实际值-9月
    /// </summary>
    public decimal ACTUAL_SEP { get; set; }
        
    /// <summary>
    ///实际值-10月
    /// </summary>
    public decimal ACTUAL_OCT { get; set; }
        
    /// <summary>
    ///实际值-11月
    /// </summary>
    public decimal ACTUAL_NOV { get; set; }
        
    /// <summary>
    ///实际值-12月
    /// </summary>
    public decimal ACTUAL_DEC { get; set; }
        
    /// <summary>
    ///0、达成挑战2;1、达成挑战1;2、达成必达;3、未达成必达
    /// </summary>
    public string MON_ASSESS { get; set; }
        
    /// <summary>
    ///半年平均
    /// </summary>
    public decimal HALF_A_YEAR_MEAN { get; set; }
        
    /// <summary>
    ///半年评价:0、达成挑战2;1、达成挑战1;2、达成必达;3、未达成必达
    /// </summary>
    public string HALF_A_YEAR_ASSESS { get; set; }
        
    /// <summary>
    ///全年平均
    /// </summary>
    public decimal YEARLY_MEAN { get; set; }
        
    /// <summary>
    ///全年评价:0、达成挑战2;1、达成挑战1;2、达成必达;3、未达成必达
    /// </summary>
    public string YEARLY_ASSESS { get; set; }
        
    /// <summary>
    ///状态
    /// </summary>
    public string IS_STATUS { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARKS { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///修改人
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///修改日期
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///未达跳2原因分析
    /// </summary>
    public string YY_REMARKS { get; set; }
    }
}
