//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///返修车设置
    /// </summary>
    public partial class T_PQ_BU_FX_SET
    {
        
    /// <summary>
    ///返修车设置ID
    /// </summary>
    public string FX_SET_ID { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///延期报交时间
    /// </summary>
    public string DELIVERY_DELAY_DATE { get; set; }
        
    /// <summary>
    ///延期时长(分)
    /// </summary>
    public decimal DELAYDURATION { get; set; }
        
    /// <summary>
    ///延期修改原因
    /// </summary>
    public string DELIVERY_DELAY_REASON { get; set; }
        
    /// <summary>
    ///延期修改时间
    /// </summary>
    public System.DateTime DELAY_MODIFY_DATE { get; set; }
        
    /// <summary>
    ///延期修改人
    /// </summary>
    public string DELAY_MODIFIER { get; set; }
        
    /// <summary>
    ///是否黑名单(0、否。1、是)
    /// </summary>
    public string IS_BLACK_VIN { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///自动变白名单时间
    /// </summary>
    public System.DateTime AUTOMATICWHITELISTTIME { get; set; }
        
    /// <summary>
    ///黑名单原因
    /// </summary>
    public string BLACKREASON { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
    }
}
