//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///RS项目系统电子化主表
    /// </summary>
    public partial class T_PQ_BU_RSPROJECT_INFO
    {
        
    /// <summary>
    ///RS项目ID
    /// </summary>
    public string RSPROJECT_INFO_ID { get; set; }
        
    /// <summary>
    ///RS项目编号（生成规则，DFL-项目类别-年月份-流水号）
    /// </summary>
    public string PROJECT_CODE { get; set; }
        
    /// <summary>
    ///项目名称
    /// </summary>
    public string ITEM_NAME { get; set; }
        
    /// <summary>
    ///项目类别
    /// </summary>
    public string PROJECT_TYPE { get; set; }
        
    /// <summary>
    ///品牌
    /// </summary>
    public string CAR_BRAND { get; set; }
        
    /// <summary>
    ///项目等级
    /// </summary>
    public string PROJECT_LEVEL { get; set; }
        
    /// <summary>
    ///项目来源
    /// </summary>
    public string PROJECT_RESOURCE { get; set; }
        
    /// <summary>
    ///机能轴
    /// </summary>
    public string SYS_DISTIN { get; set; }
        
    /// <summary>
    ///PFP编号
    /// </summary>
    public string PFP_FIVE_CODE { get; set; }
        
    /// <summary>
    ///水平车型
    /// </summary>
    public string MFGSERIES_CODE { get; set; }
        
    /// <summary>
    ///责任单位类别
    /// </summary>
    public string DUTY_COMP_TYPE { get; set; }
        
    /// <summary>
    ///责任单位编码
    /// </summary>
    public string DUTY_COMP_CODE { get; set; }
        
    /// <summary>
    ///机能担当
    /// </summary>
    public string ENG_ACT { get; set; }
        
    /// <summary>
    ///发生现象、发生条件
    /// </summary>
    public string EVENT_DESC { get; set; }
        
    /// <summary>
    ///发生原因
    /// </summary>
    public string EVENT_REASON { get; set; }
        
    /// <summary>
    ///对策内容
    /// </summary>
    public string EVENT_METHOD { get; set; }
        
    /// <summary>
    ///涉及工厂、车型
    /// </summary>
    public string RELATED_FAC_SER { get; set; }
        
    /// <summary>
    ///涉及范围、台数
    /// </summary>
    public string RELATED_RANGE_CNT { get; set; }
        
    /// <summary>
    ///防止再发责任部门
    /// </summary>
    public string RE_DUTY_ORG { get; set; }
        
    /// <summary>
    ///决议内容
    /// </summary>
    public string DECIDED_DESC { get; set; }
        
    /// <summary>
    ///项目关闭描述
    /// </summary>
    public string PROJECT_CLO_DESC { get; set; }
        
    /// <summary>
    ///TM日期
    /// </summary>
    public System.DateTime TM_DATE { get; set; }
        
    /// <summary>
    ///TC日期
    /// </summary>
    public System.DateTime TC_DATE { get; set; }
        
    /// <summary>
    ///市场专案号
    /// </summary>
    public string CASE_CODE { get; set; }
        
    /// <summary>
    ///市场展开日
    /// </summary>
    public System.DateTime EXPAND_DATE { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///供应商责任比例
    /// </summary>
    public decimal SUP_RESP_RATIO { get; set; }
        
    /// <summary>
    ///责任决定日期
    /// </summary>
    public System.DateTime RESP_DECI_DATE { get; set; }
        
    /// <summary>
    ///影响情况
    /// </summary>
    public string INFLUENCE_SITUATION { get; set; }
        
    /// <summary>
    ///扣分情况
    /// </summary>
    public decimal DEDUCT_POINTS { get; set; }
        
    /// <summary>
    ///维护担当
    /// </summary>
    public string MAINTAIN_DUTY_MAN { get; set; }
        
    /// <summary>
    ///责任划分状态
    /// </summary>
    public string DUTY_D_STATUS { get; set; }
        
    /// <summary>
    ///处置台数
    /// </summary>
    public decimal DISPOSAL_UNITS { get; set; }
    }
}
