//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_PQ_DB_VESV3_TEMP2
    /// </summary>
    public partial class T_PQ_DB_VESV3_TEMP2
    {
        
    /// <summary>
    ///ZZJS
    /// </summary>
    public decimal ZZJS { get; set; }
        
    /// <summary>
    ///VIN_CODE
    /// </summary>
    public string VIN_CODE { get; set; }
        
    /// <summary>
    ///APPRAISE_DATE
    /// </summary>
    public System.DateTime APPRAISE_DATE { get; set; }
        
    /// <summary>
    ///BAD_DESC
    /// </summary>
    public string BAD_DESC { get; set; }
        
    /// <summary>
    ///IQS_SCORE
    /// </summary>
    public string IQS_SCORE { get; set; }
        
    /// <summary>
    ///WK
    /// </summary>
    public string WK { get; set; }
        
    /// <summary>
    ///WEEKHEADER
    /// </summary>
    public string WEEKHEADER { get; set; }
        
    /// <summary>
    ///PFP_SID
    /// </summary>
    public string PFP_SID { get; set; }
        
    /// <summary>
    ///DISTIN_TYPE
    /// </summary>
    public string DISTIN_TYPE { get; set; }
        
    /// <summary>
    ///EVAL_TYPE
    /// </summary>
    public string EVAL_TYPE { get; set; }
    }
}
