//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///熔射单元-精镗后缸孔测量机业务表
    /// </summary>
    public partial class T_PQ_BU_FINE_HOLE
    {
        
    /// <summary>
    ///精膛后缸孔测量机ID
    /// </summary>
    public string CY_S_FINE_HOLE_ID { get; set; }
        
    /// <summary>
    ///工厂
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///生产线
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///工程
    /// </summary>
    public string ENGINEERING_TYPE { get; set; }
        
    /// <summary>
    ///设备号
    /// </summary>
    public string EQUIP_CODE { get; set; }
        
    /// <summary>
    ///时间
    /// </summary>
    public System.DateTime SWEEP_TIME_VAL { get; set; }
        
    /// <summary>
    ///二维码
    /// </summary>
    public string QR_CODE { get; set; }
        
    /// <summary>
    ///1#缸孔截面1X
    /// </summary>
    public string DIA_SECTION_11X { get; set; }
        
    /// <summary>
    ///1#缸孔截面1Y
    /// </summary>
    public string DIA_SECTION_11Y { get; set; }
        
    /// <summary>
    ///1#缸孔截面2X
    /// </summary>
    public string DIA_SECTION_12X { get; set; }
        
    /// <summary>
    ///1#缸孔截面2Y
    /// </summary>
    public string DIA_SECTION_12Y { get; set; }
        
    /// <summary>
    ///1#缸孔截面3X
    /// </summary>
    public string DIA_SECTION_13X { get; set; }
        
    /// <summary>
    ///1#缸孔截面3Y
    /// </summary>
    public string DIA_SECTION_13Y { get; set; }
        
    /// <summary>
    ///1#缸孔截面1椭圆度
    /// </summary>
    public string DIA_SECTION_11OY { get; set; }
        
    /// <summary>
    ///1#缸孔截面2椭圆度
    /// </summary>
    public string DIA_SECTION_12OY { get; set; }
        
    /// <summary>
    ///1#缸孔截面3椭圆度
    /// </summary>
    public string DIA_SECTION_13OY { get; set; }
        
    /// <summary>
    ///1#缸孔X锥度
    /// </summary>
    public string DIA_TAPER_1X { get; set; }
        
    /// <summary>
    ///1#缸孔Y锥度
    /// </summary>
    public string DIA_TAPER_1Y { get; set; }
        
    /// <summary>
    ///2#缸孔截面1X
    /// </summary>
    public string DIA_SECTION_21X { get; set; }
        
    /// <summary>
    ///2#缸孔截面1Y
    /// </summary>
    public string DIA_SECTION_21Y { get; set; }
        
    /// <summary>
    ///2#缸孔截面2X
    /// </summary>
    public string DIA_SECTION_22X { get; set; }
        
    /// <summary>
    ///2#缸孔截面2Y
    /// </summary>
    public string DIA_SECTION_22Y { get; set; }
        
    /// <summary>
    ///2#缸孔截面3X
    /// </summary>
    public string DIA_SECTION_23X { get; set; }
        
    /// <summary>
    ///2#缸孔截面3Y
    /// </summary>
    public string DIA_SECTION_23Y { get; set; }
        
    /// <summary>
    ///2#缸孔截面1椭圆度
    /// </summary>
    public string DIA_SECTION_21OY { get; set; }
        
    /// <summary>
    ///2#缸孔截面2椭圆度
    /// </summary>
    public string DIA_SECTION_22OY { get; set; }
        
    /// <summary>
    ///2#缸孔截面3椭圆度
    /// </summary>
    public string DIA_SECTION_23OY { get; set; }
        
    /// <summary>
    ///2#缸孔X锥度
    /// </summary>
    public string DIA_TAPER_2X { get; set; }
        
    /// <summary>
    ///2#缸孔Y锥度
    /// </summary>
    public string DIA_TAPER_2Y { get; set; }
        
    /// <summary>
    ///3#缸孔截面1X
    /// </summary>
    public string DIA_SECTION_31X { get; set; }
        
    /// <summary>
    ///3#缸孔截面1Y
    /// </summary>
    public string DIA_SECTION_31Y { get; set; }
        
    /// <summary>
    ///3#缸孔截面2X
    /// </summary>
    public string DIA_SECTION_32X { get; set; }
        
    /// <summary>
    ///3#缸孔截面2Y
    /// </summary>
    public string DIA_SECTION_32Y { get; set; }
        
    /// <summary>
    ///3#缸孔截面3X
    /// </summary>
    public string DIA_SECTION_33X { get; set; }
        
    /// <summary>
    ///3#缸孔截面3Y
    /// </summary>
    public string DIA_SECTION_33Y { get; set; }
        
    /// <summary>
    ///3#缸孔截面1椭圆度
    /// </summary>
    public string DIA_SECTION_31OY { get; set; }
        
    /// <summary>
    ///3#缸孔截面2椭圆度
    /// </summary>
    public string DIA_SECTION_32OY { get; set; }
        
    /// <summary>
    ///3#缸孔截面3椭圆度
    /// </summary>
    public string DIA_SECTION_33OY { get; set; }
        
    /// <summary>
    ///3#缸孔X锥度
    /// </summary>
    public string DIA_TAPER_3X { get; set; }
        
    /// <summary>
    ///3#缸孔Y锥度
    /// </summary>
    public string DIA_TAPER_3Y { get; set; }
        
    /// <summary>
    ///4#缸孔截面1X
    /// </summary>
    public string DIA_SECTION_41X { get; set; }
        
    /// <summary>
    ///4#缸孔截面1Y
    /// </summary>
    public string DIA_SECTION_41Y { get; set; }
        
    /// <summary>
    ///4#缸孔截面2X
    /// </summary>
    public string DIA_SECTION_42X { get; set; }
        
    /// <summary>
    ///4#缸孔截面2Y
    /// </summary>
    public string DIA_SECTION_42Y { get; set; }
        
    /// <summary>
    ///4#缸孔截面3X
    /// </summary>
    public string DIA_SECTION_43X { get; set; }
        
    /// <summary>
    ///4#缸孔截面3Y
    /// </summary>
    public string DIA_SECTION_43Y { get; set; }
        
    /// <summary>
    ///4#缸孔截面1椭圆度
    /// </summary>
    public string DIA_SECTION_41OY { get; set; }
        
    /// <summary>
    ///4#缸孔截面2椭圆度
    /// </summary>
    public string DIA_SECTION_42OY { get; set; }
        
    /// <summary>
    ///4#缸孔截面3椭圆度
    /// </summary>
    public string DIA_SECTION_43OY { get; set; }
        
    /// <summary>
    ///4#缸孔X锥度
    /// </summary>
    public string DIA_TAPER_4X { get; set; }
        
    /// <summary>
    ///4#缸孔Y锥度
    /// </summary>
    public string DIA_TAPER_4Y { get; set; }
        
    /// <summary>
    ///工件温度TW
    /// </summary>
    public string WORK_TP_TM { get; set; }
        
    /// <summary>
    ///标准件温度TM
    /// </summary>
    public string STANDARD_TP_TM { get; set; }
        
    /// <summary>
    ///温度补偿量
    /// </summary>
    public string TEMPERATRUE_CT { get; set; }
        
    /// <summary>
    ///综合判定
    /// </summary>
    public string CT_JUDGE { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///部品工序信息ID
    /// </summary>
    public string PART_PROCESS_ID { get; set; }
        
    /// <summary>
    ///逻辑工序
    /// </summary>
    public string LOGIC_PROCESS { get; set; }
    }
}
