//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///审核参数保存表
    /// </summary>
    public partial class T_PQ_BU_PROJECT_CS
    {
        
    /// <summary>
    ///流程编码
    /// </summary>
    public string CODE_TYPE { get; set; }
        
    /// <summary>
    ///工厂
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///年月
    /// </summary>
    public string YEAR_MON { get; set; }
        
    /// <summary>
    ///判断是年还是月
    /// </summary>
    public string YEAR_NUM { get; set; }
    }
}
