//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///索赔金额总表
    /// </summary>
    public partial class T_PQ_BU_CLAIM_AMT_TOT
    {
        
    /// <summary>
    ///索赔金额总表ID
    /// </summary>
    public string CLAIM_AMT_TOT_ID { get; set; }
        
    /// <summary>
    ///责任单位类别
    /// </summary>
    public string DUTY_COMP_TYPE { get; set; }
        
    /// <summary>
    ///责任单位编码
    /// </summary>
    public string DUTY_COMP_CODE { get; set; }
        
    /// <summary>
    ///物料编码
    /// </summary>
    public string MATERIAL_CODE { get; set; }
        
    /// <summary>
    ///物料数量
    /// </summary>
    public decimal MATERIAL_QTY { get; set; }
        
    /// <summary>
    ///物料费用
    /// </summary>
    public decimal MATERIAL_FEE { get; set; }
        
    /// <summary>
    ///返修工时费用
    /// </summary>
    public decimal REWORK_WORK_FEE { get; set; }
        
    /// <summary>
    ///其它费用
    /// </summary>
    public decimal OTHER_FEE { get; set; }
        
    /// <summary>
    ///费用合计
    /// </summary>
    public decimal TOTAL_FEE { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///索赔月
    /// </summary>
    public string CLAIM_MON { get; set; }
        
    /// <summary>
    ///发送状态
    /// </summary>
    public string SEND_STATUS { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///物料名称
    /// </summary>
    public string MATERIAL_NAME { get; set; }
        
    /// <summary>
    ///工厂类型
    /// </summary>
    public string FACTORY_TYPE { get; set; }
        
    /// <summary>
    ///公司编码，值列表COMPANY
    /// </summary>
    public string COMP_CODE { get; set; }
        
    /// <summary>
    ///品牌编码，值列表CAR_BRAND
    /// </summary>
    public string BRAND_CODE { get; set; }
    }
}
