//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///保险立案供应商赔偿信息表
    /// </summary>
    public partial class T_PQ_BU_INSUR_SUP_INDEM
    {
        
    /// <summary>
    ///保险立案供应商赔偿信息ID
    /// </summary>
    public string INSUR_SUP_INDEM_ID { get; set; }
        
    /// <summary>
    ///供应商编码
    /// </summary>
    public string SUPPLIER_CODE { get; set; }
        
    /// <summary>
    ///索赔金额
    /// </summary>
    public decimal CLAIM_AMT { get; set; }
        
    /// <summary>
    ///赔偿金额
    /// </summary>
    public decimal INDEM_AMT { get; set; }
        
    /// <summary>
    ///赔偿比例
    /// </summary>
    public decimal INDEM_RATE { get; set; }
        
    /// <summary>
    ///检测费
    /// </summary>
    public decimal CHECK_FEE { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
    
        public virtual T_PQ_BU_INSUR_REGI T_PQ_BU_INSUR_REGI { get; set; }
    }
}
