//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///基础数据_其它测量点
    /// </summary>
    public partial class T_PQ_DB_BA_OTHER_MEAS
    {
        
    /// <summary>
    ///基础数据_其它测量点ID
    /// </summary>
    public string BA_OTHER_MEAS_ID { get; set; }
        
    /// <summary>
    ///测量点类型 枚举:建付;UCF;检具;内间隙
    /// </summary>
    public string TEST_POINT_TYPE { get; set; }
        
    /// <summary>
    ///车型编码 枚举:B12G;L12F;L12M
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///部位
    /// </summary>
    public string PART_POS { get; set; }
        
    /// <summary>
    ///位置ID
    /// </summary>
    public string POS_ID { get; set; }
        
    /// <summary>
    ///位置名称
    /// </summary>
    public string POS_NAME { get; set; }
        
    /// <summary>
    ///RL 枚举:RH;LH
    /// </summary>
    public string RL_VAL { get; set; }
        
    /// <summary>
    ///属性
    /// </summary>
    public string ATTRIBUTE_VAL { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///理论标准值
    /// </summary>
    public decimal THEORY_STAN_VAL { get; set; }
        
    /// <summary>
    ///检规-规格_+
    /// </summary>
    public decimal CHECK_SPEC_ADD { get; set; }
        
    /// <summary>
    ///检规-规格_-
    /// </summary>
    public decimal CHECK_SPEC_SUBTRA { get; set; }
        
    /// <summary>
    ///内规-规格_+
    /// </summary>
    public decimal INNER_SPEC_ADD { get; set; }
        
    /// <summary>
    ///内规-规格_-
    /// </summary>
    public decimal INNER_SPEC_SUBTRA { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
