//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///QIC质量异常处理单主表
    /// </summary>
    public partial class T_PQ_BU_QIC_EXCE_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PQ_BU_QIC_EXCE_M()
        {
            this.T_PQ_BU_QIC_EXCE_ATTA = new HashSet<T_PQ_BU_QIC_EXCE_ATTA>();
            this.T_PQ_BU_QIC_EXCE_EXP = new HashSet<T_PQ_BU_QIC_EXCE_EXP>();
            this.T_PQ_BU_QIC_EXCE_D_CTM = new HashSet<T_PQ_BU_QIC_EXCE_D_CTM>();
            this.T_PQ_BU_QIC_EXCE_D_HCFM = new HashSet<T_PQ_BU_QIC_EXCE_D_HCFM>();
        }
    
        
    /// <summary>
    ///QIC质量异常处理单主表ID
    /// </summary>
    public string QIC_EXCE_M_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///QIC单据类型
    /// </summary>
    public string QIC_BILL_TYPE { get; set; }
        
    /// <summary>
    ///QIC单号 以QIC开头+年月+5位
    /// </summary>
    public string QIC_CODE { get; set; }
        
    /// <summary>
    ///发行日期
    /// </summary>
    public System.DateTime DISTRI_DATE { get; set; }
        
    /// <summary>
    ///要求反馈日期
    /// </summary>
    public System.DateTime ASK_FEEDBACK_DATE { get; set; }
        
    /// <summary>
    ///车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///CCR编号
    /// </summary>
    public string CCR_CODE { get; set; }
        
    /// <summary>
    ///不良台数
    /// </summary>
    public int BAD_QTY { get; set; }
        
    /// <summary>
    ///重要度
    /// </summary>
    public string IMPORT_DEGREE { get; set; }
        
    /// <summary>
    ///责任单位
    /// </summary>
    public string PFP_SID { get; set; }
        
    /// <summary>
    ///专营店编码
    /// </summary>
    public string DLR_CODE { get; set; }
        
    /// <summary>
    ///下线日期
    /// </summary>
    public System.DateTime OFFLINE_DATE { get; set; }
        
    /// <summary>
    ///购车日期
    /// </summary>
    public System.DateTime BUY_CAR_DATE { get; set; }
        
    /// <summary>
    ///故障日期
    /// </summary>
    public System.DateTime FAULT_DATE { get; set; }
        
    /// <summary>
    ///里程
    /// </summary>
    public int MILAGE { get; set; }
        
    /// <summary>
    ///3个月内再发次数（原为：1年内再发次数）
    /// </summary>
    public decimal RESEND { get; set; }
        
    /// <summary>
    ///发现日期
    /// </summary>
    public System.DateTime FIND_DATE { get; set; }
        
    /// <summary>
    ///项目名称
    /// </summary>
    public string ITEM_NAME { get; set; }
        
    /// <summary>
    ///发现场所
    /// </summary>
    public string FIND_PLACE { get; set; }
        
    /// <summary>
    ///处置
    /// </summary>
    public string DEAL_DESC { get; set; }
        
    /// <summary>
    ///现场确认人
    /// </summary>
    public string LOCALE_CONF_MAN { get; set; }
        
    /// <summary>
    ///不良描述
    /// </summary>
    public string BAD_DESC { get; set; }
        
    /// <summary>
    ///初步推定原因
    /// </summary>
    public string PRELI_PRESUMP_REASON { get; set; }
        
    /// <summary>
    ///发生人
    /// </summary>
    public string HAP_MAN { get; set; }
        
    /// <summary>
    ///发生设备
    /// </summary>
    public string HAP_EQUIP { get; set; }
        
    /// <summary>
    ///发生物料
    /// </summary>
    public string HAP_MATERIAL { get; set; }
        
    /// <summary>
    ///发生方法
    /// </summary>
    public string HAP_METHOD { get; set; }
        
    /// <summary>
    ///发生环境
    /// </summary>
    public string HAP_ENVIRON { get; set; }
        
    /// <summary>
    ///流出人
    /// </summary>
    public string OUTFLOW_MAN { get; set; }
        
    /// <summary>
    ///流出设备
    /// </summary>
    public string OUTFLOW_EQUIP { get; set; }
        
    /// <summary>
    ///流出物料
    /// </summary>
    public string OUTFLOW_MATERIAL { get; set; }
        
    /// <summary>
    ///流出方法
    /// </summary>
    public string OUTFLOW_METHOD { get; set; }
        
    /// <summary>
    ///流出环境
    /// </summary>
    public string OUTFLOW_ENVIRON { get; set; }
        
    /// <summary>
    ///部品不良件零件号
    /// </summary>
    public string BAD_PART_CODE { get; set; }
        
    /// <summary>
    ///零件名称
    /// </summary>
    public string PART_NAME { get; set; }
        
    /// <summary>
    ///所属供应商
    /// </summary>
    public string BELONG_SUPPLIER { get; set; }
        
    /// <summary>
    ///暂定对策
    /// </summary>
    public string TEMP_CMS { get; set; }
        
    /// <summary>
    ///暂定对策车号
    /// </summary>
    public string TEN_CM_CAR_CODE { get; set; }
        
    /// <summary>
    ///暂定对策时间
    /// </summary>
    public System.DateTime TEN_CM_TIME { get; set; }
        
    /// <summary>
    ///恒久对策
    /// </summary>
    public string HAP_SEASON_CMS { get; set; }
        
    /// <summary>
    ///恒久对策车号
    /// </summary>
    public string PERM_CM_CAR_CODE { get; set; }
        
    /// <summary>
    ///发生原因对策（谁）
    /// </summary>
    public string HAP_REASON_CM_WHO { get; set; }
        
    /// <summary>
    ///发生原因对策（在哪里）
    /// </summary>
    public string HAP_REASON_CM_WHERE { get; set; }
        
    /// <summary>
    ///发生原因对策（做什么）
    /// </summary>
    public string HAP_REASON_CM_WHAT { get; set; }
        
    /// <summary>
    ///发生原因对策（怎么做）
    /// </summary>
    public string HAP_REASON_CM_HOW { get; set; }
        
    /// <summary>
    ///发生原因对策开始时间
    /// </summary>
    public System.DateTime HAP_REASON_CM_START_TIME { get; set; }
        
    /// <summary>
    ///发生原因对策完成时间
    /// </summary>
    public System.DateTime HAP_REASON_CM_END_TIME { get; set; }
        
    /// <summary>
    ///流出原因对策（谁）
    /// </summary>
    public string OUTFLOW_REASON_CM_WHO { get; set; }
        
    /// <summary>
    ///流出原因对策（在哪里）
    /// </summary>
    public string OUTFLOW_REASON_CM_WHERE { get; set; }
        
    /// <summary>
    ///流出原因对策（做什么）
    /// </summary>
    public string OUTFLOW_REASON_CM_WHAT { get; set; }
        
    /// <summary>
    ///流出原因对策（怎么做）
    /// </summary>
    public string OUTFLOW_REASON_CM_HOW { get; set; }
        
    /// <summary>
    ///流出原因对策开始时间
    /// </summary>
    public System.DateTime OUTFLOW_REASON_CM_START_TIME { get; set; }
        
    /// <summary>
    ///流出原因对策完成时间
    /// </summary>
    public System.DateTime OUTFLOW_REASON_CM_END_TIME { get; set; }
        
    /// <summary>
    ///对策起始VIN码或CCR号
    /// </summary>
    public string CM_BEGIN_VIN_CCR { get; set; }
        
    /// <summary>
    ///修改工程文件
    /// </summary>
    public string MODIFY_PROJ_FILE { get; set; }
        
    /// <summary>
    ///管理文件编号
    /// </summary>
    public string MANAGE_FILE_CODE { get; set; }
        
    /// <summary>
    ///管理文件完成日期
    /// </summary>
    public System.DateTime MANAGE_FILE_COMP_DATE { get; set; }
        
    /// <summary>
    ///检查文件编号
    /// </summary>
    public string CHECK_FILE_CODE { get; set; }
        
    /// <summary>
    ///检查文件完成日期
    /// </summary>
    public System.DateTime CHECK_FILE_COMP_DATE { get; set; }
        
    /// <summary>
    ///工程作业表编号
    /// </summary>
    public string PROJ_JOB_TAB_CODE { get; set; }
        
    /// <summary>
    ///工程作业表完成日期
    /// </summary>
    public System.DateTime PROJ_JOB_TAB_COMP_DATE { get; set; }
        
    /// <summary>
    ///标准作业书文件编号
    /// </summary>
    public string STAN_JOB_BOOK_FILE_CODE { get; set; }
        
    /// <summary>
    ///标准作业书完成日期
    /// </summary>
    public System.DateTime STAN_JOB_BOOK_COMP_CODE { get; set; }
        
    /// <summary>
    ///附件_追溯记录
    /// </summary>
    public string ATTA_TRACE_RECORD { get; set; }
        
    /// <summary>
    ///附件_解析说明
    /// </summary>
    public string ATTA_ANAL_DESC { get; set; }
        
    /// <summary>
    ///提请外单位协助事项
    /// </summary>
    public string DRAW_ASSI_ISSUE { get; set; }
        
    /// <summary>
    ///对策内容确认结论
    /// </summary>
    public string CM_CONT_C_RST { get; set; }
        
    /// <summary>
    ///对策效果确认结论
    /// </summary>
    public string CM_EFFE_C_RST { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///QIC质量异常处理单状态
    /// </summary>
    public string QIC_EXCE_STATUS { get; set; }
        
    /// <summary>
    ///恒久对策时间
    /// </summary>
    public System.DateTime PERM_CM_TIME { get; set; }
        
    /// <summary>
    ///提出单位
    /// </summary>
    public string APPLY_UNIT { get; set; }
        
    /// <summary>
    ///分流节点标记 0：没有分流节点完成；1：QIC发行工程师或系长确认通过；2：QIC发行工程师且系长确认通过；3：QIC回复工程师或系长确认通过；4：QIC回复工程师且系长确认通过；
    /// </summary>
    public string FLAG_DISTRIBUTARY { get; set; }
        
    /// <summary>
    ///二次结案发起计划日期
    /// </summary>
    public System.DateTime SEC_CLOSE_ISSSUE_PLAN_DATE { get; set; }
        
    /// <summary>
    ///对策内容确认
    /// </summary>
    public string CM_CONT_IS_OK { get; set; }
        
    /// <summary>
    ///对策效果确认
    /// </summary>
    public string CM_EFFE_IS_OK { get; set; }
        
    /// <summary>
    ///发生原因分类
    /// </summary>
    public string HAP_REASON_TYPE { get; set; }
        
    /// <summary>
    ///流出原因分类
    /// </summary>
    public string OUTFLOW_REASON_TYPE { get; set; }
        
    /// <summary>
    ///不良率
    /// </summary>
    public decimal BAD_RATE { get; set; }
        
    /// <summary>
    ///一次结案标准
    /// </summary>
    public string FST_CLOSE_STANDARD { get; set; }
        
    /// <summary>
    ///一次对策实施确认
    /// </summary>
    public string FST_CTM_IML_CFM { get; set; }
        
    /// <summary>
    ///一次对策效果确认
    /// </summary>
    public string FST_CTM_EFF_CFM { get; set; }
        
    /// <summary>
    ///一次结案结论
    /// </summary>
    public string FST_CLOSE_CONCLUSION { get; set; }
        
    /// <summary>
    ///二次结案标准
    /// </summary>
    public string SCD_CLOSE_STANDARD { get; set; }
        
    /// <summary>
    ///二次对策实施确认
    /// </summary>
    public string SCD_CTM_IML_CFM { get; set; }
        
    /// <summary>
    ///二次对策效果确认
    /// </summary>
    public string SCD_CTM_EFF_CFM { get; set; }
        
    /// <summary>
    ///二次结案结论
    /// </summary>
    public string SCD_CLOSE_CONCLUSION { get; set; }
        
    /// <summary>
    ///项目工位
    /// </summary>
    public string ITEM_DESC { get; set; }
        
    /// <summary>
    ///品情来源
    /// </summary>
    public string SOURCE_BIG_TYPE { get; set; }
        
    /// <summary>
    ///发现班组
    /// </summary>
    public string SOURCE_SMALL_TYPE { get; set; }
        
    /// <summary>
    ///水平共享工厂
    /// </summary>
    public string SHARE_FACTORY_CODE { get; set; }
        
    /// <summary>
    ///失效模式是否启动 失效模式是否启动(0：否；1：是)
    /// </summary>
    public string FMEA_START_STATUS { get; set; }
        
    /// <summary>
    ///要求结案日期
    /// </summary>
    public System.DateTime ASK_CLOSE_DATE { get; set; }
        
    /// <summary>
    ///实际结案日期
    /// </summary>
    public System.DateTime REAL_CLOSE_DATE { get; set; }
        
    /// <summary>
    ///担当是否反馈标志，0未反馈；1已反馈；2已反馈后驳回
    /// </summary>
    public string FLAG_FEEDBACK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_QIC_EXCE_ATTA> T_PQ_BU_QIC_EXCE_ATTA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_QIC_EXCE_EXP> T_PQ_BU_QIC_EXCE_EXP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_QIC_EXCE_D_CTM> T_PQ_BU_QIC_EXCE_D_CTM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_QIC_EXCE_D_HCFM> T_PQ_BU_QIC_EXCE_D_HCFM { get; set; }
    }
}
