//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///连杆加工信息表
    /// </summary>
    public partial class T_PQ_BU_CONN_ROD_PROC
    {
        
    /// <summary>
    ///连杆加工信息ID
    /// </summary>
    public string CONN_ROD_PROC_ID { get; set; }
        
    /// <summary>
    ///零件名称
    /// </summary>
    public string PART_NAME { get; set; }
        
    /// <summary>
    ///部品状态
    /// </summary>
    public string PART_STATUS { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///机种
    /// </summary>
    public string MAC_TYPE { get; set; }
        
    /// <summary>
    ///二维码
    /// </summary>
    public string QR_CODE { get; set; }
        
    /// <summary>
    ///上线工序
    /// </summary>
    public string ONLINE_PROCESS { get; set; }
        
    /// <summary>
    ///上线设备号
    /// </summary>
    public string ONLINE_EQUIP_CODE { get; set; }
        
    /// <summary>
    ///上线时间
    /// </summary>
    public System.DateTime ONLINE_TIME { get; set; }
        
    /// <summary>
    ///锻造装箱lot条形码
    /// </summary>
    public string FORGE_LOT_BAR_CODE { get; set; }
        
    /// <summary>
    ///上线状态
    /// </summary>
    public string ONLINE_STATUS { get; set; }
        
    /// <summary>
    ///大端油孔加工过机工序
    /// </summary>
    public string BIG_OIL_MAC_PROCESS { get; set; }
        
    /// <summary>
    ///大端油孔加工过机设备号
    /// </summary>
    public string BIG_OIL_MAC_EQUIP_CODE { get; set; }
        
    /// <summary>
    ///大端油孔加工过机时间
    /// </summary>
    public System.DateTime BIG_OIL_MAC_TIME { get; set; }
        
    /// <summary>
    ///大端油孔加工过机状态
    /// </summary>
    public string BIG_OIL_MAC_STATUS { get; set; }
        
    /// <summary>
    ///激光涨断过机工序
    /// </summary>
    public string LASER_MAC_PROCESS { get; set; }
        
    /// <summary>
    ///激光涨断过机设备号
    /// </summary>
    public string LASER_MAC_EQUIP_CODE { get; set; }
        
    /// <summary>
    ///激光涨断过机时间
    /// </summary>
    public System.DateTime LASER_MAC_TIME { get; set; }
        
    /// <summary>
    ///激光涨断过机状态
    /// </summary>
    public string LASER_MAC_STATUS { get; set; }
        
    /// <summary>
    ///精镗加工过机工序
    /// </summary>
    public string BORING_MAC_PROCESS { get; set; }
        
    /// <summary>
    ///精镗加工过机设备号
    /// </summary>
    public string BORING_MAC_EQUIP_CODE { get; set; }
        
    /// <summary>
    ///精镗加工过机时间
    /// </summary>
    public System.DateTime BORING_MAC_TIME { get; set; }
        
    /// <summary>
    ///精镗加工过机状态
    /// </summary>
    public string BORING_MAC_STATUS { get; set; }
        
    /// <summary>
    ///加工成品过最终测量机线工序
    /// </summary>
    public string PRO_FINAL_MEAS_PROCESS { get; set; }
        
    /// <summary>
    ///加工成品过最终测量机线设备号
    /// </summary>
    public string PRO_FINAL_MEAS_EQUIP_CODE { get; set; }
        
    /// <summary>
    ///加工成品过最终测量机线时间
    /// </summary>
    public System.DateTime PRO_FINAL_MEAS_TIME { get; set; }
        
    /// <summary>
    ///连杆成品二维码
    /// </summary>
    public string CONN_ROD_PROD_2D_CODE { get; set; }
        
    /// <summary>
    ///大端孔等级
    /// </summary>
    public string BIG_HOLE_LEVEL { get; set; }
        
    /// <summary>
    ///加工成品过最终测量机线状态
    /// </summary>
    public string PRO_FINAL_MEAS_STATUS { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///上线不良大类
    /// </summary>
    public string ON_BAD_B_TYPE { get; set; }
        
    /// <summary>
    ///大端油孔加工过机不良大类
    /// </summary>
    public string BIG_OIL_MAC_BAD_B_TYPE { get; set; }
        
    /// <summary>
    ///激光涨断过机不良大类
    /// </summary>
    public string LASER_MAC_BAD_B_TYPE { get; set; }
        
    /// <summary>
    ///精镗加工过机不良大类
    /// </summary>
    public string BORING_MAC_BAD_B_TYPE { get; set; }
        
    /// <summary>
    ///加工成品过最终测量机线不良大类
    /// </summary>
    public string PRO_FINAL_MEAS_BAD_B_TYPE { get; set; }
        
    /// <summary>
    ///零件编码
    /// </summary>
    public string PART_NO { get; set; }
        
    /// <summary>
    ///工厂名称
    /// </summary>
    public string FACTORY_NAME { get; set; }
    }
}
