//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///缺陷问题信息表
    /// </summary>
    public partial class T_PQ_BU_DEFECT_QUES_BAK_0422
    {
        
    /// <summary>
    ///缺陷问题信息表ID
    /// </summary>
    public string DEFECT_QUES_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///生产编号
    /// </summary>
    public string PROC_CODE { get; set; }
        
    /// <summary>
    ///管理编号
    /// </summary>
    public string MANAGE_CODE { get; set; }
        
    /// <summary>
    ///车型
    /// </summary>
    public string CAR_TYPE { get; set; }
        
    /// <summary>
    ///颜色
    /// </summary>
    public string CAR_COLOR { get; set; }
        
    /// <summary>
    ///发动机号
    /// </summary>
    public string ENGINE_NO { get; set; }
        
    /// <summary>
    ///车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///下线日期
    /// </summary>
    public System.DateTime OFFLINE_DATE { get; set; }
        
    /// <summary>
    ///车型配置
    /// </summary>
    public string CAR_CONFIG { get; set; }
        
    /// <summary>
    ///18位码
    /// </summary>
    public string EIGTEEN_CODE { get; set; }
        
    /// <summary>
    ///用户类型
    /// </summary>
    public string USER_TYPE { get; set; }
        
    /// <summary>
    ///其他描述
    /// </summary>
    public string OTHER_DESC { get; set; }
        
    /// <summary>
    ///不良现象图片
    /// </summary>
    public string BAD_PHE_PIC { get; set; }
        
    /// <summary>
    ///级别
    /// </summary>
    public string LEVEL_VAL { get; set; }
        
    /// <summary>
    ///责任单位
    /// </summary>
    public string PFP_SID { get; set; }
        
    /// <summary>
    ///是否申告
    /// </summary>
    public string IS_CLAIM { get; set; }
        
    /// <summary>
    ///是否弹出
    /// </summary>
    public string IS_POP_UP { get; set; }
        
    /// <summary>
    ///录入时间
    /// </summary>
    public System.DateTime OPER_DATE { get; set; }
        
    /// <summary>
    ///录入人员
    /// </summary>
    public string ENTRY_CLERK { get; set; }
        
    /// <summary>
    ///班组编码
    /// </summary>
    public string TEAM_CODE { get; set; }
        
    /// <summary>
    ///班别
    /// </summary>
    public string SCHEDULE_TYPE { get; set; }
        
    /// <summary>
    ///零件1
    /// </summary>
    public string PART_1 { get; set; }
        
    /// <summary>
    ///零件2
    /// </summary>
    public string PART_2 { get; set; }
        
    /// <summary>
    ///位置/状态
    /// </summary>
    public string POS_STATUS { get; set; }
        
    /// <summary>
    ///缺陷
    /// </summary>
    public string DEFECT_VAL { get; set; }
        
    /// <summary>
    ///不良描述
    /// </summary>
    public string BAD_DESC { get; set; }
        
    /// <summary>
    ///状态
    /// </summary>
    public string STATUS { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///车间编码
    /// </summary>
    public string WORKSHOP_CODE { get; set; }
        
    /// <summary>
    ///ONLINE_DISTINCT
    /// </summary>
    public string ONLINE_DISTINCT { get; set; }
        
    /// <summary>
    ///责任变更信息表ID,关联T_PQ_BU_REJ_DUTY_CHAN的表主键ID字段
    /// </summary>
    public string REJ_DUTY_CHAN_ID { get; set; }
        
    /// <summary>
    ///指定件旧责任单位:保存变更后老的责任单位,数据来源为同表的PFP_SID字段,值为空白表示责任单位无变化
    /// </summary>
    public string DESI_PART_NEW_UNIT { get; set; }
        
    /// <summary>
    ///是否待部长审核,值列表BU_MINI_AUD_TYPE
    /// </summary>
    public string IF_MINI_AUD { get; set; }
    }
}
