//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///真空加注设备-冷媒数据表
    /// </summary>
    public partial class T_PQ_BU_VACUUM_FILL_COLD
    {
        
    /// <summary>
    ///真空加注设备-冷媒数据ID
    /// </summary>
    public string VACUUM_FILL_COLD_ID { get; set; }
        
    /// <summary>
    ///测量时间
    /// </summary>
    public System.DateTime MEASURE_DATE { get; set; }
        
    /// <summary>
    ///测量人
    /// </summary>
    public string MEASURE_MAN { get; set; }
        
    /// <summary>
    ///设备编码
    /// </summary>
    public string EQUIP_CODE { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///车间编码
    /// </summary>
    public string WORKSHOP_CODE { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///CCR编号
    /// </summary>
    public string CCR_CODE { get; set; }
        
    /// <summary>
    ///18位码
    /// </summary>
    public string EIGTEEN_CODE { get; set; }
        
    /// <summary>
    ///标准值
    /// </summary>
    public long STAN_VAL { get; set; }
        
    /// <summary>
    ///1次真空
    /// </summary>
    public long VACUUM_ONE { get; set; }
        
    /// <summary>
    ///2次真空
    /// </summary>
    public long VACUUM_TWO { get; set; }
        
    /// <summary>
    ///AC总加注量
    /// </summary>
    public long AC_TOT_FILL_QTY { get; set; }
        
    /// <summary>
    ///左右侧
    /// </summary>
    public string LR_SIDE { get; set; }
        
    /// <summary>
    ///液体温度
    /// </summary>
    public decimal LIQUID_TEMP { get; set; }
        
    /// <summary>
    ///1次真空异常
    /// </summary>
    public string VACUUM_ONE_ABN { get; set; }
        
    /// <summary>
    ///2次真空异常
    /// </summary>
    public string VACUUM_TWO_ABN { get; set; }
        
    /// <summary>
    ///测漏异常
    /// </summary>
    public string MEAS_LEAK_ABN { get; set; }
        
    /// <summary>
    ///加注时间超过
    /// </summary>
    public string FILL_TIME_MORE { get; set; }
        
    /// <summary>
    ///加注异常
    /// </summary>
    public string FILL_ABN { get; set; }
        
    /// <summary>
    ///加注量异常
    /// </summary>
    public string FILL_QTY_ABN { get; set; }
        
    /// <summary>
    ///周边气压hpa
    /// </summary>
    public decimal SURR_AIR_PRESSURE { get; set; }
        
    /// <summary>
    ///周边温度℃ 
    /// </summary>
    public decimal SURR_TEMP { get; set; }
        
    /// <summary>
    ///周边湿度%  
    /// </summary>
    public decimal SURR_HUMIDITY { get; set; }
        
    /// <summary>
    ///真空泵温度台车℃   
    /// </summary>
    public decimal VACUUM_PUMP_TEMP_CAR { get; set; }
        
    /// <summary>
    ///真空泵电流台车Ams 
    /// </summary>
    public decimal VACUUM_PUMP_CURR_CAR { get; set; }
        
    /// <summary>
    ///真空泵振动台车Hz  
    /// </summary>
    public decimal VACUUM_PUMP_VIBRATE_CAR { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///右真空泵温度台车℃
    /// </summary>
    public decimal Y_VACUUM_PUMP_TEMP_CAR { get; set; }
        
    /// <summary>
    ///右真空泵电流台车Ams
    /// </summary>
    public decimal Y_VACUUM_PUMP_CURR_CAR { get; set; }
        
    /// <summary>
    ///右真空泵振动台车Hz
    /// </summary>
    public decimal Y_VACUUM_PUMP_VIBRATE_CAR { get; set; }
    }
}
