//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///UCF测量数据表
    /// </summary>
    public partial class T_PQ_BU_UCF_MEASURE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PQ_BU_UCF_MEASURE()
        {
            this.T_PQ_BU_UCF_MEASURE_D = new HashSet<T_PQ_BU_UCF_MEASURE_D>();
        }
    
        
    /// <summary>
    ///UCF测量数据表ID
    /// </summary>
    public string UCF_MEASURE_ID { get; set; }
        
    /// <summary>
    ///日期
    /// </summary>
    public System.DateTime DATE_VAL { get; set; }
        
    /// <summary>
    ///测量人
    /// </summary>
    public string MEASURE_MAN { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///车型编码 枚举:B12G;L12F;L12M
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///部位 枚举:发动机盖;行李箱盖;右前门;右后门
    /// </summary>
    public string PART_POS { get; set; }
        
    /// <summary>
    ///内板夹具
    /// </summary>
    public string PLATE_CLAMP { get; set; }
        
    /// <summary>
    ///包边模编号 枚举:#130;#140
    /// </summary>
    public string PACK_MODEL_CODE { get; set; }
        
    /// <summary>
    ///测量基准 枚举:铰链基准;内板基准
    /// </summary>
    public string MEASURE_BASE { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///班别
    /// </summary>
    public string SCHEDULE_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_UCF_MEASURE_D> T_PQ_BU_UCF_MEASURE_D { get; set; }
    }
}
