//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///方向盘角度测量数据表
    /// </summary>
    public partial class T_PQ_BU_STEER_WHEEL_MEAS
    {
        
    /// <summary>
    ///方向盘角度测量数据ID
    /// </summary>
    public string STEER_WHEEL_MEAS_ID { get; set; }
        
    /// <summary>
    ///测量时间
    /// </summary>
    public System.DateTime MEASURE_DATE { get; set; }
        
    /// <summary>
    ///测量人
    /// </summary>
    public string MEASURE_MAN { get; set; }
        
    /// <summary>
    ///设备编码
    /// </summary>
    public string EQUIP_CODE { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///车间编码
    /// </summary>
    public string WORKSHOP_CODE { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///CCR编号
    /// </summary>
    public string CCR_CODE { get; set; }
        
    /// <summary>
    ///SPEC
    /// </summary>
    public string SPEC { get; set; }
        
    /// <summary>
    ///CHASSIS
    /// </summary>
    public string CHASSIS { get; set; }
        
    /// <summary>
    ///BODY
    /// </summary>
    public string BODY { get; set; }
        
    /// <summary>
    ///ENG
    /// </summary>
    public string ENG { get; set; }
        
    /// <summary>
    ///AXLE
    /// </summary>
    public string AXLE { get; set; }
        
    /// <summary>
    ///HANDLE
    /// </summary>
    public string HANDLE { get; set; }
        
    /// <summary>
    ///GRADE
    /// </summary>
    public string GRADE { get; set; }
        
    /// <summary>
    ///TRANS
    /// </summary>
    public string TRANS { get; set; }
        
    /// <summary>
    ///MODEL
    /// </summary>
    public string MODEL_NO { get; set; }
        
    /// <summary>
    ///FUEL
    /// </summary>
    public string FUEL { get; set; }
        
    /// <summary>
    ///ZONE
    /// </summary>
    public string ZONE { get; set; }
        
    /// <summary>
    ///EQUIP
    /// </summary>
    public string EQUIP { get; set; }
        
    /// <summary>
    ///OPTION
    /// </summary>
    public string OPTION_DESC { get; set; }
        
    /// <summary>
    ///JUDGE
    /// </summary>
    public string JUDGE { get; set; }
        
    /// <summary>
    ///ANGLE_AVE
    /// </summary>
    public decimal ANGLE_AVE { get; set; }
        
    /// <summary>
    ///ANGLE_MAX
    /// </summary>
    public decimal ANGLE_MAX { get; set; }
        
    /// <summary>
    ///ANGLE_MIN
    /// </summary>
    public decimal ANGLE_MIN { get; set; }
        
    /// <summary>
    ///ANGLE_ID
    /// </summary>
    public string ANGLE_ID { get; set; }
        
    /// <summary>
    ///TILT_ANGLE
    /// </summary>
    public decimal TILT_ANGLE { get; set; }
        
    /// <summary>
    ///JUDGE_MAX
    /// </summary>
    public decimal JUDGE_MAX { get; set; }
        
    /// <summary>
    ///JUDGE_MIN
    /// </summary>
    public decimal JUDGE_MIN { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///测量风速
    /// </summary>
    public decimal MEAS_WIND_SPEED { get; set; }
        
    /// <summary>
    ///测量路面
    /// </summary>
    public string MEAS_ROAD { get; set; }
        
    /// <summary>
    ///测量一次
    /// </summary>
    public decimal MEAS_ONE_TIMES { get; set; }
        
    /// <summary>
    ///测量二次
    /// </summary>
    public decimal MEAS_TWO_TIMES { get; set; }
        
    /// <summary>
    ///测量三次
    /// </summary>
    public decimal MEAS_THR_TIMES { get; set; }
        
    /// <summary>
    ///胎压
    /// </summary>
    public string TIRE_PRES { get; set; }
        
    /// <summary>
    ///数据来源 默认为0 0为接口数据 1为数据维护
    /// </summary>
    public string DATA_SOURCE { get; set; }
    }
}
