//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///基础数据_检测部位表
    /// </summary>
    public partial class T_PQ_DB_BA_PART_MEAS
    {
        
    /// <summary>
    ///基础数据_检测部位表ID
    /// </summary>
    public string BA_PART_MEAS_ID { get; set; }
        
    /// <summary>
    ///检测类型
    /// </summary>
    public string TEST_TYPE { get; set; }
        
    /// <summary>
    ///车型编码 枚举:B12G;L12F;L12M
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///部位
    /// </summary>
    public string PART_POS { get; set; }
        
    /// <summary>
    ///示意图路径
    /// </summary>
    public string SKETCH_PATH { get; set; }
        
    /// <summary>
    ///属性1
    /// </summary>
    public string ATTRIBUTE1 { get; set; }
        
    /// <summary>
    ///属性2
    /// </summary>
    public string ATTRIBUTE2 { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///模板路径
    /// </summary>
    public string TEMPLATE_PATH { get; set; }
        
    /// <summary>
    ///部位ID
    /// </summary>
    public string PART_POS_ID { get; set; }
        
    /// <summary>
    ///工程分类（1：冲焊；2：涂树）
    /// </summary>
    public string MAIN_TYPE { get; set; }
    }
}
