//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///预警规则表
    /// </summary>
    public partial class T_PQ_DB_ALERT_RULE
    {
        
    /// <summary>
    ///预警规则表ID
    /// </summary>
    public string ALERT_RULE_ID { get; set; }
        
    /// <summary>
    ///规则ID
    /// </summary>
    public string RULE_ID { get; set; }
        
    /// <summary>
    ///用户ID
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///预警标题
    /// </summary>
    public string ALTER_TITLE_NAME { get; set; }
        
    /// <summary>
    ///品情来源
    /// </summary>
    public string SOURCE_DEPT { get; set; }
        
    /// <summary>
    ///车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///不良现象
    /// </summary>
    public string BAD_PHE { get; set; }
        
    /// <summary>
    ///级别
    /// </summary>
    public string LEVEL_VAL { get; set; }
        
    /// <summary>
    ///责任单位
    /// </summary>
    public string PFP_SID { get; set; }
        
    /// <summary>
    ///预警条数
    /// </summary>
    public int ALERT_NUM { get; set; }
        
    /// <summary>
    ///当日累计大于
    /// </summary>
    public decimal DAY_GREATER { get; set; }
        
    /// <summary>
    ///缺陷名称
    /// </summary>
    public string DEFECT_NAME { get; set; }
        
    /// <summary>
    ///缺陷ID
    /// </summary>
    public string DEFECT_ID { get; set; }
        
    /// <summary>
    ///数据范围（天）
    /// </summary>
    public decimal DATA_RANGE_DAY { get; set; }
        
    /// <summary>
    ///数据刷新时间（秒）
    /// </summary>
    public decimal DATA_REFRESH_TIME_SEC { get; set; }
        
    /// <summary>
    ///图片切换间隔（秒)
    /// </summary>
    public decimal PIC_SWITCH_INTERVAL_SEC { get; set; }
        
    /// <summary>
    ///班次
    /// </summary>
    public string CLASS_TIMES { get; set; }
        
    /// <summary>
    ///问题关联图显示在右边
    /// </summary>
    public string QUES_PIC_RIGHT { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///录入车间
    /// </summary>
    public string WORKSHOP { get; set; }
        
    /// <summary>
    ///排序规则
    /// </summary>
    public string ORDER_RULE { get; set; }
        
    /// <summary>
    ///TEAMCODE
    /// </summary>
    public string TEAMCODE { get; set; }
        
    /// <summary>
    ///不良率车型
    /// </summary>
    public string CAR_TYPE_CODE_UNHEALTHY { get; set; }
        
    /// <summary>
    ///VES模式(1:模式1,2:模式2)
    /// </summary>
    public decimal VES_SHOWTYPE { get; set; }
        
    /// <summary>
    ///前几组数(按小时推移)
    /// </summary>
    public decimal PRE_GROUPS_HOUR { get; set; }
        
    /// <summary>
    ///前几组数(按日推移)
    /// </summary>
    public decimal PRE_GROUPS_DAY { get; set; }
        
    /// <summary>
    ///显示方式(不良提醒)(1:全部显示;2:隐藏上部分;3:隐藏下部分;4:隐藏上下部分)
    /// </summary>
    public decimal CAR_SHOWTYPE { get; set; }
        
    /// <summary>
    ///目标值车型(小时推移)
    /// </summary>
    public string SEL_TARGET_CARTYPE_HOUR { get; set; }
        
    /// <summary>
    ///目标值车辆(月推移)
    /// </summary>
    public string SEL_TARGET_CARTYPE_DAY { get; set; }
        
    /// <summary>
    ///柱图渐变颜色
    /// </summary>
    public string GRADIENTCOLOR { get; set; }
    }
}
