//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///生产实际信息
    /// </summary>
    public partial class T_PQ_BU_PRODUCT_ACTU
    {
        
    /// <summary>
    ///生产实际信息ID
    /// </summary>
    public string PRODUCT_ACTU_ID { get; set; }
        
    /// <summary>
    ///车间编码
    /// </summary>
    public string WORKSHOP_CODE { get; set; }
        
    /// <summary>
    ///车间名称
    /// </summary>
    public string WORKSHOP_NAME { get; set; }
        
    /// <summary>
    ///生产序号
    /// </summary>
    public string PRODUCE_SERIAL_NUM { get; set; }
        
    /// <summary>
    ///生产批次
    /// </summary>
    public string PRODUCE_BATCH_CODE { get; set; }
        
    /// <summary>
    ///发动机号
    /// </summary>
    public string ENGINE_NO { get; set; }
        
    /// <summary>
    ///零件编码
    /// </summary>
    public string PART_NO { get; set; }
        
    /// <summary>
    ///零件名称
    /// </summary>
    public string PART_NAME { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///零部件条码
    /// </summary>
    public string PART_BAR_CODE { get; set; }
        
    /// <summary>
    ///负责人
    /// </summary>
    public string PRINCIPAL_MAN { get; set; }
        
    /// <summary>
    ///生产日期
    /// </summary>
    public System.DateTime PRODUCE_DATE { get; set; }
        
    /// <summary>
    ///生产数量
    /// </summary>
    public int PRODUCE_QTY { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
