//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///HD空车位业务表
    /// </summary>
    public partial class T_PQ_BU_EMPTY_CARPORT
    {
        
    /// <summary>
    ///空车位ID
    /// </summary>
    public string EMPTY_CARPORT_ID { get; set; }
        
    /// <summary>
    ///空车位编码
    ///AAA为空车位编码
    /// </summary>
    public string EMPTY_CODE { get; set; }
        
    /// <summary>
    ///总装连续编号
    ///循环使用
    /// </summary>
    public string TRIM_SERIAL_NO { get; set; }
        
    /// <summary>
    ///管理编号
    /// </summary>
    public string CTRLKEY { get; set; }
        
    /// <summary>
    ///接受时间
    /// </summary>
    public string RECEIVE_DATE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///是否空车位，0非空，1空
    /// </summary>
    public string IS_EMPTY { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///焊装下线日期
    /// </summary>
    public System.DateTime HZ_OUT_TIME { get; set; }
        
    /// <summary>
    ///涂装下线日期
    /// </summary>
    public System.DateTime TZ_OUT_TIME { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///一连号
    /// </summary>
    public string SERIAL_CODE { get; set; }
        
    /// <summary>
    ///PBS OUT
    /// </summary>
    public System.DateTime PBS_OUT_TIME { get; set; }
    }
}
