//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///检出率、判定率目标数据表
    /// </summary>
    public partial class T_PQ_BU_CHECK_JUG_TAR
    {
        
    /// <summary>
    ///检出率、判定率目标数据表ID
    /// </summary>
    public string CHECK_JUG_TAR_ID { get; set; }
        
    /// <summary>
    ///类型（1：检出率、2：判定率）
    /// </summary>
    public string TYPE_VAL { get; set; }
        
    /// <summary>
    ///目标值
    /// </summary>
    public decimal TAR_VAL { get; set; }
        
    /// <summary>
    ///年份
    /// </summary>
    public short YEAR_VAL { get; set; }
        
    /// <summary>
    ///月份
    /// </summary>
    public byte MONTH_VAL { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///工厂编码（SAP_FACTORY_CODE）
    /// </summary>
    public string FACTORY_CODE { get; set; }
    }
}
