//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///监查问题表
    /// </summary>
    public partial class T_PQ_BU_MONITOR_PROBLEM
    {
        
    /// <summary>
    ///监查问题表ID
    /// </summary>
    public string MONITOR_PROBLEM_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///车间编码 枚举:冲压;焊装;涂装;树脂;总装
    /// </summary>
    public string WORKSHOP_CODE { get; set; }
        
    /// <summary>
    ///班别
    /// </summary>
    public string SCHEDULE_TYPE { get; set; }
        
    /// <summary>
    ///检查时间
    /// </summary>
    public System.DateTime CHECK_TIME { get; set; }
        
    /// <summary>
    ///监查项目
    /// </summary>
    public string INSPECT_ITEM { get; set; }
        
    /// <summary>
    ///检查员
    /// </summary>
    public string CHECK_MAN { get; set; }
        
    /// <summary>
    ///车型编码 枚举:B12G;L12F;L12M
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///不良描述
    /// </summary>
    public string BAD_DESC { get; set; }
        
    /// <summary>
    ///等级 枚举:V1+;V1;V2;V3
    /// </summary>
    public string CLASS_VAL { get; set; }
        
    /// <summary>
    ///责任单位
    /// </summary>
    public string PFP_SID { get; set; }
        
    /// <summary>
    ///品情确认人
    /// </summary>
    public string PROD_CONF_MAN { get; set; }
        
    /// <summary>
    ///不良台数
    /// </summary>
    public int BAD_QTY { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///班组编码
    /// </summary>
    public string TEAM_CODE { get; set; }
    }
}
