//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///申诉分类表
    /// </summary>
    public partial class T_PQ_BU_APPEAL_TYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PQ_BU_APPEAL_TYPE()
        {
            this.T_PQ_BU_APP_TYPE_REJ_BILL = new HashSet<T_PQ_BU_APP_TYPE_REJ_BILL>();
        }
    
        
    /// <summary>
    ///申诉分类ID
    /// </summary>
    public string APPEAL_TYPE_ID { get; set; }
        
    /// <summary>
    ///申诉分类
    /// </summary>
    public string APPEAL_SORT { get; set; }
        
    /// <summary>
    ///申诉内容
    /// </summary>
    public string APPEAL_PROCESS_CONT { get; set; }
        
    /// <summary>
    ///解析结果
    /// </summary>
    public string RESOLVE_RESULT { get; set; }
        
    /// <summary>
    ///申诉附件
    /// </summary>
    public string APPEAL_ATTACHMENT { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///申诉序号
    /// </summary>
    public string APPEAL_SEQ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_APP_TYPE_REJ_BILL> T_PQ_BU_APP_TYPE_REJ_BILL { get; set; }
        public virtual T_PQ_BU_APPEAL_ORDER T_PQ_BU_APPEAL_ORDER { get; set; }
    }
}
