//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///联合色差测量主表
    /// </summary>
    public partial class T_PQ_BU_COMB_COLOR_MEAS_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PQ_BU_COMB_COLOR_MEAS_M()
        {
            this.T_PQ_BU_COMB_COLOR_MEAS_D = new HashSet<T_PQ_BU_COMB_COLOR_MEAS_D>();
        }
    
        
    /// <summary>
    ///联合色差测量主表ID
    /// </summary>
    public string COMB_COLOR_MEAS_M_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///测量日期
    /// </summary>
    public System.DateTime MEASURE_DATE { get; set; }
        
    /// <summary>
    ///车型编码 枚举:B12G;L12F;L12M
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///车色代码 枚举:QX1;KBD
    /// </summary>
    public string CAR_COLOR_CODE { get; set; }
        
    /// <summary>
    ///车间编码 枚举:涂二车间
    /// </summary>
    public string WORKSHOP_CODE { get; set; }
        
    /// <summary>
    ///生产线编码 枚举:面漆一线;面漆二线
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///整车检查员
    /// </summary>
    public string VE_CHECK_MAN { get; set; }
        
    /// <summary>
    ///涂装检查员
    /// </summary>
    public string PAINT_CHECK_MAN { get; set; }
        
    /// <summary>
    ///技术科
    /// </summary>
    public string TECH_SEC { get; set; }
        
    /// <summary>
    ///BASF
    /// </summary>
    public string BASF_VAL { get; set; }
        
    /// <summary>
    ///联合结论
    /// </summary>
    public string JOINT_RST { get; set; }
        
    /// <summary>
    ///技术调整方案
    /// </summary>
    public string TECH_ADJUST_SCHEME { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///联测类型 1:室内;2:室外
    /// </summary>
    public string CT_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_COMB_COLOR_MEAS_D> T_PQ_BU_COMB_COLOR_MEAS_D { get; set; }
    }
}
