//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///检测点位导入表
    /// </summary>
    public partial class T_PQ_BU_POINT_IMP
    {
        
    /// <summary>
    ///检测点位导入表ID
    /// </summary>
    public string POINT_IMP_ID { get; set; }
        
    /// <summary>
    ///车型
    /// </summary>
    public string CAR_TYPE { get; set; }
        
    /// <summary>
    ///位置ID
    /// </summary>
    public string POS_ID { get; set; }
        
    /// <summary>
    ///位置名称
    /// </summary>
    public string POS_NAME { get; set; }
        
    /// <summary>
    ///RL
    /// </summary>
    public string RL_VAL { get; set; }
        
    /// <summary>
    ///方向
    /// </summary>
    public string DIRECTION { get; set; }
        
    /// <summary>
    ///属性
    /// </summary>
    public string ATTRIBUTE_VAL { get; set; }
        
    /// <summary>
    ///影响对象_主要
    /// </summary>
    public string AFFECT_OBJ_MAIN { get; set; }
        
    /// <summary>
    ///影响对象_次要
    /// </summary>
    public string AFFECT_OBJ_SEC { get; set; }
        
    /// <summary>
    ///理论标准值
    /// </summary>
    public decimal THEORY_STAN_VAL { get; set; }
        
    /// <summary>
    ///检规-规格_+
    /// </summary>
    public decimal CHECK_SPEC_ADD { get; set; }
        
    /// <summary>
    ///检规-规格_-
    /// </summary>
    public decimal CHECK_SPEC_SUBTRA { get; set; }
        
    /// <summary>
    ///内规-规格_+
    /// </summary>
    public decimal INNER_SPEC_ADD { get; set; }
        
    /// <summary>
    ///内规-规格_-
    /// </summary>
    public decimal INNER_SPEC_SUBTRA { get; set; }
        
    /// <summary>
    ///所属零件_零件号
    /// </summary>
    public string BELONG_PART_CODE { get; set; }
        
    /// <summary>
    ///所属零件_零件名
    /// </summary>
    public string BELONG_PART_NAME { get; set; }
        
    /// <summary>
    ///所属零件_供应商
    /// </summary>
    public string BELONG_PART_SUPPLIER { get; set; }
        
    /// <summary>
    ///管理班组
    /// </summary>
    public string MANAGE_TEAM { get; set; }
        
    /// <summary>
    ///夹具管理_夹具名称
    /// </summary>
    public string CLAMP_MANGE_CLAMP_NAME { get; set; }
        
    /// <summary>
    ///夹具管理_管理单元
    /// </summary>
    public string CLAMP_MANGE_MANGE_UNIT { get; set; }
        
    /// <summary>
    ///类型
    /// </summary>
    public string TYPE { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///理论标准值2
    /// </summary>
    public decimal THEORY_STAN_VAL2 { get; set; }
        
    /// <summary>
    ///检规-规格_+2
    /// </summary>
    public decimal CHECK_SPEC_ADD2 { get; set; }
        
    /// <summary>
    ///检规-规格_-2
    /// </summary>
    public decimal CHECK_SPEC_SUBTRA2 { get; set; }
        
    /// <summary>
    ///内规-规格_+2
    /// </summary>
    public decimal INNER_SPEC_ADD2 { get; set; }
        
    /// <summary>
    ///内规-规格_-2
    /// </summary>
    public decimal INNER_SPEC_SUBTRA2 { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///导入批次号
    /// </summary>
    public string BATCHNO { get; set; }
        
    /// <summary>
    ///错误信息
    /// </summary>
    public string ERR_MSG { get; set; }
        
    /// <summary>
    ///序号
    /// </summary>
    public decimal ORDER_NO { get; set; }
    }
}
