//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///装配批次管理信息表
    /// </summary>
    public partial class T_PQ_BU_ASSE_BAT_MANA
    {
        
    /// <summary>
    ///装配批次管理信息ID
    /// </summary>
    public string ASSE_BAT_MANA_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///接收时间
    /// </summary>
    public System.DateTime RECEIVE_TIME { get; set; }
        
    /// <summary>
    ///发动机号
    /// </summary>
    public string ENGINE_NO { get; set; }
        
    /// <summary>
    ///零件编码
    /// </summary>
    public string PART_NO { get; set; }
        
    /// <summary>
    ///Head 2D码
    /// </summary>
    public string HEAD_2D_CODE { get; set; }
        
    /// <summary>
    ///Block 2D码
    /// </summary>
    public string BLOCK_2D_CODE { get; set; }
        
    /// <summary>
    ///曲轴2D码
    /// </summary>
    public string CRANKSHAFT_2D_CODE { get; set; }
        
    /// <summary>
    ///凸轮轴2D码
    /// </summary>
    public string CAMSHAFT_2D_CODE { get; set; }
        
    /// <summary>
    ///连杆2D码
    /// </summary>
    public string CONN_ROD_2D_CODE { get; set; }
        
    /// <summary>
    ///缸体Jr等级
    /// </summary>
    public string CYLINDER_JR_GRADE { get; set; }
        
    /// <summary>
    ///曲轴JrPIN等级
    /// </summary>
    public string CRANKSHAFT_JRPIN_GRADE { get; set; }
        
    /// <summary>
    ///主轴瓦等级
    /// </summary>
    public string MAIN_SHAFT_TILE_GRADE { get; set; }
        
    /// <summary>
    ///连杆瓦等级
    /// </summary>
    public string CONNECTING_ROD_GRADE { get; set; }
        
    /// <summary>
    ///活塞等级
    /// </summary>
    public string PISTON_GRADE { get; set; }
        
    /// <summary>
    ///喷油器批次
    /// </summary>
    public string INJECTOR_BATCH { get; set; }
        
    /// <summary>
    ///燃油管批次
    /// </summary>
    public string FUEL_PIPE_BATCH { get; set; }
        
    /// <summary>
    ///飞轮批次
    /// </summary>
    public string FLYWHEEL_BATCH { get; set; }
        
    /// <summary>
    ///压盘
    /// </summary>
    public string PRESSURE_PLATE { get; set; }
        
    /// <summary>
    ///机油泵
    /// </summary>
    public string OIL_PUMP { get; set; }
        
    /// <summary>
    ///节气门
    /// </summary>
    public string SAVE_GAS_DOOR { get; set; }
        
    /// <summary>
    ///出水管
    /// </summary>
    public string OUTLET_PIPE { get; set; }
        
    /// <summary>
    ///水泵
    /// </summary>
    public string WATER_PUMP { get; set; }
        
    /// <summary>
    ///点火线圈
    /// </summary>
    public string IGNITION_COIL { get; set; }
        
    /// <summary>
    ///正时链条
    /// </summary>
    public string TIMING_CHAIN { get; set; }
        
    /// <summary>
    ///氧传感器
    /// </summary>
    public string OXYGEN_SENSOR { get; set; }
        
    /// <summary>
    ///涨紧器
    /// </summary>
    public string RISE_TIGHT_DEVICE { get; set; }
        
    /// <summary>
    ///活塞环
    /// </summary>
    public string PISTON_RING { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///工厂名称
    /// </summary>
    public string FACTORY_NAME { get; set; }
    }
}
