//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///QIC趋势数据导入表
    /// </summary>
    public partial class T_PQ_BU_QIC_TREND_IMP
    {
        
    /// <summary>
    ///QIC趋势数据导入表ID
    /// </summary>
    public string QIC_TREND_IMP_ID { get; set; }
        
    /// <summary>
    ///趋势日期
    /// </summary>
    public string QIC_TREND_DATE { get; set; }
        
    /// <summary>
    ///趋势分子
    /// </summary>
    public string QIC_TREND_M { get; set; }
        
    /// <summary>
    ///趋势分母
    /// </summary>
    public string QIC_TREND_D { get; set; }
        
    /// <summary>
    ///趋势百分比
    /// </summary>
    public string QIC_TREND_P { get; set; }
        
    /// <summary>
    ///QIC趋势数据类型：1-发行 2-一次结案 3-二次结案
    /// </summary>
    public string QIC_TREND_TYPE { get; set; }
        
    /// <summary>
    ///QIC单号
    /// </summary>
    public string QIC_CODE { get; set; }
        
    /// <summary>
    ///QIC趋势数据导入错误信息
    /// </summary>
    public string ERR_MSG { get; set; }
        
    /// <summary>
    ///QIC趋势数据导入批次号
    /// </summary>
    public string BATCHNO { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
