//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///T_PQ_BU_CAM_P_MEAS_TEMP
    /// </summary>
    public partial class T_PQ_BU_CAM_P_MEAS_TEMP
    {
        
    /// <summary>
    ///CAM_P_MEAS_ID
    /// </summary>
    public string CAM_P_MEAS_ID { get; set; }
        
    /// <summary>
    ///FACTORY_CODE
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///PART_SORT
    /// </summary>
    public string PART_SORT { get; set; }
        
    /// <summary>
    ///PART_2D_CODE
    /// </summary>
    public string PART_2D_CODE { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_DIAM_1
    /// </summary>
    public decimal SHAFT_NECK_DIAM_1 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_DIAM_2
    /// </summary>
    public decimal SHAFT_NECK_DIAM_2 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_DIAM_3
    /// </summary>
    public decimal SHAFT_NECK_DIAM_3 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_DIAM_4
    /// </summary>
    public decimal SHAFT_NECK_DIAM_4 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_DIAM_5
    /// </summary>
    public decimal SHAFT_NECK_DIAM_5 { get; set; }
        
    /// <summary>
    ///SP_SHAFT_NECK_DIAM
    /// </summary>
    public decimal SP_SHAFT_NECK_DIAM { get; set; }
        
    /// <summary>
    ///CAM_LONG_LEN_1
    /// </summary>
    public decimal CAM_LONG_LEN_1 { get; set; }
        
    /// <summary>
    ///CAM_LONG_LEN_2
    /// </summary>
    public decimal CAM_LONG_LEN_2 { get; set; }
        
    /// <summary>
    ///CAM_LONG_LEN_3
    /// </summary>
    public decimal CAM_LONG_LEN_3 { get; set; }
        
    /// <summary>
    ///CAM_LONG_LEN_4
    /// </summary>
    public decimal CAM_LONG_LEN_4 { get; set; }
        
    /// <summary>
    ///CAM_LONG_LEN_5
    /// </summary>
    public decimal CAM_LONG_LEN_5 { get; set; }
        
    /// <summary>
    ///CAM_LONG_LEN_6
    /// </summary>
    public decimal CAM_LONG_LEN_6 { get; set; }
        
    /// <summary>
    ///CAM_LONG_LEN_7
    /// </summary>
    public decimal CAM_LONG_LEN_7 { get; set; }
        
    /// <summary>
    ///CAM_LONG_LEN_8
    /// </summary>
    public decimal CAM_LONG_LEN_8 { get; set; }
        
    /// <summary>
    ///CAM_SHORT_LEN_1
    /// </summary>
    public decimal CAM_SHORT_LEN_1 { get; set; }
        
    /// <summary>
    ///CAM_SHORT_LEN_2
    /// </summary>
    public decimal CAM_SHORT_LEN_2 { get; set; }
        
    /// <summary>
    ///CAM_SHORT_LEN_3
    /// </summary>
    public decimal CAM_SHORT_LEN_3 { get; set; }
        
    /// <summary>
    ///CAM_SHORT_LEN_4
    /// </summary>
    public decimal CAM_SHORT_LEN_4 { get; set; }
        
    /// <summary>
    ///CAM_SHORT_LEN_5
    /// </summary>
    public decimal CAM_SHORT_LEN_5 { get; set; }
        
    /// <summary>
    ///CAM_SHORT_LEN_6
    /// </summary>
    public decimal CAM_SHORT_LEN_6 { get; set; }
        
    /// <summary>
    ///CAM_SHORT_LEN_7
    /// </summary>
    public decimal CAM_SHORT_LEN_7 { get; set; }
        
    /// <summary>
    ///CAM_SHORT_LEN_8
    /// </summary>
    public decimal CAM_SHORT_LEN_8 { get; set; }
        
    /// <summary>
    ///CAM_JUMP_1
    /// </summary>
    public decimal CAM_JUMP_1 { get; set; }
        
    /// <summary>
    ///CAM_JUMP_2
    /// </summary>
    public decimal CAM_JUMP_2 { get; set; }
        
    /// <summary>
    ///CAM_JUMP_3
    /// </summary>
    public decimal CAM_JUMP_3 { get; set; }
        
    /// <summary>
    ///CAM_JUMP_4
    /// </summary>
    public decimal CAM_JUMP_4 { get; set; }
        
    /// <summary>
    ///CAM_JUMP_5
    /// </summary>
    public decimal CAM_JUMP_5 { get; set; }
        
    /// <summary>
    ///CAM_JUMP_6
    /// </summary>
    public decimal CAM_JUMP_6 { get; set; }
        
    /// <summary>
    ///CAM_JUMP_7
    /// </summary>
    public decimal CAM_JUMP_7 { get; set; }
        
    /// <summary>
    ///CAM_JUMP_8
    /// </summary>
    public decimal CAM_JUMP_8 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_CIRCLE_1
    /// </summary>
    public decimal SHAFT_NECK_CIRCLE_1 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_CIRCLE_2
    /// </summary>
    public decimal SHAFT_NECK_CIRCLE_2 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_CIRCLE_3
    /// </summary>
    public decimal SHAFT_NECK_CIRCLE_3 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_CIRCLE_4
    /// </summary>
    public decimal SHAFT_NECK_CIRCLE_4 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_CIRCLE_5
    /// </summary>
    public decimal SHAFT_NECK_CIRCLE_5 { get; set; }
        
    /// <summary>
    ///ORDER_NO
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///IS_ENABLE
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP_USER_ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP_ORG_ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///UPDATE_CONTROL_ID
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///MAC_TYPE
    /// </summary>
    public string MAC_TYPE { get; set; }
        
    /// <summary>
    ///FACTORY_NAME
    /// </summary>
    public string FACTORY_NAME { get; set; }
        
    /// <summary>
    ///PROCESS_CODE
    /// </summary>
    public string PROCESS_CODE { get; set; }
        
    /// <summary>
    ///LOGIC_PROCESS
    /// </summary>
    public string LOGIC_PROCESS { get; set; }
        
    /// <summary>
    ///PART_PROCESS_ID
    /// </summary>
    public string PART_PROCESS_ID { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_DIAM_6
    /// </summary>
    public decimal SHAFT_NECK_DIAM_6 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_CIRCLE_6
    /// </summary>
    public decimal SHAFT_NECK_CIRCLE_6 { get; set; }
        
    /// <summary>
    ///SP_SHAFT_NECK_CIRCLE
    /// </summary>
    public decimal SP_SHAFT_NECK_CIRCLE { get; set; }
        
    /// <summary>
    ///CAM_ANGLE_2
    /// </summary>
    public decimal CAM_ANGLE_2 { get; set; }
        
    /// <summary>
    ///CAM_ANGLE_3
    /// </summary>
    public decimal CAM_ANGLE_3 { get; set; }
        
    /// <summary>
    ///CAM_ANGLE_4
    /// </summary>
    public decimal CAM_ANGLE_4 { get; set; }
        
    /// <summary>
    ///CAM_ANGLE_5
    /// </summary>
    public decimal CAM_ANGLE_5 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_JUMP_2
    /// </summary>
    public decimal SHAFT_NECK_JUMP_2 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_JUMP_3
    /// </summary>
    public decimal SHAFT_NECK_JUMP_3 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_JUMP_4
    /// </summary>
    public decimal SHAFT_NECK_JUMP_4 { get; set; }
        
    /// <summary>
    ///SHAFT_NECK_JUMP_5
    /// </summary>
    public decimal SHAFT_NECK_JUMP_5 { get; set; }
        
    /// <summary>
    ///SP_SHAFT_NECK_JUMP
    /// </summary>
    public decimal SP_SHAFT_NECK_JUMP { get; set; }
        
    /// <summary>
    ///PUMP_CAM_LONG_LEN
    /// </summary>
    public decimal PUMP_CAM_LONG_LEN { get; set; }
        
    /// <summary>
    ///PUMP_CAM_SHORT_LEN
    /// </summary>
    public decimal PUMP_CAM_SHORT_LEN { get; set; }
        
    /// <summary>
    ///PUMP_CAM_ANGLE
    /// </summary>
    public decimal PUMP_CAM_ANGLE { get; set; }
        
    /// <summary>
    ///CAM_ANGLE_6
    /// </summary>
    public decimal CAM_ANGLE_6 { get; set; }
        
    /// <summary>
    ///CAM_ANGLE_7
    /// </summary>
    public decimal CAM_ANGLE_7 { get; set; }
        
    /// <summary>
    ///CAM_ANGLE_1
    /// </summary>
    public decimal CAM_ANGLE_1 { get; set; }
    }
}
