//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///色差对比检测
    /// </summary>
    public partial class T_PQ_BU_CAR_CHRO_CHECK
    {
        
    /// <summary>
    ///色差对比检测ID
    /// </summary>
    public string CAR_CHRO_CHECK_ID { get; set; }
        
    /// <summary>
    ///颜色
    /// </summary>
    public string CAR_COLOR { get; set; }
        
    /// <summary>
    ///自编号
    /// </summary>
    public string SELF_CODE { get; set; }
        
    /// <summary>
    ///仪器检测部位
    /// </summary>
    public string INSTRUMENT_PART_POS_CODE { get; set; }
        
    /// <summary>
    ///仪器检测结果
    /// </summary>
    public string INSTRUMENT_CR { get; set; }
        
    /// <summary>
    ///检测基准-最大值
    /// </summary>
    public decimal CB_MAX_VAL { get; set; }
        
    /// <summary>
    ///检测基准-最小值
    /// </summary>
    public decimal CB_MIN_VAL { get; set; }
        
    /// <summary>
    ///目视项目
    /// </summary>
    public string VISUAL_ITEM { get; set; }
        
    /// <summary>
    ///目视结果-正面
    /// </summary>
    public string VISUAL_RESULT_OBVERSE { get; set; }
        
    /// <summary>
    ///目视结果-底面
    /// </summary>
    public string VISUAL_RESULT_BOTTOM { get; set; }
        
    /// <summary>
    ///检查基准-明度最大值
    /// </summary>
    public decimal CB_BRIGHT_MAX { get; set; }
        
    /// <summary>
    ///检查基准-明度最小值
    /// </summary>
    public decimal CB_BRIGHT_MIN { get; set; }
        
    /// <summary>
    ///检查基准-红相最大值
    /// </summary>
    public decimal CB_RED_MAX { get; set; }
        
    /// <summary>
    ///检查基准-红相最小值
    /// </summary>
    public decimal CB_RED_MIN { get; set; }
        
    /// <summary>
    ///检查基准-黄相最大值
    /// </summary>
    public decimal CB_YELLOW_MAX { get; set; }
        
    /// <summary>
    ///检查基准-黄相最小值
    /// </summary>
    public decimal CB_YELLOW_MIN { get; set; }
        
    /// <summary>
    ///结论
    /// </summary>
    public string CONCLUSION_DESC { get; set; }
        
    /// <summary>
    ///判断结果
    /// </summary>
    public string JUDGE_RESULT { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    
        public virtual T_PQ_BU_QUALITY_CHECK_V T_PQ_BU_QUALITY_CHECK_V { get; set; }
    }
}
