//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///QIC质量异常处理单处理履历表
    /// </summary>
    public partial class T_PQ_BU_QIC_EXCE_EXP
    {
        
    /// <summary>
    ///QIC质量异常处理单处理履历表ID
    /// </summary>
    public string QIC_EXCE_EXP_ID { get; set; }
        
    /// <summary>
    ///处理类型：发行，答复，确认，追加确认
    /// </summary>
    public string DEAL_TYPE { get; set; }
        
    /// <summary>
    ///处理人员角色：担当，工程师，系长，科长，部长
    /// </summary>
    public string DEAL_MAN { get; set; }
        
    /// <summary>
    ///处理人
    /// </summary>
    public string DEAL_PERSON { get; set; }
        
    /// <summary>
    ///处理时间
    /// </summary>
    public System.DateTime DEAL_DATE { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///处理意见
    /// </summary>
    public string DEAL_OPINION { get; set; }
        
    /// <summary>
    ///QIC质量异常操作后处理单状态
    /// </summary>
    public string QIC_EXCE_STATUS { get; set; }
    
        public virtual T_PQ_BU_QIC_EXCE_M T_PQ_BU_QIC_EXCE_M { get; set; }
    }
}
