//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///缺陷标准不良组维护
    /// </summary>
    public partial class T_PQ_DB_DEFECT_STAN_BAD_G
    {
        
    /// <summary>
    ///不良组维护ID
    /// </summary>
    public string DEFECT_STAN_BAD_G_ID { get; set; }
        
    /// <summary>
    ///不良组名称
    /// </summary>
    public string BAD_G_NAME { get; set; }
        
    /// <summary>
    ///不良组编码
    /// </summary>
    public string BAD_G_CODE { get; set; }
        
    /// <summary>
    ///拼音字段
    /// </summary>
    public string PINYIN_FIELD { get; set; }
        
    /// <summary>
    ///不良组类型
    /// </summary>
    public string BAD_G_TYPE { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///颜色编码
    /// </summary>
    public string COLOR_CODE { get; set; }
        
    /// <summary>
    ///扩展2
    /// </summary>
    public string EXTENDED_2 { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///SUV
    /// </summary>
    public string SUV_FLAG { get; set; }
        
    /// <summary>
    ///两厢
    /// </summary>
    public string TWO_BOX_FLAG { get; set; }
        
    /// <summary>
    ///三厢
    /// </summary>
    public string THR_BOX_FLAG { get; set; }
        
    /// <summary>
    ///MPV
    /// </summary>
    public string MPV_FLAG { get; set; }
        
    /// <summary>
    ///缺陷类别编码
    /// </summary>
    public string STAN_TYPE { get; set; }
    }
}
