//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///失效模式判定信息表
    /// </summary>
    public partial class T_PQ_BU_FMEA_DATA
    {
        
    /// <summary>
    ///失效模式判定信息表ID
    /// </summary>
    public string FMEA_DATA_ID { get; set; }
        
    /// <summary>
    ///QIC质量异常处理单主表ID
    /// </summary>
    public string QIC_EXCE_M_ID { get; set; }
        
    /// <summary>
    ///严重度(S)分值
    /// </summary>
    public decimal SEVERITY_VALUE { get; set; }
        
    /// <summary>
    ///严重度(S)评分理由
    /// </summary>
    public string SEVERITY_REASON { get; set; }
        
    /// <summary>
    ///频度(O)分值
    /// </summary>
    public decimal OCCURRENCE_VALUE { get; set; }
        
    /// <summary>
    ///频度(O)评分理由
    /// </summary>
    public string OCCURRENCE_REASON { get; set; }
        
    /// <summary>
    ///探测度(D)分值
    /// </summary>
    public decimal DETECTIVITY_VALUE { get; set; }
        
    /// <summary>
    ///探测度(D)评分理由
    /// </summary>
    public string DETECTIVITY_REASON { get; set; }
        
    /// <summary>
    ///市场风险（1：高；2：中；3：低）
    /// </summary>
    public string MARKET_RISK { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///修改人
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///修改日期
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
    }
}
