//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///装配KH1T线冷试信息表
    /// </summary>
    public partial class T_PQ_BU_ASSE_COOL_ML
    {
        
    /// <summary>
    ///装配KH1T线冷试信息ID
    /// </summary>
    public string ASSE_COOL_ML_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///测漏结果
    /// </summary>
    public string MEAS_LEAK_RESULT { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///测漏数值1
    /// </summary>
    public decimal MEAS_VAL_1 { get; set; }
        
    /// <summary>
    ///测漏数值2
    /// </summary>
    public decimal MEAS_VAL_2 { get; set; }
        
    /// <summary>
    ///测漏数值3
    /// </summary>
    public decimal MEAS_VAL_3 { get; set; }
        
    /// <summary>
    ///测漏数值4
    /// </summary>
    public decimal MEAS_VAL_4 { get; set; }
        
    /// <summary>
    ///测漏数值5
    /// </summary>
    public decimal MEAS_VAL_5 { get; set; }
        
    /// <summary>
    ///测漏数值6
    /// </summary>
    public decimal MEAS_VAL_6 { get; set; }
        
    /// <summary>
    ///测漏数值7
    /// </summary>
    public decimal MEAS_VAL_7 { get; set; }
        
    /// <summary>
    ///测漏数值8
    /// </summary>
    public decimal MEAS_VAL_8 { get; set; }
        
    /// <summary>
    ///测漏数值9
    /// </summary>
    public decimal MEAS_VAL_9 { get; set; }
        
    /// <summary>
    ///测漏数值10
    /// </summary>
    public decimal MEAS_VAL_10 { get; set; }
        
    /// <summary>
    ///测漏数值11
    /// </summary>
    public decimal MEAS_VAL_11 { get; set; }
        
    /// <summary>
    ///测漏数值12
    /// </summary>
    public decimal MEAS_VAL_12 { get; set; }
        
    /// <summary>
    ///测漏数值13
    /// </summary>
    public decimal MEAS_VAL_13 { get; set; }
        
    /// <summary>
    ///测漏数值14
    /// </summary>
    public decimal MEAS_VAL_14 { get; set; }
        
    /// <summary>
    ///测漏数值15
    /// </summary>
    public decimal MEAS_VAL_15 { get; set; }
        
    /// <summary>
    ///测漏数值16
    /// </summary>
    public decimal MEAS_VAL_16 { get; set; }
        
    /// <summary>
    ///测漏数值17
    /// </summary>
    public decimal MEAS_VAL_17 { get; set; }
        
    /// <summary>
    ///测漏数值18
    /// </summary>
    public decimal MEAS_VAL_18 { get; set; }
        
    /// <summary>
    ///测漏数值19
    /// </summary>
    public decimal MEAS_VAL_19 { get; set; }
        
    /// <summary>
    ///测漏数值20
    /// </summary>
    public decimal MEAS_VAL_20 { get; set; }
        
    /// <summary>
    ///测漏数值21
    /// </summary>
    public decimal MEAS_VAL_21 { get; set; }
        
    /// <summary>
    ///测漏数值22
    /// </summary>
    public decimal MEAS_VAL_22 { get; set; }
        
    /// <summary>
    ///测漏数值23
    /// </summary>
    public decimal MEAS_VAL_23 { get; set; }
        
    /// <summary>
    ///测漏数值24
    /// </summary>
    public decimal MEAS_VAL_24 { get; set; }
        
    /// <summary>
    ///测漏数值25
    /// </summary>
    public decimal MEAS_VAL_25 { get; set; }
        
    /// <summary>
    ///测漏数值26
    /// </summary>
    public decimal MEAS_VAL_26 { get; set; }
        
    /// <summary>
    ///测漏数值27
    /// </summary>
    public decimal MEAS_VAL_27 { get; set; }
        
    /// <summary>
    ///测漏数值28
    /// </summary>
    public decimal MEAS_VAL_28 { get; set; }
        
    /// <summary>
    ///测漏数值29
    /// </summary>
    public decimal MEAS_VAL_29 { get; set; }
        
    /// <summary>
    ///测漏数值30
    /// </summary>
    public decimal MEAS_VAL_30 { get; set; }
        
    /// <summary>
    ///测漏数值31
    /// </summary>
    public decimal MEAS_VAL_31 { get; set; }
        
    /// <summary>
    ///测漏数值32
    /// </summary>
    public decimal MEAS_VAL_32 { get; set; }
        
    /// <summary>
    ///测漏数值33
    /// </summary>
    public decimal MEAS_VAL_33 { get; set; }
        
    /// <summary>
    ///测漏数值34
    /// </summary>
    public decimal MEAS_VAL_34 { get; set; }
        
    /// <summary>
    ///测漏数值35
    /// </summary>
    public decimal MEAS_VAL_35 { get; set; }
        
    /// <summary>
    ///测漏数值36
    /// </summary>
    public decimal MEAS_VAL_36 { get; set; }
        
    /// <summary>
    ///测漏数值37
    /// </summary>
    public decimal MEAS_VAL_37 { get; set; }
        
    /// <summary>
    ///测漏数值38
    /// </summary>
    public decimal MEAS_VAL_38 { get; set; }
        
    /// <summary>
    ///测漏数值39
    /// </summary>
    public decimal MEAS_VAL_39 { get; set; }
        
    /// <summary>
    ///测漏数值40
    /// </summary>
    public decimal MEAS_VAL_40 { get; set; }
        
    /// <summary>
    ///测漏数值41
    /// </summary>
    public decimal MEAS_VAL_41 { get; set; }
        
    /// <summary>
    ///测漏数值42
    /// </summary>
    public decimal MEAS_VAL_42 { get; set; }
        
    /// <summary>
    ///测漏数值43
    /// </summary>
    public decimal MEAS_VAL_43 { get; set; }
        
    /// <summary>
    ///测漏数值44
    /// </summary>
    public decimal MEAS_VAL_44 { get; set; }
        
    /// <summary>
    ///测漏数值45
    /// </summary>
    public decimal MEAS_VAL_45 { get; set; }
        
    /// <summary>
    ///测漏数值46
    /// </summary>
    public decimal MEAS_VAL_46 { get; set; }
        
    /// <summary>
    ///测漏数值47
    /// </summary>
    public decimal MEAS_VAL_47 { get; set; }
        
    /// <summary>
    ///测漏数值48
    /// </summary>
    public decimal MEAS_VAL_48 { get; set; }
        
    /// <summary>
    ///测漏数值49
    /// </summary>
    public decimal MEAS_VAL_49 { get; set; }
        
    /// <summary>
    ///测漏数值50
    /// </summary>
    public decimal MEAS_VAL_50 { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///扫描时间
    /// </summary>
    public System.DateTime SWEEP_TIME_VAL { get; set; }
        
    /// <summary>
    ///发动机号
    /// </summary>
    public string ENGINE_NO { get; set; }
        
    /// <summary>
    ///零件编码
    /// </summary>
    public string PART_NO { get; set; }
    }
}
