//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///基础数据_涂装规格导入表
    /// </summary>
    public partial class T_PQ_DB_PT_SPEC_IMP
    {
        
    /// <summary>
    ///基础数据_涂装规格导入ID
    /// </summary>
    public string PT_SPEC_IMP_ID { get; set; }
        
    /// <summary>
    ///颜色
    /// </summary>
    public string CAR_COLOR { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///涂装测量类型
    /// </summary>
    public string PAINT_MEAS_TYPE { get; set; }
        
    /// <summary>
    ///测量项目大类
    /// </summary>
    public string ITEM_BIG_TYPE { get; set; }
        
    /// <summary>
    ///测量项目小类
    /// </summary>
    public string ITEM_SMALL_TYPE { get; set; }
        
    /// <summary>
    ///测量项目
    /// </summary>
    public string MEASURE_ITEM { get; set; }
        
    /// <summary>
    ///部位
    /// </summary>
    public string PART_POS { get; set; }
        
    /// <summary>
    ///检规上限
    /// </summary>
    public string CHECK_M_VALUE { get; set; }
        
    /// <summary>
    ///检规下限
    /// </summary>
    public string CHECK_L_VALUE { get; set; }
        
    /// <summary>
    ///内规上限
    /// </summary>
    public string IN_MAX_VALUE { get; set; }
        
    /// <summary>
    ///内规下限
    /// </summary>
    public string IN_L_BOUND_VAL { get; set; }
        
    /// <summary>
    ///部位大类
    /// </summary>
    public string PART_POS_BIG_TYPE { get; set; }
        
    /// <summary>
    ///部位中类
    /// </summary>
    public string PART_POS_MID_TYPE { get; set; }
        
    /// <summary>
    ///部位小类
    /// </summary>
    public string PART_POS_SMALL_TYPE { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///导入批次号
    /// </summary>
    public string BATCHNO { get; set; }
        
    /// <summary>
    ///导入错误类型
    /// </summary>
    public string PT_ERR_FLAG { get; set; }
        
    /// <summary>
    ///导入错误信息
    /// </summary>
    public string PT_ERR_MSG { get; set; }
    }
}
