//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///曲轴孔分级打号数据表
    /// </summary>
    public partial class T_PQ_BU_CS_HOLE_E
    {
        
    /// <summary>
    ///曲轴分级打号ID
    /// </summary>
    public string CS_HOLE_E_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///工程
    /// </summary>
    public string ENGINEERING_TYPE { get; set; }
        
    /// <summary>
    ///设备编码
    /// </summary>
    public string EQUIP_CODE { get; set; }
        
    /// <summary>
    ///扫描时间
    /// </summary>
    public System.DateTime SWEEP_TIME_VAL { get; set; }
        
    /// <summary>
    ///二维码
    /// </summary>
    public string QR_CODE { get; set; }
        
    /// <summary>
    ///1#曲轴孔测量数据直径（Dia.CrankN.Secn.x）
    /// </summary>
    public string VALUE01 { get; set; }
        
    /// <summary>
    ///1#曲轴孔测量数据直径（Dia.CrankN.Secn.y）
    /// </summary>
    public string VALUE02 { get; set; }
        
    /// <summary>
    ///2#曲轴孔测量数据直径（Dia.CrankN.Secn.x）
    /// </summary>
    public string VALUE03 { get; set; }
        
    /// <summary>
    ///2#曲轴孔测量数据直径（Dia.CrankN.Secn.y）
    /// </summary>
    public string VALUE04 { get; set; }
        
    /// <summary>
    ///3#曲轴孔测量数据直径（Dia.CrankN.Secn.x）
    /// </summary>
    public string VALUE05 { get; set; }
        
    /// <summary>
    ///3#曲轴孔测量数据直径（Dia.CrankN.Secn.y）
    /// </summary>
    public string VALUE06 { get; set; }
        
    /// <summary>
    ///4#曲轴孔测量数据直径（Dia.CrankN.Secn.x）
    /// </summary>
    public string VALUE07 { get; set; }
        
    /// <summary>
    ///4#曲轴孔测量数据直径（Dia.CrankN.Secn.y）
    /// </summary>
    public string VALUE08 { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///5#曲轴孔测量数据直径（Dia.CrankN.Secn.x）
    /// </summary>
    public string VALUE09 { get; set; }
        
    /// <summary>
    ///5#曲轴孔测量数据直径（Dia.CrankN.Secn.y）
    /// </summary>
    public string VALUE10 { get; set; }
        
    /// <summary>
    ///5#曲轴孔分级打号数据
    /// </summary>
    public string VALUE11 { get; set; }
        
    /// <summary>
    ///部品工序信息ID
    /// </summary>
    public string PART_PROCESS_ID { get; set; }
        
    /// <summary>
    ///逻辑工序
    /// </summary>
    public string LOGIC_PROCESS { get; set; }
    }
}
