//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///车辆零件清单
    /// </summary>
    public partial class T_PQ_BU_CAR_PART
    {
        
    /// <summary>
    ///车辆零件清单ID
    /// </summary>
    public string CAR_PART_ID { get; set; }
        
    /// <summary>
    ///车系编码
    /// </summary>
    public string CAR_SERIES_CODE { get; set; }
        
    /// <summary>
    ///车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///零件编码
    /// </summary>
    public string PART_NO { get; set; }
        
    /// <summary>
    ///零件批次号
    /// </summary>
    public string PART_BATCH_CODE { get; set; }
        
    /// <summary>
    ///零件生产序号
    /// </summary>
    public string PART_PROD_NUM { get; set; }
        
    /// <summary>
    ///数量
    /// </summary>
    public decimal QTY { get; set; }
        
    /// <summary>
    ///零件来源
    /// </summary>
    public string PART_SOURCE { get; set; }
        
    /// <summary>
    ///零件类型
    /// </summary>
    public string PART_TYPE { get; set; }
        
    /// <summary>
    ///装配人
    /// </summary>
    public string ASSEMBLE_MAN { get; set; }
        
    /// <summary>
    ///装配时间
    /// </summary>
    public System.DateTime ASSEMBLE_DATE { get; set; }
        
    /// <summary>
    ///装配地点
    /// </summary>
    public string ASSEMBLE_POS { get; set; }
        
    /// <summary>
    ///录入人员
    /// </summary>
    public string ENTRY_CLERK { get; set; }
        
    /// <summary>
    ///录入时间
    /// </summary>
    public System.DateTime OPER_DATE { get; set; }
        
    /// <summary>
    ///车辆零件状态
    /// </summary>
    public string CAR_PART_STATUS { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
