//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///返修车信息_屏幕显示设置
    /// </summary>
    public partial class T_PQ_BU_FX_DISPLAY_SET
    {
        
    /// <summary>
    ///屏幕显示设置ID
    /// </summary>
    public string FX_DISPLAY_SET_ID { get; set; }
        
    /// <summary>
    ///显示条数
    /// </summary>
    public decimal DISPLAY_NUM { get; set; }
        
    /// <summary>
    ///刷新间隔
    /// </summary>
    public decimal REFRESH_INTERVAL { get; set; }
        
    /// <summary>
    ///底盘返修区起(标红)
    /// </summary>
    public decimal CRWA_BEGIN_TORED { get; set; }
        
    /// <summary>
    ///底盘返修区止(标红)
    /// </summary>
    public decimal CRWA_END_TORED { get; set; }
        
    /// <summary>
    ///报交车间返修区起(标红) (可用时间)
    /// </summary>
    public decimal WSRA_BEGIN_TORED { get; set; }
        
    /// <summary>
    ///报交车间返修区止(标红) (可用时间)
    /// </summary>
    public decimal WSRA_AEND_TORED { get; set; }
        
    /// <summary>
    ///底盘返修区起(标黄)
    /// </summary>
    public decimal CRWA_BEGIN_TOYELLOW { get; set; }
        
    /// <summary>
    ///底盘返修区止(标黄)
    /// </summary>
    public decimal CRWA_END_TOYELLOW { get; set; }
        
    /// <summary>
    ///报交车间返修区起(标黄) (可用时间)
    /// </summary>
    public decimal WSRA_BEGIN_TOYELLOW { get; set; }
        
    /// <summary>
    ///报交车间返修区止(标黄) (可用时间)
    /// </summary>
    public decimal WSRA_END_TOYELLOW { get; set; }
        
    /// <summary>
    ///隐藏字段
    /// </summary>
    public string HIDDENFIELDS { get; set; }
        
    /// <summary>
    ///用户ID
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///降序优先级(0:返修可用时间;1:分配状态)
    /// </summary>
    public decimal DESCENDINGPRIORITY { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///隐藏字段名称(中文名称)
    /// </summary>
    public string HIDDENFIELDS_NAME { get; set; }
    }
}
