//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///装配KH1T线总成测漏信息表
    /// </summary>
    public partial class T_PQ_BU_ASSEMBLY_ML
    {
        
    /// <summary>
    ///装配KH1T线总成测漏信息ID
    /// </summary>
    public string ASSEMBLY_ML_ID { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///测漏结果
    /// </summary>
    public string MEAS_LEAK_RESULT { get; set; }
        
    /// <summary>
    ///主油道测漏数值
    /// </summary>
    public decimal MAIN_OIL_ML { get; set; }
        
    /// <summary>
    ///水道测漏数值
    /// </summary>
    public decimal CHANNEL_ML { get; set; }
        
    /// <summary>
    ///燃烧室测漏数值
    /// </summary>
    public decimal FIREBOX_ML { get; set; }
        
    /// <summary>
    ///曲轴箱测漏数值
    /// </summary>
    public decimal CRANKCASE_ML { get; set; }
        
    /// <summary>
    ///燃料系测漏数值
    /// </summary>
    public decimal FUEL_SYS_ML { get; set; }
        
    /// <summary>
    ///活塞环测漏数值
    /// </summary>
    public decimal PISTON_RING_ML { get; set; }
        
    /// <summary>
    ///主轴承测漏数值
    /// </summary>
    public decimal MAIN_SHAFT_TILE_ML { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///主油道压力数值
    /// </summary>
    public decimal MAIN_OIL_PRE { get; set; }
        
    /// <summary>
    ///水道压力数值
    /// </summary>
    public decimal CHANNEL_PRE { get; set; }
        
    /// <summary>
    ///燃烧室压力数值
    /// </summary>
    public decimal FIREBOX_PRE { get; set; }
        
    /// <summary>
    ///曲轴箱压力数值
    /// </summary>
    public decimal CRANKCASE_PRE { get; set; }
        
    /// <summary>
    ///燃料系压力数值
    /// </summary>
    public decimal FUEL_SYS_PRE { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///扫描时间
    /// </summary>
    public System.DateTime SWEEP_TIME_VAL { get; set; }
        
    /// <summary>
    ///发动机号
    /// </summary>
    public string ENGINE_NO { get; set; }
        
    /// <summary>
    ///零件编码
    /// </summary>
    public string PART_NO { get; set; }
    }
}
