//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///部品工位关系表
    /// </summary>
    public partial class T_PQ_BU_PART_POS_R
    {
        
    /// <summary>
    ///部品工位关系表ID
    /// </summary>
    public string PART_POS_R_ID { get; set; }
        
    /// <summary>
    ///SAP工厂代码，值来源工厂表的SAP_FACTORY_CODE
    /// </summary>
    public string SYSTEM_FAC_CODE { get; set; }
        
    /// <summary>
    ///零件编码
    /// </summary>
    public string PART_NO { get; set; }
        
    /// <summary>
    ///手配号，值来源T_DB_DB_SERIAL_CPL_REL表的FAMILY_CODE字段
    /// </summary>
    public string CAR_SERIES_CODE { get; set; }
        
    /// <summary>
    ///装配车间
    /// </summary>
    public string ASSE_WORKSHOP { get; set; }
        
    /// <summary>
    ///班组
    /// </summary>
    public string TEAM_CODE { get; set; }
        
    /// <summary>
    ///工位代码
    /// </summary>
    public string WORK_STATION_CODE { get; set; }
        
    /// <summary>
    ///工位名称
    /// </summary>
    public string WORK_STATION_NAME { get; set; }
        
    /// <summary>
    ///方位
    /// </summary>
    public string DIR_POS_CODE { get; set; }
        
    /// <summary>
    ///料位
    /// </summary>
    public string MAT_POS_CODE { get; set; }
        
    /// <summary>
    ///状态（值：1 启用， 0 废止）
    /// </summary>
    public string STATUS { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///当工顺
    /// </summary>
    public string WORK_ORDER_NO { get; set; }
        
    /// <summary>
    ///SNP
    /// </summary>
    public decimal SNP { get; set; }
        
    /// <summary>
    ///计划切换时间
    /// </summary>
    public string PLAN_SWITCH_TIME { get; set; }
    }
}
