//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///覆膜砂到货测量
    /// </summary>
    public partial class T_PQ_BU_PRE_SAND_CHECK
    {
        
    /// <summary>
    ///覆膜砂到货测量ID
    /// </summary>
    public string PRE_SAND_CHECK_ID { get; set; }
        
    /// <summary>
    ///检测项目细分
    /// </summary>
    public string CHECK_ITEM_D { get; set; }
        
    /// <summary>
    ///品名
    /// </summary>
    public string PRE_SAND_NAME { get; set; }
        
    /// <summary>
    ///检测部位
    /// </summary>
    public string CHECK_PART_POS_CODE { get; set; }
        
    /// <summary>
    ///检测内容概要
    /// </summary>
    public string CHECK_CONTENT_OVERVIEW { get; set; }
        
    /// <summary>
    ///检测目的
    /// </summary>
    public string CHECK_TAR { get; set; }
        
    /// <summary>
    ///覆膜砂规格
    /// </summary>
    public string PRE_SAND_SPECI { get; set; }
        
    /// <summary>
    ///样本总量
    /// </summary>
    public decimal SAMPLE_TOTAL { get; set; }
        
    /// <summary>
    ///检测结果
    /// </summary>
    public decimal CHECK_RESULT { get; set; }
        
    /// <summary>
    ///问题描述
    /// </summary>
    public string PROBLEM_DESC { get; set; }
        
    /// <summary>
    ///判断结果
    /// </summary>
    public string JUDGE_RESULT { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    
        public virtual T_PQ_BU_QUALITY_CHECK_E T_PQ_BU_QUALITY_CHECK_E { get; set; }
    }
}
