//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///涂装测量数据主表
    /// </summary>
    public partial class T_PQ_BU_PT_MEASURE_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PQ_BU_PT_MEASURE_M()
        {
            this.T_PQ_BU_PT_MEASURE_D = new HashSet<T_PQ_BU_PT_MEASURE_D>();
        }
    
        
    /// <summary>
    ///涂装测量数据主表ID
    /// </summary>
    public string PT_MEASURE_M_ID { get; set; }
        
    /// <summary>
    ///测量类型 1：NID、2：膜厚；3：电泳漆；4：单品；5：联合
    /// </summary>
    public string MEAS_TYPE { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///车间编码
    /// </summary>
    public string WORKSHOP_CODE { get; set; }
        
    /// <summary>
    ///车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///颜色编码
    /// </summary>
    public string COLOR_CODE { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///测量日期
    /// </summary>
    public System.DateTime MEASURE_DATE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///结果判定 0：NG；1：OK
    /// </summary>
    public string IS_OK { get; set; }
        
    /// <summary>
    ///结论
    /// </summary>
    public string CONCLUSION_DESC { get; set; }
        
    /// <summary>
    ///技术调整方案
    /// </summary>
    public string TECH_ADJUST_SCHEME { get; set; }
        
    /// <summary>
    ///整车检查员
    /// </summary>
    public string VE_CHECK_MAN { get; set; }
        
    /// <summary>
    ///涂装检查员
    /// </summary>
    public string PAINT_CHECK_MAN { get; set; }
        
    /// <summary>
    ///技术科
    /// </summary>
    public string TECH_SEC { get; set; }
        
    /// <summary>
    ///BASF
    /// </summary>
    public string BASF_VAL { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///班别
    /// </summary>
    public string SCHEDULE_TYPE { get; set; }
        
    /// <summary>
    ///树脂检查员
    /// </summary>
    public string RESIN_CHECK_MAN { get; set; }
        
    /// <summary>
    ///CCR编号
    /// </summary>
    public string CCR_CODE { get; set; }
        
    /// <summary>
    ///临时类型
    /// </summary>
    public string TEMP_TYPE { get; set; }
        
    /// <summary>
    ///数据来源 默认为0 0为接口数据 1为数据维护
    /// </summary>
    public string DATA_SOURCE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_BU_PT_MEASURE_D> T_PQ_BU_PT_MEASURE_D { get; set; }
    }
}
