//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///车辆流转状态
    /// </summary>
    public partial class T_PQ_BU_STOCK_STATUS
    {
        
    /// <summary>
    ///流转状态ID
    /// </summary>
    public string STOCK_ID { get; set; }
        
    /// <summary>
    ///车辆识别代号/车架号码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///车辆状态 状态：在库；出库；已销售
    /// </summary>
    public string CAR_STATUS { get; set; }
        
    /// <summary>
    ///所有人 位置：PV；专营店名称；客户名称
    /// </summary>
    public string ALL_NAME { get; set; }
        
    /// <summary>
    ///仓库名称
    /// </summary>
    public string CAR_HOUSE_NAME { get; set; }
        
    /// <summary>
    ///处理状态
    /// </summary>
    public string DATA_STATUS { get; set; }
        
    /// <summary>
    ///CREATOR
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///CREATED_DATE
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///MODIFIER
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///LAST_UPDATED_DATE
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///备用1
    /// </summary>
    public string ATTRBUIT1 { get; set; }
        
    /// <summary>
    ///品牌编码：1日产；2启辰；3：其他品牌；4进口尼桑；5：英菲尼迪-国产
    /// </summary>
    public string ATTRBUIT2 { get; set; }
        
    /// <summary>
    ///备用3
    /// </summary>
    public string ATTRBUIT3 { get; set; }
        
    /// <summary>
    ///备用4
    /// </summary>
    public string ATTRBUIT4 { get; set; }
        
    /// <summary>
    ///备用5
    /// </summary>
    public string ATTRBUIT5 { get; set; }
    }
}
