//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///扭矩数据表
    /// </summary>
    public partial class T_PQ_BU_TORQUE_DATA
    {
        
    /// <summary>
    ///扭矩数据ID
    /// </summary>
    public string TORQUE_DATA_ID { get; set; }
        
    /// <summary>
    ///测量时间
    /// </summary>
    public System.DateTime MEASURE_DATE { get; set; }
        
    /// <summary>
    ///测量人
    /// </summary>
    public string MEASURE_MAN { get; set; }
        
    /// <summary>
    ///设备编码
    /// </summary>
    public string EQUIP_CODE { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///车间编码
    /// </summary>
    public string WORKSHOP_CODE { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///车型编码
    /// </summary>
    public string CAR_TYPE_CODE { get; set; }
        
    /// <summary>
    ///VIN码
    /// </summary>
    public string VIN { get; set; }
        
    /// <summary>
    ///CCR编号
    /// </summary>
    public string CCR_CODE { get; set; }
        
    /// <summary>
    ///管理号
    /// </summary>
    public string MANAGE_CODE { get; set; }
        
    /// <summary>
    ///18位码
    /// </summary>
    public string EIGTEEN_CODE { get; set; }
        
    /// <summary>
    ///机柜名称
    /// </summary>
    public string CABINET_NAME { get; set; }
        
    /// <summary>
    ///工位
    /// </summary>
    public string WORK_STATION_CODE { get; set; }
        
    /// <summary>
    ///作业名称
    /// </summary>
    public string JOB_NAME { get; set; }
        
    /// <summary>
    ///总次数
    /// </summary>
    public long TOT_TIMES { get; set; }
        
    /// <summary>
    ///剩余次数
    /// </summary>
    public long LEFT_TIMES { get; set; }
        
    /// <summary>
    ///控制器编号
    /// </summary>
    public string CTRL_CODE { get; set; }
        
    /// <summary>
    ///程序号
    /// </summary>
    public string APP_CODE { get; set; }
        
    /// <summary>
    ///处理状态
    /// </summary>
    public string DEAL_STATUS { get; set; }
        
    /// <summary>
    ///角度
    /// </summary>
    public string ANGLE_VAL { get; set; }
        
    /// <summary>
    ///实际扭矩值
    /// </summary>
    public decimal ACTUAL_TORQUE_VAL { get; set; }
        
    /// <summary>
    ///扭矩设定值
    /// </summary>
    public decimal TORQUE_SET_VAL { get; set; }
        
    /// <summary>
    ///扭矩下限值
    /// </summary>
    public decimal TORQUE_MIN_VAL { get; set; }
        
    /// <summary>
    ///扭矩上限值
    /// </summary>
    public decimal TORQUE_MAX_VAL { get; set; }
        
    /// <summary>
    ///完成状态
    /// </summary>
    public string FINISH_STATUS { get; set; }
        
    /// <summary>
    ///CPK计算
    /// </summary>
    public string CPK_CALCU { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///完成时间
    /// </summary>
    public System.DateTime COMPLETE_DATE { get; set; }
        
    /// <summary>
    ///打击次数
    /// </summary>
    public long HIT_TIMES { get; set; }
    }
}
