//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///部位提醒图主表
    /// </summary>
    public partial class T_PQ_DB_PART_POS_PIC_M
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_PQ_DB_PART_POS_PIC_M()
        {
            this.T_PQ_DB_PART_POS_PIC_D = new HashSet<T_PQ_DB_PART_POS_PIC_D>();
        }
    
        
    /// <summary>
    ///部位提醒图主表ID
    /// </summary>
    public string PART_POS_PIC_M_ID { get; set; }
        
    /// <summary>
    ///部位ID
    /// </summary>
    public string PART_POS_ID { get; set; }
        
    /// <summary>
    ///用户ID
    /// </summary>
    public string USER_ID { get; set; }
        
    /// <summary>
    ///部位名称
    /// </summary>
    public string PART_POS_NAME { get; set; }
        
    /// <summary>
    ///缺陷名称
    /// </summary>
    public string DEFECT_NAME { get; set; }
        
    /// <summary>
    ///缺陷ID
    /// </summary>
    public string DEFECT_ID { get; set; }
        
    /// <summary>
    ///图片切换间隔（分钟）
    /// </summary>
    public decimal PIC_SWITCH_INTERVAL_MIN { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_PQ_DB_PART_POS_PIC_D> T_PQ_DB_PART_POS_PIC_D { get; set; }
    }
}
