//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///下拉框关联表
    /// </summary>
    public partial class T_PQ_DB_PRT_CLD_REL
    {
        
    /// <summary>
    ///VARCHAR2(36)
    /// </summary>
    public string PRT_CLD_REL_ID { get; set; }
        
    /// <summary>
    ///VARCHAR2(200)
    /// </summary>
    public string PARENT_CODE { get; set; }
        
    /// <summary>
    ///VARCHAR2(200)
    /// </summary>
    public string PARENT_TYPE_CODE { get; set; }
        
    /// <summary>
    ///VARCHAR2(200)
    /// </summary>
    public string CHILD_CODE { get; set; }
        
    /// <summary>
    ///VARCHAR2(200)
    /// </summary>
    public string CHILD_TYPE_CODE { get; set; }
        
    /// <summary>
    ///VARCHAR2(200)
    /// </summary>
    public string REL_TYPE { get; set; }
        
    /// <summary>
    ///VARCHAR2(500)
    /// </summary>
    public string REL_TYPE_DESC { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
    }
}
