//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///QIC质量异常处理单附件明细表
    /// </summary>
    public partial class T_PQ_BU_QIC_EXCE_ATTA
    {
        
    /// <summary>
    ///QIC质量异常处理单附件明细表ID
    /// </summary>
    public string QIC_EXCE_ATTA_ID { get; set; }
        
    /// <summary>
    ///文件类型
    /// </summary>
    public string FILE_TYPE { get; set; }
        
    /// <summary>
    ///文件序号
    /// </summary>
    public int FILE_SERIES { get; set; }
        
    /// <summary>
    ///文件路径
    /// </summary>
    public string FILE_PATH { get; set; }
        
    /// <summary>
    ///排列顺序
    /// </summary>
    public decimal ORDER_NO { get; set; }
        
    /// <summary>
    ///是否可用
    /// </summary>
    public string IS_ENABLE { get; set; }
        
    /// <summary>
    ///创建人
    /// </summary>
    public string CREATOR { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///最后更新人员
    /// </summary>
    public string MODIFIER { get; set; }
        
    /// <summary>
    ///最后更新时间
    /// </summary>
    public System.DateTime LAST_UPDATED_DATE { get; set; }
        
    /// <summary>
    ///SDP用户ID
    /// </summary>
    public string SDP_USER_ID { get; set; }
        
    /// <summary>
    ///SDP组织ID
    /// </summary>
    public string SDP_ORG_ID { get; set; }
        
    /// <summary>
    ///并发控制字段
    /// </summary>
    public string UPDATE_CONTROL_ID { get; set; }
        
    /// <summary>
    ///文件编号
    /// </summary>
    public string FILE_NO { get; set; }
        
    /// <summary>
    ///标准化内容
    /// </summary>
    public string STANDARD_CONTENT { get; set; }
        
    /// <summary>
    ///责任单位
    /// </summary>
    public string DUTY_UNIT { get; set; }
        
    /// <summary>
    ///备注
    /// </summary>
    public string REMARK { get; set; }
        
    /// <summary>
    ///文件类型描述
    /// </summary>
    public string FILE_TYPE_DESC { get; set; }
        
    /// <summary>
    ///文件大类
    /// </summary>
    public string FILE_BIG_TYPE { get; set; }
        
    /// <summary>
    ///实施日期
    /// </summary>
    public System.DateTime IML_DATE { get; set; }
    
        public virtual T_PQ_BU_QIC_EXCE_M T_PQ_BU_QIC_EXCE_M { get; set; }
    }
}
