//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LY.MQCS.Plugin.DBService.Bak.PQ
{
    using System;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///条码统计率临时表
    /// </summary>
    public partial class T_PQ_BU_BARCODE_SCAN_RATE
    {
        
    /// <summary>
    ///统计类别 1-发动机，2-变速箱
    /// </summary>
    public string RATE_TYPE { get; set; }
        
    /// <summary>
    ///部品类别
    /// </summary>
    public string PART_SORT { get; set; }
        
    /// <summary>
    ///生产线编码
    /// </summary>
    public string PRO_LINE_CODE { get; set; }
        
    /// <summary>
    ///工序编码
    /// </summary>
    public string PROCESS_CODE { get; set; }
        
    /// <summary>
    ///工序名称
    /// </summary>
    public string PROCESS_NAME { get; set; }
        
    /// <summary>
    ///工序设备号
    /// </summary>
    public string PROCESS_EQUIP_CODE { get; set; }
        
    /// <summary>
    ///过机数
    /// </summary>
    public int TOTAL_NUM { get; set; }
        
    /// <summary>
    ///未读取数
    /// </summary>
    public int TEMP_NUM { get; set; }
        
    /// <summary>
    ///读取率
    /// </summary>
    public string RATIO { get; set; }
        
    /// <summary>
    ///工厂编码
    /// </summary>
    public string FACTORY_CODE { get; set; }
        
    /// <summary>
    ///创建日期
    /// </summary>
    public System.DateTime CREATED_DATE { get; set; }
        
    /// <summary>
    ///逻辑工序编码
    /// </summary>
    public string LOGIC_PROCESS { get; set; }
        
    /// <summary>
    ///过机时间
    /// </summary>
    public string TIME_VAL { get; set; }
    }
}
