//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1008
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamCube.Framework.DataAccess.Basic.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DreamCube.Framework.DataAccess.Basic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 当前数据库({0})不支持异步操作 的本地化字符串。
        /// </summary>
        internal static string AsyncOperationsNotSupported {
            get {
                return ResourceManager.GetString("AsyncOperationsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 server=,data source= 的本地化字符串。
        /// </summary>
        internal static string DataSourceToken {
            get {
                return ResourceManager.GetString("DataSourceToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DreamCube.Framework.DataAccess.Basic.DbTypeMapper.xml 的本地化字符串。
        /// </summary>
        internal static string DbTypeMapperXmlFileName {
            get {
                return ResourceManager.GetString("DbTypeMapperXmlFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;DbFactories&gt;
        ///  &lt;!--providerName值，必须与应用程序app.config(web.config)连接字符串中的providerName匹配--&gt;
        ///  &lt;!--providerType，是自定义的一种类型，根据不同的类型创建不同的工厂实例--&gt;
        ///  &lt;DBFactory 
        ///        providerName=&quot;System.Data.SqlClient&quot;
        ///        providerType=&quot;SqlClient&quot;
        ///        dbFactoryType=&quot;DreamCube.Framework.DataAccess.Sqlserver.SqlserverDbFactory,DreamCube.Framework.DataAccess.Sqlserver,Version=1.0.0.0,Culture=neutral,PublicKeyToken=null&quot;/&gt;
        ///  &lt;DBFactory
        ///        providerName=&quot;System.Data.SqlServe [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DreamCube_Framework_DataAccess_Basic_DbFactory {
            get {
                return ResourceManager.GetString("DreamCube_Framework_DataAccess_Basic_DbFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给定的命令参数不合法，命令类型必须是存储过程类型 的本地化字符串。
        /// </summary>
        internal static string ExceptionDbCommandParameterInvalidate {
            get {
                return ResourceManager.GetString("ExceptionDbCommandParameterInvalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的列名参数数组与列值参数数组个数不一致。 的本地化字符串。
        /// </summary>
        internal static string ExceptionItemsCountNotEqualValuesCount {
            get {
                return ResourceManager.GetString("ExceptionItemsCountNotEqualValuesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载数据库工厂配置文件失败. 的本地化字符串。
        /// </summary>
        internal static string ExceptionLoadDbFactoryConfig {
            get {
                return ResourceManager.GetString("ExceptionLoadDbFactoryConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 给命令提供的参数值的个数与命令的参数个数不一致 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageParameterMatchFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageParameterMatchFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新DataSet参数失败 的本地化字符串。
        /// </summary>
        internal static string ExceptionMessageUpdateDataSetArgumentFailure {
            get {
                return ResourceManager.GetString("ExceptionMessageUpdateDataSetArgumentFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在配置文件中，找不到工厂名为{0}的配置记录，无法创建工厂对象。 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotFoundFactoryRecord {
            get {
                return ResourceManager.GetString("ExceptionNotFoundFactoryRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的连接字符串没有配置providerName属性 的本地化字符串。
        /// </summary>
        internal static string ExceptionNotSetProviderName {
            get {
                return ResourceManager.GetString("ExceptionNotSetProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的字符串不能为空或者为空串 的本地化字符串。
        /// </summary>
        internal static string ExceptionNullOrEmptyString {
            get {
                return ResourceManager.GetString("ExceptionNullOrEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传入的表名数组为空 的本地化字符串。
        /// </summary>
        internal static string ExceptionTableNameArrayEmpty {
            get {
                return ResourceManager.GetString("ExceptionTableNameArrayEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在数据库【{0}】无法找到表【{1}】 的本地化字符串。
        /// </summary>
        internal static string ExceptionTableNotFound {
            get {
                return ResourceManager.GetString("ExceptionTableNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 password=,pwd= 的本地化字符串。
        /// </summary>
        internal static string PasswordToken {
            get {
                return ResourceManager.GetString("PasswordToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 table 的本地化字符串。
        /// </summary>
        internal static string SystemCreatedTableNameRoot {
            get {
                return ResourceManager.GetString("SystemCreatedTableNameRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 __unique__ 的本地化字符串。
        /// </summary>
        internal static string UniquelyParamPartValue {
            get {
                return ResourceManager.GetString("UniquelyParamPartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 user id=,uid= 的本地化字符串。
        /// </summary>
        internal static string UserNameToken {
            get {
                return ResourceManager.GetString("UserNameToken", resourceCulture);
            }
        }
    }
}
